<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompose.index.page_title'] = "Massenmailer&gt; Verfassen";
$lang['AdminCompose.!tooltip.log'] = "Wenn diese Option aktiviert ist, werden alle gesendeten E-Mails in Blesta protokolliert.";
$lang['AdminCompose.index.boxtitle'] = "Mail schreiben";
$lang['AdminCompose.index.form.from_name'] = "Absender-Name";
$lang['AdminCompose.index.form.from_address'] = "Aus der Email";
$lang['AdminCompose.index.form.subject'] = "Gegenstand";
$lang['AdminCompose.index.form.html'] = "HTML";
$lang['AdminCompose.index.form.text'] = "Text";
$lang['AdminCompose.index.form.log'] = "E-Mails protokollieren";
$lang['AdminCompose.index.text.note'] = "Wenn keine Textversion festgelegt ist, wird sie automatisch aus der HTML-Version generiert.";
$lang['AdminCompose.index.heading_client_tags'] = "Kunden-Tags";
$lang['AdminCompose.index.heading_service_tags'] = "Service-Tags";
$lang['AdminCompose.index.link_back'] = "Zurück";
$lang['AdminCompose.index.form.preview'] = "Vorschau";
$lang['AdminCompose.preview.boxtitle'] = "Mailing Vorschau";
$lang['AdminCompose.preview.email_total'] = "Gesamtzahl der E-Mail Empfänger: %1\$s"; // %1$s is the total number of contacts
$lang['AdminCompose.preview.heading.email_sample'] = "Beispiel-E-Mail";
$lang['AdminCompose.preview.text_name'] = "Von: %1\$s %2\$s"; // %1$s is the email's from name, %2$s is the email's from address
$lang['AdminCompose.preview.text_subject'] = "Betreff: %1\$s"; // %1$s
$lang['AdminCompose.preview.link_back'] = "Zurück";
$lang['AdminCompose.preview.form.send'] = "Senden";
$lang['AdminCompose.!error.parse_error'] = "Fehler beim Template parsen: %1\$s"; // %1$s is the parse error
?>