<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Config.export.id_code'] = "Kundennummer";
$lang['Config.export.first_name'] = "Vorname";
$lang['Config.export.last_name'] = "Familienname, Nachname";
$lang['Config.export.company'] = "Unternehmen";
$lang['Config.export.email'] = "E-Mail";
$lang['Config.export.date_added'] = "Hinzugefügt am";
$lang['Config.export.package_name'] = "Paket";
$lang['Config.export.service_name'] = "Service";
$lang['Config.export.service_date_renews'] = "Verlängerungsdatum";
$lang['Config.export.module_name'] = "Modul";
$lang['Config.export.module_label'] = "Modulzeile";
?>