<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MassMailerEmails.!error.job_id.valid'] = "Ungültige Job-ID";
$lang['MassMailerEmails.!error.job_id.unique'] = "Dem Job wurde bereits eine E-Mail zugewiesen.";
$lang['MassMailerEmails.!error.from_name.empty'] = "

Bitte geben Sie einen Namen ein.
";
$lang['MassMailerEmails.!error.from_address.valid'] = "

Bitte geben Sie eine gültige E-Mail-Adresse ein.
";
$lang['MassMailerEmails.!error.subject.empty'] = "

Bitte geben Sie einen Betreff ein.
";
$lang['MassMailerEmails.!error.html.empty'] = "Bitte geben Sie HTML-E-Mail-Inhalte ein.";
$lang['MassMailerEmails.!error.log.valid'] = "Die Protokolloption muss auf 0 oder 1 eingestellt sein.";
?>