<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Tags.client.id_code'] = "ID";
$lang['Tags.client.status'] = "Status";
$lang['Tags.contact.first_name'] = "Vorname";
$lang['Tags.contact.last_name'] = "Nachname";
$lang['Tags.contact.company'] = "Name der Firma";
$lang['Tags.contact.address1'] = "Adresse 1";
$lang['Tags.contact.address2'] = "Adresse (weitere Informationen)";
$lang['Tags.contact.city'] = "Stadt";
$lang['Tags.contact.state'] = "Zustand";
$lang['Tags.contact.country'] = "Land";
$lang['Tags.contact.zip'] = "Postleitzahl";
$lang['Tags.contact.email'] = "Email";
$lang['Tags.contact.date_added'] = "Mitglied seit";
$lang['Tags.package.name'] = "Paketnamen";
$lang['Tags.package.description'] = "Pakettext Beschreibung";
$lang['Tags.package.description_html'] = "Paket HTML Beschreibung";
$lang['Tags.package.status'] = "Paket Status";
$lang['Tags.service.name'] = "Etikette";
$lang['Tags.service.date_added'] = "Hinzugefügt am";
$lang['Tags.service.date_renews'] = "Verlängert am";
$lang['Tags.service.date_last_renewed'] = "Zuletzt verlängert am";
$lang['Tags.service.date_suspended'] = "Datum ausgesetzt";
$lang['Tags.service.date_canceled'] = "Storniert am";
$lang['Tags.service.status'] = "Status";
$lang['Tags.module.name'] = "Modulname";
$lang['Tags.module.label'] = "Modulzeilenbezeichnung";
?>