<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Blesta2_5.!error.host.invalid'] = "

Databasehost ist erforderlich.
";
$lang['Blesta2_5.!error.database.invalid'] = "

Datenbankname ist erforderlich.
";
$lang['Blesta2_5.!error.user.invalid'] = "Datenbankbenutzer ist erforderlich.";
$lang['Blesta2_5.!error.pass.invalid'] = "

Datenbank-Passwort ist erforderlich.
";
$lang['Blesta2_5.!error.key.invalid'] = "

Ein gültiger AESKEY ist erforderlich.
";
$lang['Blesta2_5.settings.host'] = "Datenbankhost";
$lang['Blesta2_5.settings.database'] = "Name der Datenbank";
$lang['Blesta2_5.settings.user'] = "Datenbankbenutzer";
$lang['Blesta2_5.settings.pass'] = "

Datenbankpasswort
";
$lang['Blesta2_5.settings.key'] = "AESKEI";
$lang['Blesta2_5.settings.key.info'] = "Geben Sie den Wert der AESKEY-Definition in /inc/config.php ein. Dieser sollte 32 Zeichen lang sein.";
$lang['Blesta2_5.configuration.create_packages_true'] = "Erstellen Sie automatisch alle erforderlichen Pakete während des Imports";
$lang['Blesta2_5.configuration.create_packages_false'] = "

Pakete manuell zuordnen
";
$lang['Blesta2_5.configuration.local_package'] = "

Lokales Paket
";
$lang['Blesta2_5.configuration.remote_package'] = "Remote-Paket";
$lang['Blesta2_5.configuration.no_local_packages'] = "Sie müssen Pakete erstellen, bevor Sie sie zuordnen können.";
?>