<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['404.heading_error'] = "404";
$lang['404.text_error'] = "Entschuldigung, die Seite, auf die Sie zugreifen möchten, ist nicht vorhanden oder wurde verschoben.";
$lang['404.text_go_to_home'] = "Zu Home gehen";
?>