<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['_PaymentTypes.cash'] = "Barzahlung";
$lang['_PaymentTypes.check'] = "Überprüfen";
$lang['_PaymentTypes.money_order'] = "Money Order";
$lang['_PaymentTypes.in_house_credit'] = "In House Kreditkarten";
?>