<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyGeneral.!success.localization_updated'] = "Die Lokalisierungseinstellungen wurden erfolgreich aktualisiert.";
$lang['AdminCompanyGeneral.!success.encryption_updated'] = "Die Verschlüsselungseinstellungen wurden erfolgreich aktualisiert.";
$lang['AdminCompanyGeneral.!success.contact_type_added'] = "Der Kontakttyp \"%1\$s\" wurde erfolgreich hinzugefügt."; // %1$s is the name of the contact type
$lang['AdminCompanyGeneral.!success.contact_type_updated'] = "Der Kontakttyp #%1\$s wurde erfolgreich gespeichert."; // %1$s is the name of the contact type
$lang['AdminCompanyGeneral.!success.contact_type_deleted'] = "Der Kontakttyp \"%1\$s\" wurde erfolgreich gelöscht."; // %1$s is the name of the contact type
$lang['AdminCompanyGeneral.localization.tz_format'] = "(UTC %1\$s) %2\$s"; // %1$s is the UTC offset, %2$s is the timezone name
$lang['AdminCompanyGeneral.international.boxtitle_international'] = "Internationalisierung";
$lang['AdminCompanyGeneral.international.text_language'] = "Sprache";
$lang['AdminCompanyGeneral.international.text_iso'] = "ISO 639-1, 3166-1";
$lang['AdminCompanyGeneral.international.text_options'] = "Optionen";
$lang['AdminCompanyGeneral.international.option_install'] = "Installieren";
$lang['AdminCompanyGeneral.international.option_uninstall'] = "Deinstallieren";
$lang['AdminCompanyGeneral.!notice.passphrase_set'] = "WARNUNG: Eine Passphrase wurde festgelegt. Sie müssen die Zahlungen manuell mit Ihrem Passwort paketieren. Wenn Sie Ihre Passphrase in eine leere Passphrase ändern, wird diese Anforderung entfernt.";
$lang['AdminCompanyGeneral.encryption.boxtitle_encryption'] = "Verschlüsselung";
$lang['AdminCompanyGeneral.encryption.field_current_passphrase'] = "Private-Key Passphrase";
$lang['AdminCompanyGeneral.encryption.field_private_key_passphrase'] = "Neue Passphrase für privaten Schlüssel";
$lang['AdminCompanyGeneral.encryption.field_confirm_new_passphrase'] = "Bestätigen Sie die Passphrase für den privaten Schlüssel";
$lang['AdminCompanyGeneral.encryption.field_agree'] = "Ich habe dieses Passwort an einem sicheren Ort gespeichert";
$lang['AdminCompanyGeneral.encryption.field_encryptionsubmit'] = "Passphrase updaten";
$lang['AdminCompanyGeneral.contacttypes.categorylink_addtype'] = "Kontakttyp erstellen";
$lang['AdminCompanyGeneral.contacttypes.boxtitle_types'] = "Kontaktarten";
$lang['AdminCompanyGeneral.contacttypes.heading_name'] = "Name";
$lang['AdminCompanyGeneral.contacttypes.heading_define'] = "Verwendet Sprachdefinition";
$lang['AdminCompanyGeneral.contacttypes.heading_options'] = "Optionen";
$lang['AdminCompanyGeneral.contacttypes.text_yes'] = "Ja";
$lang['AdminCompanyGeneral.contacttypes.text_no'] = "Nein";
$lang['AdminCompanyGeneral.contacttypes.option_edit'] = "Bearbeiten";
$lang['AdminCompanyGeneral.contacttypes.option_delete'] = "Löschen";
$lang['AdminCompanyGeneral.contacttypes.modal_delete'] = "Wenn Sie diesen Kontakttyp löschen, werden alle diesem Typ zugewiesenen Kontakte in den Standardtyp \"Abrechnung\" gestellt. Möchten Sie diesen Kontakttyp wirklich löschen?";
$lang['AdminCompanyGeneral.addcontacttype.boxtitle_addcontacttype'] = "Kontakttyp erstellen";
$lang['AdminCompanyGeneral.addcontacttype.field_name'] = "Name";
$lang['AdminCompanyGeneral.addcontacttype.field_is_lang'] = "Verwenden Sie die Sprachdefinition";
$lang['AdminCompanyGeneral.addcontacttype.field_contacttypesubmit'] = "Kontakttyp erstellen";
$lang['AdminCompanyGeneral.editcontacttype.boxtitle_editcontacttype'] = "Kontaktart bearbeiten";
$lang['AdminCompanyGeneral.editcontacttype.field_name'] = "Name";
$lang['AdminCompanyGeneral.editcontacttype.field_is_lang'] = "Verwende die Sprachdefinition";
$lang['AdminCompanyGeneral.editcontacttype.field_contacttypesubmit'] = "Kontaktart bearbeiten";
$lang['AdminCompanyGeneral.localization.page_title'] = "Einstellungen -> Unternehmen -> Allgemein -> Lokalisierung";
$lang['AdminCompanyGeneral.international.page_title'] = "Einstellungen > Unternehmen > Allgemein > Internationalisierung";
$lang['AdminCompanyGeneral.encryption.page_title'] = "Einstellungen > Firma > Allgemein > Verschlüsselung";
$lang['AdminCompanyGeneral.contacttypes.page_title'] = "Einstellungen> Firma> Allgemein> Kontakttypen";
$lang['AdminCompanyGeneral.addcontacttype.page_title'] = "Einstellungen > Firma > Allgemein > Kontakt Typ erstellen";
$lang['AdminCompanyGeneral.editcontacttype.page_title'] = "Einstellungen> Firma> Allgemein> Kontaktart bearbeiten";
$lang['AdminCompanyGeneral.!contacttypes.is_lang'] = "Aktivieren Sie dieses Kontrollkästchen nur, wenn Sie in der benutzerdefinierten Sprachdatei eine Sprachdefinition für diesen Kontakttyp hinzugefügt haben.";
$lang['AdminCompanyGeneral.!success.language_installed'] = "Die Sprache %1\$s wurde erfolgreich installiert."; // %1$s is the name of the language
$lang['AdminCompanyGeneral.!success.language_uninstalled'] = "Die Sprache %1\$s wurde erfolgreich deinstalliert."; // %1$s is the name of the language
$lang['AdminCompanyGeneral.!notice.international_languages'] = "Ein Crowdsourcing-Übersetzungsprojekt existiert auf translate.blesta.com. Sie können dort Sprachübersetzungen beisteuern und herunterladen. Zum Installieren entpacken Sie den Inhalt der Datei in Ihr Blesta-Installationsverzeichnis. Aktualisieren Sie dann diese Seite und klicken Sie auf den Link Installieren.";
$lang['AdminCompanyGeneral.international.confirm_install'] = "Wollen Sie die Sprache %1\$s wirklich installieren?"; // %1$s is the name of the language
$lang['AdminCompanyGeneral.international.confirm_uninstall'] = "Möchten Sie die Sprache %1\$s wirklich deinstallieren? Diese Sprache wird deinstalliert und alle E-Mail-Vorlagen in dieser Sprache werden endgültig gelöscht."; // %1$s is the name of the language
$lang['AdminCompanyGeneral.contacttypes.no_results'] = "Es gibt keine Kontakttypen.";
$lang['AdminCompanyGeneral.!notice.passphrase'] = "WARNUNG: Durch das Festlegen einer Passphrase wird verhindert, dass lokal gespeicherte Zahlungskonten automatisch verarbeitet werden. Sie werden aufgefordert, die Zahlungen manuell zu buchen, indem Sie Ihre Passphrase eingeben. Weitere Informationen zu dieser Funktion finden Sie im Handbuch.";
$lang['AdminCompanyGeneral.localization.boxtitle_localization'] = "Lokalisierung";
$lang['AdminCompanyGeneral.!success.marketing_updated'] = "Die Marketingeinstellungen wurden erfolgreich aktualisiert.";
$lang['AdminCompanyGeneral.marketing.boxtitle_marketing'] = "Marketing";
$lang['AdminCompanyGeneral.marketing.field_show_receive_email_marketing'] = "Den Kunden die Möglichkeit bieten, E-Mail-Marketing zu aktivieren / deaktivieren";
$lang['AdminCompanyGeneral.marketing.field_submit'] = "Einstellungen Aktualisieren";
$lang['AdminCompanyGeneral.!tooltip.language'] = "Die Standart Sprache die vom System genutzt wird. Um mehr Sprachen hinzuzufügen, gucken Sie nach den Internationalisierung Einstellungen.";
$lang['AdminCompanyGeneral.localization.field.localizationsubmit'] = "Einstellungen Aktualisieren";
$lang['AdminCompanyGeneral.humanverification.field_captcha_none'] = "Keine";
$lang['AdminCompanyGeneral.humanverification.field_recaptcha_pub_key'] = "reCaptcha Standort-Schlüssel";
$lang['AdminCompanyGeneral.humanverification.field_captcha_enabled_forms_client_login_forgot'] = "Kunde Benutzername vergessen";
?>