<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminLogin.index.field_password'] = "Passwort";
$lang['AdminLogin.index.field_rememberme'] = "Login auf diesem Computer speichern.";
$lang['AdminLogin.index.field_loginsubmit'] = "Einloggen";
$lang['AdminLogin.index.link_resetpassword'] = "Passwort zurücksetzen";
$lang['AdminLogin.otp.field_password'] = "Einmal-Passwort";
$lang['AdminLogin.otp.field_loginsubmit'] = "Anmelden";
$lang['AdminLogin.otp.link_login'] = "Abbrechen, Anmelden";
$lang['AdminLogin.reset.title_adminarea'] = "%1\$s | Passwort zurücksetzten"; // %1$s is the company name
$lang['AdminLogin.reset.field_resetsubmit'] = "Passwort zurücksetzten ";
$lang['AdminLogin.reset.link_login'] = "Abbrechen, Login";
$lang['AdminLogin.confirmreset.title_adminarea'] = "%1\$s | Zurücksetzen des Passworts bestätigen"; // %1$s is the company name
$lang['AdminLogin.confirmreset.field_new_password'] = "Neues Kennwort";
$lang['AdminLogin.confirmreset.field_confirm_password'] = "Passwort bestätigen";
$lang['AdminLogin.confirmreset.field_resetsubmit'] = "Passwort festlegen";
$lang['AdminLogin.confirmreset.link_login'] = "Abbrechen, Anmelden";
$lang['AdminLogin.!error.unknown_user'] = "Dieser Benutzername wird nicht erkannt oder das Passwort kann nicht zurückgesetzt werden.";
$lang['AdminLogin.!success.reset_sent'] = "Eine Bestätigungs-E-Mail wurde an die angegebene Adresse gesendet.";
$lang['AdminLogin.index.page_title'] = "Login";
$lang['AdminLogin.otp.page_title'] = "OTP-Anmeldung";
$lang['AdminLogin.reset.page_title'] = "Passwort zurücksetzen";
$lang['AdminLogin.confirmreset.page_title'] = "Bestätigen Sie das Passwort zurücksetzen";
$lang['AdminLogin.setup.page_title'] = "Einmaliges Setup";
$lang['AdminLogin.setup.title_adminarea'] = "Einrichtung"; // %1$s is the company name
$lang['AdminLogin.setup.field_license_key'] = "Lizenzschlüssel";
$lang['AdminLogin.setup.heading_create_account'] = "Erstellen Sie Ihr Mitarbeiterkonto";
$lang['AdminLogin.setup.field_first_name'] = "Vorname";
$lang['AdminLogin.setup.field_last_name'] = "Familienname, Nachname";
$lang['AdminLogin.setup.field_username'] = "Benutzername";
$lang['AdminLogin.setup.field_email'] = "Email Adresse";
$lang['AdminLogin.setup.field_password'] = "Passwort";
$lang['AdminLogin.setup.field_confirm_password'] = "Passwort bestätigen";
$lang['AdminLogin.setup.field_enter_key_true'] = "Ich muss einen Lizenzschlüssel eingeben";
$lang['AdminLogin.setup.field_enter_key_false'] = "Ich möchte die 30-tägige Testlizenz aktivieren.";
$lang['AdminLogin.setup.field_submit'] = "Fertig";
$lang['AdminLogin.index.title_adminarea'] = "%1\$s | Mitarbeiterbereich"; // %1$s is the company name
$lang['AdminLogin.index.field_username'] = "Benutzername";
$lang['AdminLogin.reset.field_username'] = "Benutzername";
$lang['AdminLogin.!info.reset_password'] = "Geben Sie Ihren Benutzernamen ein und ein zeitkritischer Link wird Ihnen per E-Mail zugesandt, damit Sie ein neues Passwort festlegen können.";
$lang['AdminLogin.!info.otp'] = "Für diesen Benutzer ist eine Zwei-Faktor-Authentifizierung erforderlich. Bitte geben Sie unten Ihr OTP (Einmalpasswort) ein.";
$lang['AdminLogin.otp.title_adminarea'] = "%1\$s - Personalbereich"; // %1$s is the company name
?>