<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemUpgrade.index.boxtitle_upgrade'] = "

Upgrade-Optionen
";
$lang['AdminSystemUpgrade.index.field_upgradesubmit'] = "Update Einstellungen";
$lang['AdminSystemUpgrade.index.page_title'] = "Einstellungen -> System -> Upgrade Optionen";
$lang['AdminSystemUpgrade.index.no_results'] = "Ein Upgrade steht derzeit nicht zur Verfügung.";
?>