<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminDialog.confirm.text_yes'] = "Ja";
$lang['AdminDialog.confirm.text_no'] = "Nein";
$lang['AdminDialog.password.field_modal_password'] = "Passwort";
$lang['AdminDialog.password.field_modal_password_copied'] = "Ich habe dieses Passwort an einen sicheren Ort kopiert";
$lang['AdminDialog.password.btn_generate'] = "Generieren";
$lang['AdminDialog.password.btn_modal_password'] = "Passwort";
$lang['AdminDialog.password.btn_cancel'] = "Stornieren";
$lang['AdminDialog.password.btn_use_password'] = "Passwort verwenden";
?>