<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Backup.!error.driver.support'] = "Der Datenbanktreiber wird nicht unterstützt.";
$lang['Backup.!error.temp_dir.writable'] = "Das temp Verzeichnis ist nicht beschreibbar.";
$lang['Backup.frequencies.hour'] = "Stunde";
$lang['Backup.frequencies.hours'] = "%1\$s Stunden"; // %1$s is the number of hours
$lang['Backup.frequencies.day'] = "Tag";
$lang['Backup.frequencies.days'] = "%1\$s Tage"; // %1$s is the number of days
$lang['Backup.!error.amazons3_failed'] = "Das Amazon S3 Backup ist fehlgeschlagen.";
$lang['Backup.frequencies.never'] = "Niemals
";
$lang['Backup.!error.ftp_failed'] = "Die SFTP-Sicherung ist fehlgeschlagen.";
?>