<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientContacts.!success.contact_deleted'] = "Der Kontakt %1\$s %2\$s wurde erfolgreich gelöscht!"; // %1$s is the contact's first name, %2$s is the contact's last name
$lang['ClientContacts.!success.contact_updated'] = "Der Kontakt wurde erfolgreich aktualisiert!";
$lang['ClientContacts.!success.contact_added'] = "Der Kontakt wurde erfolgreich erstellt!";
$lang['ClientContacts.index.page_title'] = "Kunde #%1\$s Kontakte"; // %1$s is the client ID number
$lang['ClientContacts.index.create_contact'] = "Kontakt hinzufügen";
$lang['ClientContacts.index.boxtitle_contacts'] = "Kontakte";
$lang['ClientContacts.index.heading_name'] = "Name";
$lang['ClientContacts.index.heading_email'] = "Email";
$lang['ClientContacts.index.heading_type'] = "Typ";
$lang['ClientContacts.index.heading_options'] = "Optionen";
$lang['ClientContacts.index.option_edit'] = "Bearbeiten";
$lang['ClientContacts.index.option_delete'] = "Löschen";
$lang['ClientContacts.index.confirm_delete'] = "Möchten Sie diesen Kontakt wirklich löschen?";
$lang['ClientContacts.add.page_title'] = "Kunde #%1\$s Kontakt hinzufügen"; // %1$s is the client ID number
$lang['ClientContacts.add.boxtitle_create'] = "Kontakt hinzufügen";
$lang['ClientContacts.add.heading_settings'] = "Zusätzliche Einstellungen";
$lang['ClientContacts.add.field_contact_type'] = "Kontaktart";
$lang['ClientContacts.add.field_addsubmit'] = "Kontakt erstellen";
$lang['ClientContacts.edit.page_title'] = "Client # %1\$s Kontakt bearbeiten"; // %1$s is the client ID number
$lang['ClientContacts.edit.boxtitle_edit'] = "Kontakt bearbeiten";
$lang['ClientContacts.edit.heading_settings'] = "

Zusätzliche Einstellungen
";
$lang['ClientContacts.edit.field_contact_type'] = "Kontakt Typ";
$lang['ClientContacts.edit.field_editsubmit'] = "Kontakt aktualisieren";
$lang['ClientContacts.setcontactview.text_none'] = "Keiner";
$lang['ClientContacts.contact_info.heading_contact'] = "Kontakt Informationen";
$lang['ClientContacts.contact_info.field_contact_id'] = "Kontaktinformationen kopieren von";
$lang['ClientContacts.contact_info.field_first_name'] = "Vorname";
$lang['ClientContacts.contact_info.field_last_name'] = "Nachname";
$lang['ClientContacts.contact_info.field_company'] = "Firma";
$lang['ClientContacts.contact_info.field_address1'] = "Adresse 1";
$lang['ClientContacts.contact_info.field_address2'] = "Adresse 2";
$lang['ClientContacts.contact_info.field_city'] = "Stadt";
$lang['ClientContacts.contact_info.field_country'] = "Land";
$lang['ClientContacts.contact_info.field_state'] = "Bundesstaat";
$lang['ClientContacts.contact_info.field_zip'] = "Postleitzahl";
$lang['ClientContacts.contact_info.field_email'] = "Email";
$lang['ClientContacts.phone_numbers.heading_phone'] = "Telefonnummern";
$lang['ClientContacts.phone_numbers.field_phonetype'] = "Art";
$lang['ClientContacts.phone_numbers.field_phonelocation'] = "Standort";
$lang['ClientContacts.phone_numbers.field_phonenumber'] = "Nummer";
$lang['ClientContacts.phone_numbers.text_remove'] = "Entfernen";
$lang['ClientContacts.index.no_results'] = "Sie haben keine Kontakte. Klicken Sie auf den Knopf unten, um Kontakte hinzuzufügen.";
$lang['ClientContacts.!info.no_contacts'] = "Sie haben derzeit keine Kontakte, fügen Sie unten Ihren ersten Kontakt hinzu.
";
$lang['ClientContacts.contact_info.text_select_contact'] = "Sie können einen bestehenden Vertrag angeben, um dieses Formular mit vorgeschlagenen Werten zu befüllen.";
$lang['ClientContacts.phone_numbers.field_phoneoptions'] = "Optionen";
$lang['ClientContacts.phone_numbers.categorylink_number'] = "Zusätzliche hinzufügen";
$lang['ClientContacts.add.heading_contact'] = "Kontaktinformation";
$lang['ClientContacts.add.heading_authentication'] = "Authentifizierung";
$lang['ClientContacts.add.field_enable_login'] = "Aktivieren Sie die Anmeldung";
$lang['ClientContacts.add.field_username'] = "Nutzername";
$lang['ClientContacts.add.field_new_password'] = "Neues Kennwort";
$lang['ClientContacts.add.field_confirm_password'] = "Passwort Bestätigen";
$lang['ClientContacts.add.heading_permissions'] = "Berechtigungen";
$lang['ClientContacts.edit.heading_contact'] = "Kontakt-Informationen";
$lang['ClientContacts.edit.heading_authentication'] = "Authentifizierung";
$lang['ClientContacts.edit.field_enable_login'] = "Login aktivieren";
$lang['ClientContacts.edit.field_username'] = "Benutzername";
$lang['ClientContacts.edit.field_new_password'] = "Neues Kennwort";
$lang['ClientContacts.edit.field_confirm_password'] = "Passwort bestätigen";
$lang['ClientContacts.edit.heading_permissions'] = "Berechtigungen";
$lang['ClientContacts.tooltip.client_invoices'] = "Zeigen Sie Rechnungen auf dem Dashboard an sowie Benachrichtigungen zur Zahlungserinnerung.";
$lang['ClientContacts.tooltip.client_services'] = "

Zeigen Sie Dienste auf dem Dashboard an, und lassen Sie sie verwalten.
";
$lang['ClientContacts.tooltip.client_transactions'] = "Transaktionen im Dashboard anzeigen";
$lang['ClientContacts.tooltip.client_contacts'] = "Erlaube, dass Kontakte verwaltet werden.";
$lang['ClientContacts.tooltip.client_accounts'] = "

Verwalten von Zahlungskonten erlauben.
";
$lang['ClientContacts.tooltip._invoice_delivery'] = "Lassen Sie die Rechnungsanlieferungsmethode angezeigt und geändert werden.";
$lang['ClientContacts.tooltip._credits'] = "

Erlauben Sie das Anzeigen der Kontoguthaben.
";
$lang['ClientContacts.contact_info.field_title'] = "

Titel
";
?>