<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientTransactions.index.page_title'] = "Kunde #%1\$s Transaktionen"; // %1$s is the client ID number
$lang['ClientTransactions.index.boxtitle_transactions'] = "Transaktionen";
$lang['ClientTransactions.index.category_approved'] = "Bestätigt";
$lang['ClientTransactions.index.category_declined'] = "Abgelehnt";
$lang['ClientTransactions.index.heading_type'] = "Typ";
$lang['ClientTransactions.index.heading_amount'] = "Summe";
$lang['ClientTransactions.index.heading_credited'] = "Belastet";
$lang['ClientTransactions.index.heading_applied'] = "Angewendet";
$lang['ClientTransactions.index.heading_number'] = "Nummer";
$lang['ClientTransactions.index.heading_date'] = "Datum";
$lang['ClientTransactions.index.no_results'] = "Sie haben keine %1\$s-Transaktionen."; // %1$s is the language for the transaction category type (e.g. Approved, Declined)
$lang['ClientTransactions.applied.heading_invoice'] = "Rechnung";
$lang['ClientTransactions.applied.heading_amount'] = "Menge";
$lang['ClientTransactions.applied.heading_appliedon'] = "Aufgetragen auf";
$lang['ClientTransactions.applied.no_results'] = "Diese Transaktion wurde nicht auf Rechnungen angewendet.";
?>