<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Contacts.!error.client_id.exists'] = "Ungültige Kunden Nr.";
$lang['Contacts.!error.user_id.exists'] = "Ungültige Benutzer-Id.";
$lang['Contacts.!error.contact_type.format'] = "Ungültiger Kontakt Typ";
$lang['Contacts.!error.contact_type_id.format'] = "Ungültige Kontakttyp-ID";
$lang['Contacts.!error.first_name.empty'] = "Bitte geben Sie einen Vornamen an.";
$lang['Contacts.!error.last_name.empty'] = "Bitte gehen Sie einen Nachnamen an.";
$lang['Contacts.!error.title.length'] = "Der Titel darf nicht länger als 64 Zeichen sein.";
$lang['Contacts.!error.company.length'] = "Die Länge des Unternehmens darf 128 Zeichen nicht überschreiten.";
$lang['Contacts.!error.email.format'] = "Ungültige Email Adresse";
$lang['Contacts.!error.state.length'] = "Die Staatslänge darf 3 Zeichen nicht überschreiten.";
$lang['Contacts.!error.state.country_exists'] = "Bitte wählen sie ein Land, dass zum ausgewählten Staat gehört.";
$lang['Contacts.!error.country.length'] = "Landeskürzel darf nicht 3 Zeichen überschreiten.";
$lang['Contacts.!error.contact_id.exists'] = "Ungültige Kontakt ID.";
$lang['Contacts.!error.number.empty'] = "Bitte geben Sie eine Telefonnummer an.";
$lang['Contacts.!error.type.format'] = "Ungültiger Typ.";
$lang['Contacts.!error.location.format'] = "Ungültiger Ort.";
$lang['Contacts.!error.id.exists'] = "

Ungültige Kontakt-ID-Nummer
";
$lang['Contacts.!error.company_id.format'] = "Ungültige Firmen ID.";
$lang['Contacts.!error.name.empty'] = "Bitte geben Sie einen Namen ein.";
$lang['Contacts.!error.is_lang.format'] = "is_lang muss eine Zahl sein.";
$lang['Contacts.!error.is_lang.length'] = "

Die Länge von is_lang darf 1 Zeichen nicht überschreiten.
";
$lang['Contacts.!error.contact_type_id.exists'] = "

Ungültige Kontakttyp-ID
";
$lang['Contacts.getcontacttypes.primary'] = "Primär";
$lang['Contacts.getcontacttypes.billing'] = "Rechnung";
$lang['Contacts.getcontacttypes.other'] = "Andere";
$lang['Contacts.getnumbertypes.phone'] = "Telefon";
$lang['Contacts.getnumbertypes.fax'] = "Fax";
$lang['Contacts.getnumberlocations.home'] = "Start";
$lang['Contacts.getnumberlocations.work'] = "Arbeit";
$lang['Contacts.getnumberlocations.mobile'] = "Mobil";
$lang['Contacts.!error.contact_type.inv_address_to'] = "Rechnungen werden an diesen Kontakt adressiert und müssen vor dem Aktualisieren dieses Kontakts geändert werden.";
$lang['Contacts.!error.contact_id.primary'] = "Der primäre Kundenkontakt darf nicht gelöscht werden.";
$lang['Contacts.getPermissionOptions.client_invoices'] = "Rechnungen";
$lang['Contacts.getPermissionOptions.client_services'] = "Dienstleistungen";
$lang['Contacts.getPermissionOptions.client_transactions'] = "Transaktionen";
$lang['Contacts.getPermissionOptions.client_contacts'] = "Kontakte";
$lang['Contacts.getPermissionOptions.client_accounts'] = "Zahlungskonten";
$lang['Contacts.getPermissionOptions._invoice_delivery'] = "Rechnungszustellung";
$lang['Contacts.getPermissionOptions._credits'] = "Kredite";
$lang['Contacts.!error.title.empty'] = "

Bitte geben Sie einen Titel ein.
";
$lang['Contacts.!error.company.empty'] = "

Bitte geben Sie eine Firma ein.
";
$lang['Contacts.!error.city.empty'] = "

Bitte geben Sie eine Stadt ein.
";
$lang['Contacts.!error.state.empty'] = "Bitte wählen Sie ein Bundesland / Bundesstaat";
$lang['Contacts.!error.country.empty'] = "Bitte wähle ein Land.";
$lang['Contacts.!error.address1.empty'] = "Bitte geben Sie die erste Zeile Ihrer Adresse ein.";
$lang['Contacts.!error.address2.empty'] = "

Bitte geben Sie die zweite Zeile Ihrer Adresse ein.
";
$lang['Contacts.!error.zip.empty'] = "Bitte geben Sie eine Postleitzahl ein.";
$lang['Contacts.!error.email.unique'] = "E-Mail-Adresse ist bereits vergeben.";
$lang['Contacts.!error.phone.required'] = "Bitte geben Sie mindestens eine Telefonnummer ein.";
?>