<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['EmailVerifications.!error.contact_id.exists'] = "Ungültige Kontakt-ID.";
$lang['EmailVerifications.!error.verified.valid'] = "Das verifizierte Feld muss \"1\" oder \"0\" sein.";
?>