<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['EmailGroups.!error.action.empty'] = "

Bitte geben Sie eine Aktion ein.
";
$lang['EmailGroups.!error.action.length'] = "Die Aktionslänge darf 64 Zeichen nicht überschreiten.";
$lang['EmailGroups.!error.action.unique'] = "Eine Aktion mit diesem Name existiert bereits.";
$lang['EmailGroups.!error.type.format'] = "Ungültiger Typ.";
$lang['EmailGroups.!error.group_id.exists'] = "Ungültige E-Mail-Gruppen-ID.";
$lang['EmailGroups.!error.notice_type.valid'] = "Der Hinweistyp muss auf bcc oder auf gesetzt sein.";
?>