<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Messages.!error.message_group_id.valid'] = "Ungültige Nachrichtengruppen-ID.";
$lang['Messages.!error.company_id.valid'] = "Ungültige Firmen-ID.";
$lang['Messages.!error.content.format'] = "Der Nachrichteninhalt muss ein Array sein.";
$lang['Messages.getStatusTypes.active'] = "Aktiv";
?>