<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ModuleManager.!error.company_id.valid'] = "

Die Firmen-ID ist ungültig.
";
$lang['ModuleManager.!error.class.valid'] = "

Klasse ist ungültig
";
$lang['ModuleManager.!error.name.valid'] = "Name ist ungültig.";
$lang['ModuleManager.!error.version.valid'] = "

Version ist ungültig
";
$lang['ModuleManager.!error.name.empty'] = "

Sie müssen einen Namen für die Gruppe angeben.
";
$lang['ModuleManager.!error.module_rows[].valid'] = "

Eine oder mehrere der angegebenen Zeilen gehören nicht zu diesem Modul.
";
$lang['ModuleManager.!error.module_row_id.assigned_package'] = "

Die Zeile kann nicht gelöscht werden, da sie zu einem oder mehreren Paketen gehört.
";
$lang['ModuleManager.!error.module_group_id.assigned_package'] = "Die Gruppe kann nicht gelöscht werden, da es zu einem oder mehreren Paketen gehört.";
$lang['ModuleManager.!error.module_row_id.assigned_service'] = "Die Zeile kann nicht gelöscht werden, da sie zu einem oder mehreren Diensten gehört.";
$lang['ModuleManager.!error.module_id.assigned_package'] = "Das Modul kann nicht deinstalliert werden, da es von einem oder mehreren aktiven Paketen verwendet wird.";
$lang['ModuleManager.!error.module_id.assigned_service'] = "Das Modul kann nicht deinstalliert werden, da es von einem oder mehreren nicht entwerteten Diensten verwendet wird.";
$lang['ModuleManager.!error.force_limits.valid'] = "

Ob strikte Grenzwerte erzwungen werden sollen, muss auf 0 oder 1 gesetzt werden.
";
$lang['ModuleManager.!error.type_id.valid'] = "Typ-ID ist ungültig.";
?>