<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ReportManager.!error.type.valid'] = "Bitte wähle eine gültige Berichtsart aus.";
$lang['ReportManager.!error.format.valid'] = "Bitte wählen Sie ein gültiges Berichtsformat.";
$lang['ReportManager.!error.temp_dir.writable'] = "Das temporäre Verzeichnis ist schreibgeschützt oder der Bericht konnte nicht geschrieben werden.";
$lang['ReportManager.getformats.csv'] = "CSV";
$lang['ReportManager.!error.name.valid'] = "Der Bericht benötigt einen Name.";
$lang['ReportManager.!error.query.empty'] = "Bericht muss eine Abfrage enthalten.";
$lang['ReportManager.!error.query.valid'] = "Es ist nur eine Abfrage zulässig, und es muss sich um eine SELECT-Abfrage handeln.";
$lang['ReportManager.!error.date_created.format'] = "Das Erstellungsdatum hat ein ungültiges Format.";
$lang['ReportManager.reportfieldtypes.text'] = "Text";
$lang['ReportManager.reportfieldtypes.select'] = "Wählen";
$lang['ReportManager.reportfieldtypes.date'] = "Datum";
$lang['ReportManager.reportrequiredtypes.no'] = "Nein";
$lang['ReportManager.reportrequiredtypes.yes'] = "Ja";
$lang['ReportManager.reportrequiredtypes.custom'] = "

Custom Regex
";
$lang['ReportManager.getformats.json'] = "JSON";
?>