<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ServiceChanges.!error.id.exists'] = "Ungültige Dienständerungs-ID";
$lang['ServiceChanges.!error.service_id.exists'] = "

Ungültige Service-ID
";
$lang['ServiceChanges.!error.invoice_id.exists'] = "Ungültige Rechnungsnummer.";
$lang['ServiceChanges.!error.invoice_id.unique'] = "Die Rechnungs-ID ist bereits für eine Serviceänderung festgelegt und kann nicht erneut festgelegt werden.";
$lang['ServiceChanges.!error.status.valid'] = "Bitte wählen Sie einen gültigen Status.";
$lang['ServiceChanges.status.pending'] = "Ausstehend";
$lang['ServiceChanges.status.completed'] = "Abgeschlossen";
$lang['ServiceChanges.status.error'] = "Fehlerb";
$lang['ServiceChanges.status.canceled'] = "Abgebrochen";
?>