<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ServiceInvoices.!error.service_id.exists'] = "Ungültige Dienst-ID";
$lang['ServiceInvoices.!error.invoice_id.exists'] = "

Ungültige Rechnungskennung
";
?>