<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SystemEvents.!error.event.empty'] = "Bitte geben Sie einen Ereignisnamen ein.";
$lang['SystemEvents.!error.event.length'] = "Das Ereignis darf %1\$s Zeichen nicht überschreiten."; // %1$s is the maximum number of characters allowed
$lang['SystemEvents.!error.observer.valid'] = "

Bitte geben Sie einen aufrufbaren Beobachter nach Namespace oder Dateisystempfad an.
";
?>