<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Taxes.!error.company_id.exists'] = "

Ungültige Firmen-ID
";
$lang['Taxes.!error.level.format'] = "Das Steuerlevel muss eine Nummer sein.";
$lang['Taxes.!error.level.length'] = "Die Steuerstufenlänge darf 2 Zeichen nicht überschreiten.";
$lang['Taxes.!error.name.length'] = "Die Länge des Namens der Steuer darf 64 Zeichen nicht überschreiten.";
$lang['Taxes.!error.amount.format'] = "Der Wert muss eine Zahl sein";
$lang['Taxes.!error.type.format'] = "Ungültige Steuerart";
$lang['Taxes.!error.status.format'] = "Ungültigen Status.";
$lang['Taxes.!error.tax_id.exists'] = "Ungültige Steuer-ID";
$lang['Taxes.getTaxStatus.active'] = "Aktiv";
$lang['Taxes.getTaxStatus.inactive'] = "Inaktiv";
$lang['Taxes.getTaxTypes.exclusive'] = "Ecklusive";
$lang['Taxes.!error.country.valid'] = "Land ist kein gültiger Ländercode nach ISO 3166-1.";
$lang['Taxes.!error.state.valid'] = "Der Status ist kein gültiger ISO 3166-2-Unterteilungscode.";
?>