<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Themes.!error.id.exists'] = "

Das von Ihnen ausgewählte Theme ist nicht vorhanden.
";
$lang['Themes.!error.company_id.exists'] = "Ungültige Firmen-ID";
$lang['Themes.!error.company_id.isset'] = "Nur Firmenspezifische Themen können gelöscht werden.";
$lang['Themes.!error.company_id.set'] = "Nur unternehmensspezifische Themen können aktualisiert werden.";
$lang['Themes.!error.name.empty'] = "Bitte geben Sie einen Design-Namen ein.";
$lang['Themes.!error.name.length'] = "Der Themenname darf nicht länger als 64 Zeichen sein.";
$lang['Themes.!error.colors.exist'] = "Bitte geben Sie einen gültigen 6-stelligen Hex-Code für jede Farbe ein .";
$lang['Themes.!error.type.format'] = "Der angegebene Thematyp ist ungültig.";
$lang['Themes.type.admin'] = "Personal";
$lang['Themes.type.client'] = "Klient";
?>