<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientDataPortability.name'] = "Client Data Portabilität";
$lang['ClientDataPortability.options.field_client_id'] = "

Kunden ID
";
$lang['ClientDataPortability.!error.client_id'] = "Die Client-ID ist nicht gültig.";
$lang['ClientDataPortability.!tooltip.client_id'] = "Dies ist die interne Kundennummer, die in der URL angezeigt wird, wenn Sie ein Kunden-Profil anzeigen.";
?>