<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Cart.index.table_price'] = "Preis";
$lang['Cart.index.remove_item'] = "Löschen";
$lang['Cart.index.order_more_btn'] = "Drücken um andere Services zu bestellen
";
?>