<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Domain.lookup.title'] = "Überprüfen Sie die Verfügbarkeit der Domain";
$lang['Domain.lookup.description'] = "Suchen Sie zunächst nach einer Domain oder überspringen Sie diesen Schritt, indem Sie auf \"Andere Artikel bestellen\" klicken.";
$lang['Domain.lookup.domain_placeholder'] = "yourdomain.com";
$lang['Domain.lookup.transfer_btn'] = "

Transfer
";
$lang['Domain.lookup.lookup_btn'] = "Verfügbarkeit prüfen";
$lang['Domain.lookup.other_btn'] = "

Überspringen, andere Artikel bestellen
";
$lang['Domain.lookup.domains_header_available'] = "

Glückwunsch, diese Domain ist verfügbar.
";
$lang['Domain.lookup.domains_header_unavailable'] = "Sorry, diese Domain ist nicht verfügbar.";
$lang['Domain.lookup.domains_domain_name'] = "Domainname";
$lang['Domain.lookup.domains_status'] = "Status";
$lang['Domain.lookup.domains_term'] = "

Begriff
";
$lang['Domain.lookup.domain_available'] = "Verfügbar";
$lang['Domain.lookup.domain_unavailable'] = "Nicht verfügbar";
$lang['Domain.lookup.order_btn'] = "

Auftrag ausgewählt
";
$lang['Domain.lookup.term'] = "%1\$s %2\$s @ %3\$s"; // %1$s is the term, %2$s is the period, %3$s is the currency price
$lang['Domain.lookup.term_onetime'] = "%1\$s je %2\$s"; // %1$s is the period, %2$s is the currency price
$lang['Domain.lookup.heading_price'] = "Preis";
$lang['Domain.lookup.heading_transfer_price'] = "Transferpreis";
$lang['Domain.lookup.term_year'] = "%1\$s Jahr"; // %1$s is the term
?>