<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminManagePlugin.!success.settings_saved'] = "Die Einstellungen wurden gespeichert.";
$lang['AdminManagePlugin.index.page_title'] = "

Automatisch abbrechen
";
$lang['AdminManagePlugin.index.boxtitle_auto_cancel'] = "

Automatisch beenden
";
$lang['AdminManagePlugin.index.heading_settings'] = "Einstellungen";
$lang['AdminManagePlugin.index.field.schedule_days'] = "Planen Sie die Stornierungstage nach dem Suspendieren ein";
$lang['AdminManagePlugin.index.field.cancel_days'] = "Service beenden, wenn Service eingestellt, nach wieviel Tagen";
$lang['AdminManagePlugin.index.field.submit'] = "sparen";
$lang['AdminManagePlugin.getDays.never'] = "noch nie";
$lang['AdminManagePlugin.getDays.text_day'] = "%1\$s Tag";
$lang['AdminManagePlugin.getDays.text_days'] = "%1\$s Tage"; // %1$s is the number of days
?>