<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AutoCancelSettings.!error.schedule_days.valid'] = "Schedule Cancellation Days nach Aussetzung ist nicht gültig.";
$lang['AutoCancelSettings.!error.cancel_days.valid'] = "Service-Tage nach der Deaktivierung abbrechen ist nicht gültig.";
$lang['AutoCancelSettings.!error.cancel_days.greater'] = "Cancel Services Days After Suspended must be greater than or equal to Schedule Cancellation Days After Suspended";
?>