<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.!notice.type_warning'] = "Wenn Sie den Erweiterungstyp ändern, werden alle für diese Erweiterung gespeicherten Einstellungen unwiderruflich gelöscht.";
$lang['AdminMain.!success.plugin_created'] = "Das neue Plugin wurde erfolgreich erstellt und befindet sich unter %1\$s"; // Where %1$s is the path to the created plugin's directory
$lang['AdminMain.getfilelocations.custom'] = "Benutzerdefiniert";
$lang['AdminMain.index.extension_add'] = "Zusatz Addon";
$lang['AdminMain.index.heading_code_examples'] = "Codebeispiele";
$lang['AdminMain.index.heading_options'] = "Optionen";
$lang['AdminMain.index.option_edit'] = "Bearbeiten";
$lang['AdminMain.general.code_examples'] = "Beispielcode einfügen";
$lang['AdminMain.confirm.custom_path'] = "Benutzerdefinierter Pfad";
?>