<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminModule.getoptionalfunctions.tooltip_unsuspendService'] = "Wird aufgerufen, um Modulaktionen bei der Aussetzung des Dienstes durchzuführen.";
$lang['AdminModule.getoptionalfunctions.tooltip_editPackage'] = "Führt alle erforderlichen Aktionen aus, um das Paket auf dem Remote-Server zu bearbeiten. Setzt Eingabefehler bei Fehler, wodurch das Paket nicht bearbeitet werden kann.";
$lang['AdminModule.getoptionalfunctions.tooltip_upgrade'] = "Führt die Migration der Daten von \$current_version (der aktuell installierten Version) auf das angegebene Dateisystem durch. Setzt bei einem Fehlschlag Eingabefehler, so dass das Modul nicht aktualisiert werden kann.";
$lang['AdminModule.getoptionalfunctions.tooltip_selectModuleRow'] = "Legt fest, welche Modulreihe versucht werden soll, wenn ein Dienst für die angegebene Gruppe bereitgestellt wird, basierend auf der für diese Gruppe festgelegten Bestellmethode.";
$lang['AdminModule.basic.author_name'] = "Autorenname";
$lang['AdminModule.basic.author_url'] = "Autoren-URL";
$lang['AdminModule.basic.author_row_add'] = "Autor hinzufügen";
$lang['AdminModule.fields.heading_module_row_fields'] = "Modul Zeilenfelder";
$lang['AdminModule.fields.name_key'] = "Namensschlüssel";
$lang['AdminModule.fields.tooltip_label'] = "Der Anzeigename des Feldes";
$lang['AdminModule.fields.placeholder_package_name'] = "z.B. package_field";
$lang['AdminModule.fields.package_row_add'] = "Paketfeld hinzufügen";
$lang['AdminModule.fields.text_remove'] = "Entfernen";
$lang['AdminModule.fields.features'] = "Weiter - Zusätzliche Funktionen";
$lang['AdminModule.features.level'] = "Level";
$lang['AdminModule.features.name'] = "Name";
$lang['AdminModule.features.tooltip_cron_label'] = "Angezeigter Name der Cron-Aufgabe";
$lang['AdminModule.features.tooltip_type'] = "Die Art der Zeitsteuerung, die für die Cron-Aufgabe verwendet werden soll (Zeit oder Intervall)";
$lang['AdminModule.features.tooltip_time'] = "Die tägliche 24-Stunden-Zeit, zu der diese Aufgabe ausgeführt werden soll (z. B. \"14:25\") ODER Das Intervall in Minuten, in dem diese Cron-Aufgabe ausgeführt werden soll";
$lang['AdminModule.features.placeholder_tab_label'] = "z.B. Passwort ändern";
$lang['AdminModule.features.service_tab_row_add'] = "Registerkarte Service Management hinzufügen";
$lang['AdminModule.features.text_options'] = "Optionen";
$lang['AdminModule.getoptionalfunctions.tooltip_getDomainIsLocked'] = "Gibt zurück, ob die Domain gesperrt ist oder nicht, gibt \"boolean\" zurück.";
$lang['AdminModule.getoptionalfunctions.tooltip_setNameserverIps'] = "Legt die Nameserver für einen bestimmten Domainnamen fest.";
$lang['AdminModule.getoptionalfunctions.tooltip_setDomainContacts'] = "Aktualisiert die Liste der mit einer Domain verbundenen Kontakte.";
$lang['AdminModule.basic.static_tlds'] = "Statische Definition von TLDs";
$lang['AdminModule.basic.placeholder_tlds'] = ".com, .net, .org";
$lang['AdminModule.fields.package_fields_epp_code_label'] = "EPP Code";
?>