<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMerchant.getsupportedfeatures.cc_offsite'] = "Offsite-Kreditkarte";
$lang['AdminMerchant.basic.text_options'] = "Optionen";
$lang['AdminMerchant.basic.tooltip_signup_url'] = "Die URL zur Anmeldeseite des Portals (Gateways)";
$lang['AdminMerchant.basic.tooltip_currencies'] = "Eine durch Kommata getrennte Liste der unterstützten Währungen (z. B. USD, JPY, EUR)";
$lang['AdminMerchant.basic.placeholder_author_name'] = "z.B. Blesta";
$lang['AdminMerchant.fields.encryptable'] = "Verschlüsselbar";
$lang['AdminMerchant.fields.tooltip_label'] = "Der Anzeigename des Feldes";
$lang['AdminMerchant.fields.text_options'] = "Optionen";
$lang['AdminMerchant.fields.text_remove'] = "Entfernen";
$lang['AdminMerchant.features.heading_supported_features'] = "Unterstützte Funktionen";
?>