<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminNonmerchant.basic.heading_authors'] = "Autoren";
$lang['AdminNonmerchant.basic.currencies'] = "Währungen";
$lang['AdminNonmerchant.basic.text_options'] = "Optionen";
$lang['AdminNonmerchant.basic.author_row_add'] = "Autor hinzufügen";
$lang['AdminNonmerchant.basic.tooltip_currencies'] = "Eine durch Kommata getrennte Liste der unterstützten Währungen (z. B. USD, JPY, EUR)";
$lang['AdminNonmerchant.basic.placeholder_author_name'] = "z. B. Blesta";
$lang['AdminNonmerchant.basic.fields'] = "Nächstes Konfigurations Feld";
$lang['AdminNonmerchant.fields.label'] = "Etikett";
$lang['AdminNonmerchant.fields.type'] = "Typ";
$lang['AdminNonmerchant.fields.tooltip_label'] = "Der Anzeigename des Feldes";
$lang['AdminNonmerchant.fields.tooltip_tooltip'] = "Der Text des Tooltips, der neben dem Feld angezeigt werden soll (leer lassen, um keinen Tooltip zu haben)";
$lang['AdminNonmerchant.fields.text_remove'] = "Entfernen";
?>