<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['FormRules.modulebasic.authors[][name].empty'] = "Bitte geben Sie für jeden Autor einen Namen an.";
$lang['FormRules.modulefields.module_rows[][label].empty'] = "Bitte geben Sie für jedes Modulzeilenfeld eine Beschriftung ein.";
$lang['FormRules.modulefields.module_rows[][type].valid'] = "Eine oder mehrere Modulzeilen haben einen ungültigen Typ.";
$lang['FormRules.modulefields.service_fields[][name_key].valid'] = "Ob ein Servicefeld als Namensschlüssel gesetzt werden soll, muss auf true oder false gesetzt werden.";
$lang['FormRules.modulefeatures.cron_tasks[][label].empty'] = "Bitte geben Sie für jede Cron-Aufgabe eine Beschreibung ein.";
$lang['FormRules.pluginintegrations.actions[][action].format'] = "Bitte geben Sie für jede Aktion eine Aktion in Kleinbuchstaben an.";
$lang['FormRules.pluginintegrations.cards[][label].empty'] = "Bitte geben Sie für jede Karte ein Label ein.";
$lang['FormRules.nonmerchantbasic.currencies.format'] = "Bitte geben Sie die Währungen im Drei-Zeichen-Format und durch Komma getrennt ein (z.B. USD,EUR,JPY).";
$lang['FormRules.nonmerchantfields.fields[][label].empty'] = "Bitte geben Sie für jedes Feld eine Bezeichnung (Label) ein.";
?>