<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SystemOverviewSettings.!error.staff_id.exists'] = "Ungültige Personalnummer";
$lang['SystemOverviewSettings.!error.company_id.exists'] = "Ungültige Firmen-ID";
$lang['SystemOverviewSettings.!error.settings[][key].empty'] = "Kein Einstellschlüssel darf leer sein.";
$lang['SystemOverviewSettings.!error.settings[][value].length'] = "

Jede einzelne Einstellwertlänge darf 255 Zeichen nicht überschreiten.
";
?>