<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CustomReport.name'] = "

Benutzerdefinierter Bericht
";
$lang['CustomReports.options.field_report'] = "Bericht";
$lang['CustomReports.options.field_report_select'] = "-- Bitte auswählen --";
$lang['CustomReport.!error.field'] = "%1\$s ist nicht gültig."; // %1$s is the field label
?>