<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Razorpay.webhook_note'] = "Bevor Sie mit der Nutzung dieses Portals (Gateways) beginnen, müssen Sie die folgende URL als Webhook in Ihrem Razorpay-Konto konfigurieren.";
?>