<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CoinPayments.name'] = "CoinPayments.net";
$lang['CoinPayments.merchant_id'] = "CoinPayments-Händler-ID";
$lang['CoinPayments.ipn_secret'] = "IPN Secret";
$lang['CoinPayments.buildprocess.submit'] = "Zahlen Sie mit CoinPayments";
?>