<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Checkout.index.header_checkout'] = "Fast dort!";
$lang['Checkout.index.checkout_note'] = "

Bitte führen Sie die Zahlung durch, um Ihre Bestellung abzuschließen.
";
$lang['Checkout.index.field_useaccount'] = "

Zahlungskonto verwenden
";
$lang['Checkout.index.field_newdetails'] = "Neue Zahlungsdetails";
$lang['Checkout.index.heading_other_payment_options'] = "Andere Zahlungsmöglichkeiten";
$lang['Checkout.index.heading_payment_options'] = "Zahlungsmöglichkeiten";
$lang['Checkout.index.pay_btn'] = "Bezahlung & Bestellung abschließen";
$lang['Checkout.index.no_options'] = "Es sind keine Zahlungsoptionen verfügbar.";
$lang['Checkout.contact_info.heading_contact'] = "Kontakt Informationen";
$lang['Checkout.contact_info.field_contact_id'] = "

Kontaktinformationen kopieren aus
";
$lang['Checkout.contact_info.text_select_contact'] = "

Sie können einen vorhandenen Kontakt auswählen, um dieses Formular vorab auszufüllen.
";
$lang['Checkout.cc_info.heading_cc'] = "Kreditkarteninformation";
$lang['Checkout.ach_info.heading_ach'] = "Bankkonto Information";
$lang['Checkout.complete.order_more_btn'] = "Legen Sie eine andere Reihenfolge an";
$lang['Checkout.complete.invoice_paid'] = "BEZAHLT";
?>