<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Main.index.heading'] = "Paketauswahl";
$lang['Main.index.subheading'] = "

Bitte wählen Sie unten eine Paketgruppe aus, um fortzufahren.
";
$lang['Main.index.group_heading'] = "Wählen Sie unten ein Paket aus.";
$lang['Main.index.field_pricing_id'] = "Wählen Sie Ihren Abrechnungszeitraum.";
$lang['Main.index.button_order'] = "

Jetzt bestellen
";
$lang['Main.index.sold_out'] = "Ausverkauft";
$lang['Main.index.field_currency'] = "

Währung:
";
$lang['Main.packages.subheading'] = "

Wählen Sie ein Paket aus und konfigurieren Sie es unten.
";
$lang['Main.packages.select_note'] = "Ziehen Sie, um ein anderes Paket auszuwählen.";
$lang['Main.packages.price_start'] = "Beginnt um";
$lang['Main.packages.box_select'] = "Auswahl";
$lang['Main.packages.box_selected'] = "Ausgewählt";
$lang['Main.packages.box_sold_out'] = "Ausverkauft";
?>