<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ReassignPricingServices.!error.pricing_id.exists'] = "Ungültige Preiskennung";
$lang['ReassignPricingServices.!error.pricing_id.company'] = "Die Preis-ID gehört nicht zum selben Unternehmen wie der Service.";
$lang['ReassignPricingServices.!error.module_row_id.exists'] = "Ungültige Modulzeilen-ID aus der angegebenen Preis-ID";
$lang['ReassignPricingServices.!error.module_row_id.company'] = "Die Modulzeilennummer gehört nicht zu derselben Firma wie der Dienst.";
$lang['ReassignPricingServices.!error.service_id.exists'] = "Ungültige Service-ID.";
$lang['ReassignPricingServices.!error.package_group_id.exists'] = "Ungültige Paketgruppen-ID";
$lang['ReassignPricingServices.!error.package_group_id.company'] = "Die Paketgruppen-ID gehört nicht zu derselben Firma wie der Dienst.";
?>