<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Alipay.name'] = "Alipay";
$lang['Alipay.merchant_email'] = "Händler-E-Mail";
$lang['Alipay.merchant_uid'] = "Händler-UID/PID";
$lang['Alipay.signature_key'] = "

Signaturschlüssel
";
$lang['Alipay.dev_mode'] = "Entwicklermodus";
$lang['Alipay.dev_mode_note'] = "

Durch Aktivieren dieser Option werden Transaktionen in der Alipay Sandbox-Umgebung gebucht. Aktivieren Sie diese Option nur, wenn Sie mit einem Alipay-Sandbox-Konto testen.
";
$lang['Alipay.buildprocess.submit'] = "Bezahlen mit Alipay";
$lang['Alipay.!error.merchant_email.valid'] = "

Sie müssen eine gültige Email-Adresse angeben.
";
$lang['Alipay.!error.merchant_uid.valid'] = "

Sie müssen eine gültige Händler-UID/PID eingeben.
";
$lang['Alipay.!error.signature_key.valid'] = "

Sie müssen einen gültigen Signaturschlüssel eingeben.
";
?>