<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DomainsPlugin.getCronTasks.domain_synchronization_description'] = "Synchronisieren Sie die Domain-Dienste mit dem Ablaufdatum ihres Registrar-Moduls";
$lang['DomainsPlugin.getCronTasks.domain_renewal_reminders_description'] = "Senden Sie E-Mail-Erinnerungen für Domains, deren Verlängerungsdatum näher rückt";
$lang['DomainsPlugin.nav_secondary_staff.domain_options'] = "Domain Optionen";
$lang['DomainsPlugin.card_client.getDomainCount'] = "Domains";
$lang['DomainsPlugin.email_forwarding.description'] = "E-Mail-Weiterleitung";
$lang['DomainsPlugin.dns_management.name'] = "DNS-Verwaltung";
$lang['DomainsPlugin.nav_client.services'] = "Dienstleistungen";
$lang['DomainsPlugin.upgrade.domains_id_protection_option_group'] = "Alle Domain-Namen müssen gemäß den ICANN-Regeln über gültige Kontaktinformationen verfügen. Mit dieser Option werden diese Angaben vor dem öffentlichen Whois verborgen, so dass Ihre Informationen privat bleiben.";
?>