<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DomainsTlds.!error.package_group_id.exists'] = "Ungültige Paketgruppen-ID.";
$lang['DomainsTlds.!error.package_pricing.count'] = "Die Preise können nicht deaktiviert werden, die TLD muss mindestens eine Preisangabe haben.";
$lang['DomainsTlds.!error.tld.supported'] = "Die angegebene TLD wird von dem ausgewählten Registrar-Modul nicht unterstützt.";
?>