<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminPaymentMethods.index.page_title'] = "Zahlungsmethoden für Partner";
$lang['AdminPaymentMethods.index.boxtitle_payment_methods'] = "Affiliate Zahlungs Methode
";
$lang['AdminPaymentMethods.index.heading_options'] = "Optionen";
?>