<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSettings.settings.field_order_frequency'] = "Bestellreienfolge";
$lang['AdminSettings.settings.tooltip_order_frequency'] = "Entweder um Empfehlungen nur für die erste Bestellung zu bezahlen, die ein Kunde über einen Empfehlungs-Link tätigt oder beliebig, um Empfehlungen für jede Bestellung zu bezahlen, die ein Kunde über einen Empfehlungs-Link tätigt.";
$lang['AdminSettings.settings.tooltip_maturity_days'] = "Die Anzahl der Tage, die eine Überweisung fällig und für eine Auszahlung verfügbar wird.";
$lang['AdminSettings.settings.zero_amount'] = "Die Auszahlungshöhe ist aktuell bei null, bedeuted das Partner keine Auszahlung erhalten.";
?>