<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminPayouts.!success.payout_updated'] = "Die Auszahlung wurde erfolgreich aktualisiert.";
$lang['AdminPayouts.index.category_declined'] = "Abgelehnt";
$lang['AdminPayouts.index.heading_options'] = "Optionen";
$lang['AdminPayouts.index.option_edit'] = "Bearbeiten";
$lang['AdminPayouts.index.option_decline'] = "ablehnen";
$lang['AdminPayouts.index.confirm_approve'] = "Sind Sie sicher, dass Sie diese Auszahlung genehmigen wollen?";
$lang['AdminPayouts.index.no_results'] = "Zurzeit liegen keine Auszahlungsanträge vor.";
$lang['AdminPayouts.edit.field_payment_method_id'] = "Zahlungsmethode";
$lang['AdminPayouts.edit.modify_payout'] = "Auszahlung ändern";
?>