<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyEmails.templates.Order.received_name'] = "Bestellung erhalten";
$lang['AdminCompanyEmails.templates.Order.received_desc'] = "Mitteilung gesendet, wenn eine Bestellung erhalten wird.";
$lang['AdminCompanyEmails.templates.Order.received_mobile_name'] = "Bestellung eingegangen (Mobil)";
$lang['AdminCompanyEmails.templates.Order.received_mobile_desc'] = "Benachrichtigung gesendet, wenn eine Bestellung für mobile Geräte empfangen wird.";
$lang['AdminCompanyEmails.templates.Order.affiliate_payout_request_received_desc'] = "Mitteilung, die an einen Kunden gesendet wird, wenn sein Auszahlungsantrag eingereicht wird.";
$lang['AdminCompanyEmails.templates.Order.abandoned_cart_first_desc'] = "Erste Mitteilung an einen Kunden, nachdem er einen unbezahlten Auftrag abgebrochen hat.";
?>