<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Cart.!success.coupon_applied'] = "Der Gutschein wurde erfolgreich angewendet.";
$lang['Cart.!success.item_removed'] = "Der Artikel wurde aus Ihrem Warenkorb entfernt.";
$lang['Cart.!success.all_items_removed'] = "Alle Artikel wurden von Ihrem Warenkorb entfernt.";
$lang['Cart.!error.coupon_applied'] = "Der Gutschein konnte nicht angewendet werden.";
$lang['Cart.index.quantity'] = "%1\$s @"; // %1\$s is the quantity value being ordered
$lang['Cart.index.totals.discount'] = "

Rabatt:
";
$lang['Cart.index.totals.subtotal'] = "Zwischensumme:";
$lang['Cart.index.totals.tax'] = "%1\$s:"; // %1$s is the tax name
$lang['Cart.index.totals.total_recurring'] = "Gesamtbetrag bei Verlängerung:";
?>