<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Config.!error.invalid_pricing_id'] = "Das angegebene Paket wurde nicht gefunden.";
$lang['Config.!error.invalid_module'] = "Das Paket ist derzeit nicht verfügbar.";
$lang['Config.index.package_price'] = "%1\$s für %2\$s"; // %1$s is the term, %2$s is the price
$lang['Config.index.field_default_addon'] = "Keins";
$lang['Config.index.field_addon_label'] = "%1\$s (%2\$s @ %3\$s)"; // %1$s is the addon on name, %2$s is the term, %3$s is the price
$lang['Config.index.field_addon_label_recurring'] = "%1\$s (%2\$s @ %3\$s, verlängerung @ %4\$s)"; // %1$s is the addon on name, %2$s is the term, %3$s is the initial price, %4$s is the addon renewal price
?>