<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Main.index.package_price'] = "%1\$s @ %2\$s"; // %1$s is the term, %2$s is the price
$lang['Main.!error.package_limits'] = "Die Paketgrenzen wurden für alle Pakete in der ausgewählten Gruppe erreicht.";
?>