<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['OrderPlugin.name'] = "Bestellsystem";
$lang['OrderPlugin.admin_main.name'] = "Aufträge";
$lang['OrderPlugin.admin_forms.name'] = "Bestellformulare";
$lang['OrderPlugin.cron.accept_paid_orders_name'] = "Anstehende Aufträge akzeptieren";
$lang['OrderPlugin.cron.accept_paid_orders_desc'] = "

Akzeptiert automatisch bezahlte ausstehende Bestellungen, wenn dies im Bestellformular zulässig ist.
";
$lang['OrderPlugin.client.name'] = "Auftrag";
$lang['OrderPlugin.client_affiliates.name'] = "Partner";
$lang['OrderPlugin.permission.admin_affiliates'] = "Partner";
$lang['OrderPlugin.permission.admin_affiliates_update'] = "Partner aktualisieren";
$lang['OrderPlugin.permission.admin_affiliates_activate'] = "Affiliate aktivieren";
$lang['OrderPlugin.permission.admin_affiliates_settings'] = "Partnereinstellungen";
$lang['OrderPlugin.permission.admin_payouts_approve'] = "Auszahlung beantragen";
$lang['OrderPlugin.permission.admin_payouts_decline'] = "Auszahlung ablehnen";
$lang['OrderPlugin.permission.admin_payment_methods'] = "Zahlungsarten";
$lang['OrderPlugin.permission.admin_payment_methods_delete'] = "Zahlungsmethode löschen";
$lang['OrderPlugin.cron.process_abandoned_orders_desc'] = "Senden Sie Erinnerungs-E-Mails, führen Sie Stornierungen durch und deaktivieren Sie Kunden für abgebrochene Bestellungen";
?>