<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['OrderSettings.!error.embed_code.parse'] = "Fehler beim Parsen von Code-Analyse: %1\$s"; // %1$s is the parse error
$lang['OrderSettings.getantifraud.fraudlabspro'] = "FraudLabs Pro";
?>