<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['OrderAffiliatePayouts.!error.payout_id.exists'] = "Ungültige Auszahlungs-ID.";
$lang['OrderAffiliatePayouts.!error.affiliate_id.exists'] = "Falsche Partner ID.";
$lang['OrderAffiliatePayouts.!error.paid_amount.format'] = "Der gezahlte Betrag muss eine Zahl sein.";
?>