<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Summary.index.totals.discount'] = "

Rabatt:
";
$lang['Summary.index.totals.subtotal'] = "Zwischensumme:";
$lang['Summary.index.price'] = "je %1\$s"; // %1$s is the price per term
$lang['Summary.index.totals.tax'] = "%1\$s:"; // %1$s is the tax name
$lang['Summary.index.totals.total_recurring'] = "Gesamtbetrag bei Verlängerung:";
?>