<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Offline.name'] = "Offline-Zahlung";
$lang['Offline.instructions'] = "Anleitung";
$lang['Offline.!error.instructions.valid'] = "Sie müssen einige Anweisungen eingeben.";
$lang['Offline.description'] = "Ermöglicht die Anzeige spezieller Anweisungen für die Offline-Zahlungsabwicklung";
?>