<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Orders.index.heading_paid'] = "Bezahlt";
$lang['Orders.index.heading_date_ordered'] = "Datum der Bestellung";
$lang['Orders.index.option_view'] = "Ansicht";
$lang['Orders.index.option_cancel'] = "Abbrechen";
$lang['Orders.view.heading_services'] = "Dienste";
$lang['Orders.view.heading_package'] = "Paket";
$lang['Orders.view.heading_term'] = "Begriff";
$lang['Orders.view.heading_type'] = "Typ";
$lang['Orders.view.field_back_order_history'] = "Zurück zur Bestellhistorie";
$lang['Orders.view.no_invoices'] = "Zu dieser Bestellung gibt es keine Rechnungen.";
?>