<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['OrderAffiliateReferrals.!error.affiliate_id.exists'] = "Ungültige Affiliate-ID.";
$lang['OrderAffiliateReferrals.!error.order_id.exists'] = "Ungültige Bestell-ID.";
$lang['OrderAffiliateReferrals.!error.name.length'] = "\"Referral name\" darf 255 Zeichen nicht überschreiten.";
$lang['OrderAffiliateReferrals.!error.currency.length'] = "Der Währungs Code muss 3 Stellen beinhalten.";
$lang['OrderAffiliateReferrals.!error.date_added.format'] = "Das hinzugefügte Datum hat ein ungültiges Datumsformat.";
$lang['OrderAffiliateReferrals.getStatuses.canceled'] = "Abgebrochen";
?>