<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['OrderOrders.getstatuses.accepted'] = "Akzeptiert";
$lang['OrderOrders.getstatuses.fraud'] = "Betrug";
$lang['OrderOrders.getstatuses.canceled'] = "Stoniert";
$lang['OrderOrders.getstatuses.pending'] = "Im Rückblick";
?>