<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Payouts.!error.insufficient_funds_payout_request'] = "Es existiert nicht genug auf Ihrem Partner Konto. Die Auszahlung konnte nicht durchgeführt werden.";
$lang['Payouts.index.heading_requested_amount'] = "Angeforderter Betrag";
$lang['Payouts.index.heading_payment_method'] = "Zahlungsmethode";
$lang['Payouts.add.boxtitle_request_payout'] = "Auszahlung anfordern";
$lang['Payouts.add.title_payout_request'] = "Auszahlungsanfrage";
?>