<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Signup.!error.captcha.invalid'] = "Das eingegebene Captcha war ungültig. Bitte versuche es erneut.";
$lang['Signup.index.field_taxid'] = "Umsatzsteuernummer";
$lang['Signup.index.field_firstname'] = "Vorname";
$lang['Signup.index.field_lastname'] = "Familienname, Nachname";
$lang['Signup.index.field_company'] = "Firma / Organisation ";
$lang['Signup.index.field_address1'] = "Adresse 1";
$lang['Signup.index.field_address2'] = "Adresszusatz";
$lang['Signup.index.field_city'] = "Stadt";
$lang['Signup.index.field_state'] = "Land";
$lang['Signup.index.field_zip'] = "Postleitzahl";
$lang['Signup.index.field_country'] = "Land";
$lang['Signup.index.field_phone'] = "Telefon";
$lang['Signup.index.field_fax'] = "Fax";
$lang['Signup.index.field_email'] = "

Email
";
$lang['Signup.index.field_username_type_email'] = "E-Mail als Benutzernamen verwenden";
$lang['Signup.index.field_username_type_username'] = "Geben Sie einen Benutzernamen an";
$lang['Signup.index.field_action_continue'] = "Fortfahren als %1\$s %2\$s"; // %1$s is the first name of the client, %2$s is the last name of the client
$lang['Signup.index.field_action_login'] = "Einloggen";
$lang['Signup.index.field_action_signup'] = "Ein Konto erstellen";
$lang['Signup.index.field_username'] = "Benutzername";
$lang['Signup.index.field_password'] = "Passwort";
$lang['Signup.index.field_newpassword'] = "Passwort";
$lang['Signup.index.field_confirmpassword'] = "

Passwort bestätigen
";
$lang['Signup.index.login_btn'] = "Login";
$lang['Signup.index.continue_btn'] = "Weiter zur Kasse";
$lang['Signup.index.signup_btn'] = "

Benutzerkonto anlegen
";
$lang['Signup.!error.not_client_owner'] = "Sie müssen als Kunde angemeldet sein, um fortzufahren.";
$lang['Signup.index.field_title'] = "Titel";
$lang['Signup.index.field_receive_email_marketing'] = "Ich möchte E-Mails über neue Produkte, Dienstleistungen und Angebote erhalten.";
?>