<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Upload.!error.max_file_size'] = "Die Datei überschreitet die maximal zulässige Dateigröße.";
$lang['Upload.!error.mime_type'] = "

Der Dateityp %1\$s ist nicht zulässig.
"; // %1$s is the MIME type that is not permitted
$lang['Upload.!error.file_exists'] = "Die Datei existiert bereits.";
$lang['Upload.!error.write_failed'] = "Die Datei konnte nicht geschrieben werden.";
$lang['Upload.!error.path_created'] = "

Der Upload-Pfad konnte nicht erstellt werden.
";
?>