<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['InvoiceCreation.name'] = "Rechnungserstellung";
$lang['InvoiceCreation.options.field_start_date'] = "Anfangsdatum";
$lang['InvoiceCreation.options.field_end_date'] = "Endtermin";
$lang['InvoiceCreation.options.field_status'] = "Status";
$lang['InvoiceCreation.option.any'] = "Jeder";
$lang['InvoiceCreation.heading.id_code'] = "

Rechnung #
";
$lang['InvoiceCreation.heading.client_id_code'] = "Kunde";
$lang['InvoiceCreation.heading.subtotal'] = "Zwischensumme";
$lang['InvoiceCreation.heading.total'] = "Gesamt";
$lang['InvoiceCreation.heading.paid'] = "Bezahlt";
$lang['InvoiceCreation.heading.currency'] = "Währung";
$lang['InvoiceCreation.heading.status'] = "Status";
$lang['InvoiceCreation.heading.date_billed'] = "Datum in Rechnung gestellt";
$lang['InvoiceCreation.heading.date_due'] = "Fälligkeitsdatum";
$lang['InvoiceCreation.heading.date_closed'] = "Abschlussdatum";
?>