<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Checkout2.name'] = "2Checkout";
$lang['Checkout2.secret_word'] = "Geheimwort";
$lang['Checkout2.!error.buy_link_secret_word.empty'] = "Bitte geben Sie Ihr Buy Link Geheimwort ein.";
$lang['Checkout2.!error.test_mode.valid'] = "Der Testmodus muss entweder auf \"true\" oder \"false\" gesetzt werden.";
$lang['Checkout2.!error.key.valid'] = "Der Schlüssel, der zur Verifizierung dieses Verkaufs von 2Checkout verwendet wurde, ist ungültig.";
?>