<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['FraudLabsPro.!error.reject.reject_score'] = "Ihre Bestellung kann derzeit nicht bearbeitet werden.";
$lang['FraudLabsPro.!error.review.review_score'] = "Ihre Bestellung muss manuell überprüft werden.";
$lang['FraudLabsPro.!error.reject.fraudlabspro'] = "Ihre Bestellung wurde von FraudLabs Pro als Betrug markiert.";
$lang['FraudLabsPro.!error.review.fraudlabspro'] = "Ihre Bestellung wurde von FraudLabs Pro als potenziell betrügerisch gekennzeichnet. Es wird manuell überprüft.";
$lang['FraudLabsPro.settings.field_api_key'] = "API-Schlüssel";
$lang['FraudLabsPro.settings.label_description'] = "Holen Sie sich kostenlos FraudLabs Pro Micro Plan (500 Abfragen / Monat) von http://www.fraudlabspro.com/plan";
$lang['FraudLabsPro.settings.field_reject_score'] = "Mindestpunktzahl zum Ablehnen";
$lang['FraudLabsPro.settings.field_review_score'] = "Mindestbewertung zum Überprüfen";
$lang['FraudLabsPro.settings.field_follow_flp_result'] = "Automatisches Ablehnen / Überprüfen auf Empfehlung von FraudLabs Pro";
$lang['FraudLabsPro.settings.option_yes'] = "Ja";
$lang['FraudLabsPro.settings.option_no'] = "Nein";
?>