<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Whmsonic.name'] = "WHMSonic";
$lang['Whmsonic.module_row'] = "Server";
$lang['Whmsonic.module_row_plural'] = "Server";
$lang['Whmsonic.module_group'] = "Servergruppe";
$lang['Whmsonic.tab_stats'] = "Service Info";
$lang['Whmsonic.tab_client_actions'] = "Aktionen";
$lang['Whmsonic.submit'] = "einreichen";
$lang['Whmsonic.tab_stats.info_heading.field'] = "Feld";
$lang['Whmsonic.tab_stats.info_heading.value'] = "Wert";
$lang['Whmsonic.tab_stats.info.client_type'] = "Kundentyp";
$lang['Whmsonic.tab_stats.info.bitrate'] = "Bitrate-Limit";
$lang['Whmsonic.tab_stats.info.bandwidth'] = "Bandbreitenlimit (in MB)";
$lang['Whmsonic.tab_stats.info.hspace'] = "Hosting-Speicherplatz (in MB)";
$lang['Whmsonic.tab_stats.info.listeners'] = "Hörer begrenzen";
$lang['Whmsonic.tab_stats.info.autodj'] = "AutoDJ-Zugriff";
$lang['Whmsonic.tab_stats.info.username'] = "Nutzername";
$lang['Whmsonic.tab_stats.info.password'] = "Passwort";
$lang['Whmsonic.tab_stats.info.whmsonic_ftp'] = "FTP-Zugang";
$lang['Whmsonic.tab_stats.info.whmsonic_radio_ip'] = "Radio IP";
$lang['Whmsonic.tab_stats.info.whmsonic_radio_password'] = "Funkpasswort";
$lang['Whmsonic.tab_client_actions.change_password'] = "Passwörter ändern";
$lang['Whmsonic.tab_client_actions.password'] = "cPanel Passwort";
$lang['Whmsonic.tab_client_actions.radio_password'] = "Funkpasswort";
$lang['Whmsonic.add_module_row'] = "Server hinzufügen";
$lang['Whmsonic.add_module_group'] = "Servergruppe hinzufügen";
$lang['Whmsonic.manage.module_rows_title'] = "Server";
$lang['Whmsonic.manage.module_groups_title'] = "Servergruppen";
$lang['Whmsonic.manage.module_rows_heading.name'] = "Server-Label";
$lang['Whmsonic.manage.module_rows_heading.ip_address'] = "IP Adresse";
$lang['Whmsonic.manage.module_rows_heading.options'] = "Optionen";
$lang['Whmsonic.manage.module_groups_heading.name'] = "Gruppenname";
$lang['Whmsonic.manage.module_groups_heading.servers'] = "Serveranzahl";
$lang['Whmsonic.manage.module_groups_heading.options'] = "Optionen";
$lang['Whmsonic.manage.module_rows.edit'] = "Bearbeiten";
$lang['Whmsonic.manage.module_groups.edit'] = "Bearbeiten";
$lang['Whmsonic.manage.module_rows.delete'] = "Löschen";
$lang['Whmsonic.manage.module_groups.delete'] = "Löschen";
$lang['Whmsonic.manage.module_rows.confirm_delete'] = "Möchten Sie diesen Server wirklich löschen?";
$lang['Whmsonic.manage.module_groups.confirm_delete'] = "Möchten Sie diese Servergruppe wirklich löschen?";
$lang['Whmsonic.manage.module_rows_no_results'] = "

Es gibt keine Server.
";
$lang['Whmsonic.manage.module_groups_no_results'] = "

Es gibt keine Servergruppen.
";
$lang['Whmsonic.order_options.first'] = "Erster nicht voller Server";
$lang['Whmsonic.add_row.box_title'] = "WHMSonic Server hinzufügen";
$lang['Whmsonic.add_row.basic_title'] = "Basis-Einstellungen";
$lang['Whmsonic.add_row.add_btn'] = "Server hinzufügen";
$lang['Whmsonic.edit_row.box_title'] = "
WHMSonic Server bearbeiten
";
$lang['Whmsonic.edit_row.basic_title'] = "Grundeinstellungen";
$lang['Whmsonic.edit_row.add_btn'] = "Server bearbeiten";
$lang['Whmsonic.row_meta.server_name'] = "Serverkennzeichnung";
$lang['Whmsonic.row_meta.ip_address'] = "IP Adresse";
$lang['Whmsonic.row_meta.password'] = "Passwort";
$lang['Whmsonic.row_meta.use_ssl'] = "Verwenden Sie SSL, wenn Sie eine Verbindung zur API herstellen (empfohlen)";
$lang['Whmsonic.package_fields.client_type'] = "Kundentyp";
$lang['Whmsonic.package_fields.client_type.external'] = "Extern";
$lang['Whmsonic.package_fields.client_type.internal'] = "Intern";
$lang['Whmsonic.package_fields.bitrate'] = "Bitratenlimit";
$lang['Whmsonic.package_fields.hspace'] = "Hosting Space (in MB)";
$lang['Whmsonic.package_fields.bandwidth'] = "Bandbreitenlimit (in MB)";
$lang['Whmsonic.package_fields.listeners'] = "Hörer begrenzen";
$lang['Whmsonic.package_fields.autodj'] = "AutoDJ-Zugriff";
$lang['Whmsonic.package_fields.autodj.yes'] = "Ja";
$lang['Whmsonic.package_fields.autodj.no'] = "Nein";
$lang['Whmsonic.service_field.cpanel_username'] = "cPanel Benutzername";
$lang['Whmsonic.service_field.username'] = "Radio Benutzername";
$lang['Whmsonic.service_field.radio_password'] = "Funkpasswort";
$lang['Whmsonic.service_field.password'] = "cPanel Passwort";
$lang['Whmsonic.service_field.username.tooltip'] = "Der Benutzername wird nur lokal in Blesta aktualisiert";
$lang['Whmsonic.service_field.password.tooltip'] = "Das Passwort wird nur lokal in Blesta aktualisiert";
$lang['Whmsonic.service_info.ip_address'] = "IP Adresse";
$lang['Whmsonic.service_info.username'] = "Benutzername";
$lang['Whmsonic.service_info.password'] = "Passwort";
$lang['Whmsonic.service_info.options'] = "Optionen";
$lang['Whmsonic.service_info.option_login'] = "Einloggen";
$lang['Whmsonic.!error.server_name_valid'] = "Sie müssen eine Serverbezeichnung eingeben.";
$lang['Whmsonic.!error.ip_address_valid'] = "

Die IP-Adresse scheint ungültig zu sein.
";
$lang['Whmsonic.!error.password_valid'] = "Die API-Anmeldeinformationen scheinen ungültig zu sein.";
$lang['Whmsonic.!error.api.internal'] = "Ein interner Fehler ist aufgetreten oder der Server hat auf die Anfrage nicht geantwortet.";
$lang['Whmsonic.!error.module_row.missing'] = "Ein interner Fehler ist aufgetreten. Die Modulzeile ist nicht verfügbar.";
$lang['Whmsonic.!error.meta[client_type].valid'] = "

Bitte wählen Sie einen gültigen Kundentyp.
";
$lang['Whmsonic.!error.meta[bitrate].valid'] = "Bitte wählen Sie ein gültiges BitRate-Limit.";
$lang['Whmsonic.!error.meta[hspace].empty'] = "Bitte geben Sie den Hosting Space (in MB) ein, z. B. 1000.";
$lang['Whmsonic.!error.meta[bandwidth].empty'] = "Bitte geben Sie das Bandbreitenlimit (in MB) ein, z. B .: 1000.";
$lang['Whmsonic.!error.meta[listeners].empty'] = "Bitte geben Sie das Listener Limit ein.";
$lang['Whmsonic.!error.meta[autodj].valid'] = "Wählen Sie eine gültige AutoDJ-Zugriffsoption aus.";
$lang['Whmsonic.!error.user_name.empty'] = "Der Benutzername darf nicht leer sein.";
$lang['Whmsonic.!error.user_password.valid'] = "Das Passwort muss mindestens 8 Zeichen lang sein.";
?>