<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Bitpay.name'] = "Bitpay";
$lang['Bitpay.transaction_speed'] = "Transaktionsgeschwindigkeit";
$lang['Bitpay.transaction.speed.high'] = "Hoch";
$lang['Bitpay.transaction.speed.medium'] = "Mittel";
$lang['Bitpay.transaction.speed.low'] = "Niedrig";
$lang['Bitpay.transaction_speed_note'] = "Die Transaktionsgeschwindigkeit bestimmt, wie schnell eine Rechnung (in Bitpay) als \"bestätigt\" betrachtet werden kann.";
$lang['Bitpay.buildprocess.submit'] = "Bezahlen mit Bitcoin";
$lang['Bitpay.!error.transaction_speed.valid'] = "Bitte wählen Sie eine gültige Transaktionsgeschwindigkeit.";
$lang['Bitpay.!error.failed.response'] = "Die Transaktion konnte nicht verarbeitet werden.";
$lang['Bitpay.!error.payment.invalid'] = "Die Transaktion ist ungültig und konnte nicht verarbeitet werden.";
$lang['Bitpay.!error.payment.expired'] = "Die Transaktion ist abgelaufen und konnte nicht verarbeitet werden.";
?>