<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Braintree.name'] = "Braintree";
$lang['Braintree.merchant_id'] = "Händler-ID";
$lang['Braintree.public_key'] = "Public-Key";
$lang['Braintree.private_key'] = "Privater Schlüssel";
$lang['Braintree.live_mode'] = "Livemodus";
$lang['Braintree.environment'] = "Umgebung";
$lang['Braintree.environment.sandbox'] = "Sandkasten";
$lang['Braintree.environment.production'] = "Produktion";
$lang['Braintree.!error.live_mode.valid'] = "Der Live-Modus muss auf \"true\" gesetzt sein, wenn er angegeben ist.";
$lang['Braintree.!error.merchant_id'] = "Bitte geben Sie Ihre Händler-ID ein.";
$lang['Braintree.!error.public_key'] = "

Bitte geben Sie Ihren öffentlichen Schlüssel ein.
";
$lang['Braintree.!error.private_key'] = "Bitte geben Sie Ihren privaten Schlüssel ein.";
$lang['Braintree.!error.environment'] = "Bitte wählen Sie eine gültige Umgebung aus.";
?>