<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Square.name'] = "Square";
$lang['Square.application_id'] = "

Anwendungs-ID
";
$lang['Square.access_token'] = "Zugangstoken";
$lang['Square.location_id'] = "

Standort-ID
";
$lang['Square.buildprocess.submit'] = "Mit Square zahlen";
$lang['Square.!error.application_id.valid'] = "Sie müssen eine gültige Anwendungs-ID eingeben.";
$lang['Square.!error.access_token.valid'] = "Sie müssen ein gültiges Access Token eingeben.";
$lang['Square.!error.location_id.valid'] = "Sie müssen eine gültige Standort-ID eingeben.";
$lang['Square.description'] = "Square, Inc. ist ein Unternehmen für Finanzdienstleistungen, Händlerdienste und mobile Zahlungen mit Sitz in San Francisco, Kalifornien. Das Unternehmen hat eine starke Kundenbasis von Kleinunternehmern";
?>