<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PayJunction.name'] = "PayJunction";
$lang['PayJunction.api_key'] = "

API-Schlüssel
";
$lang['PayJunction.user_name'] = "Nutzername";
$lang['PayJunction.password'] = "Passwort";
$lang['PayJunction.test_mode'] = "Entwicklermodus";
$lang['PayJunction.api_key_note'] = "Geben Sie den API-Schlüssel von Ihrem PayJunction-Konto ein.";
$lang['PayJunction.user_name_note'] = "Geben Sie Ihren PayJunction Benutzernamen ein.";
$lang['PayJunction.password_note'] = "Geben Sie ihr PayJunction Passwort ein.";
$lang['PayJunction.test_mode_note'] = "Wenn Sie den Entwicklermodus aktivieren, werden Transaktionen an die Demoumgebung von PayJunction Labs gesendet. Sie müssen den Demo-Benutzernamen und das Passwort sowie Ihren Labs-API-Schlüssel verwenden, um den Entwicklermodus zu verwenden.";
$lang['PayJunction.!error.api_key.empty'] = "Bitte geben Sie einen gültigen API-Schlüssel ein.";
$lang['PayJunction.!error.user_name.empty'] = "Bitte geben Sie Ihren Nutzernamen ein.";
$lang['PayJunction.!error.password.empty'] = "Bitte geben Sie Ihr Kontopasswort ein.";
$lang['PayJunction.!error.test_mode.valid'] = "Der Entwicklermodus muss auf 'true' gesetzt sein, wenn er angegeben wird.";
?>