<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MaxmindV2.settings.field_key'] = "Lizenzschlüssel";
$lang['MaxmindV2.settings.field_country_mismatch'] = "Länderkonflikt";
$lang['MaxmindV2.settings.field_enable_js'] = "JavaScript-Tracking add-on aktivieren";
$lang['MaxmindV2.settings.option_allow'] = "Erlauben";
$lang['MaxmindV2.settings.option_enable'] = "Aktivieren";
?>