<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.!success.feed_added'] = "Der Feed wurde erfolgreich hinzugefügt.";
$lang['AdminMain.!success.feed_refreshed'] = "Diese Nachricht wurde erfolgreich erneuert.";
$lang['AdminMain.!success.feed_removed'] = "Der Feed wurde erfolgreich gelöscht.";
$lang['AdminMain.index.boxtitle_feed'] = "Feed Reader";
$lang['AdminMain.index.no_results'] = "Es gibt keine Feed-Ergebnisse.";
$lang['AdminMain.index.last_updated'] = "Der Feed wurde am %1\$s zuletzt aktualisiert."; // %1$s is a date/time stamp of the last time the feed was updated
$lang['AdminMain.add.boxtitle_feed'] = "Feed hinzufügen";
$lang['AdminMain.add.field_url'] = "URL";
$lang['AdminMain.add.submit_add'] = "Feed hinzufügen";
$lang['AdminMain.add.submit_cancel'] = "Abbrechen";
$lang['AdminMain.settings.no_feeds'] = "Es existieren keine Feeds.";
$lang['AdminMain.settings.add_feed'] = "Feed hinzufügen";
$lang['AdminMain.settings.submit_cancel'] = "Zurück zu den Feeds";
$lang['AdminMain.settings.heading_url'] = "URL";
$lang['AdminMain.settings.heading_lastupdated'] = "Zuletzt aktualisiert";
$lang['AdminMain.settings.heading_options'] = "Optionen";
$lang['AdminMain.settings.option_refresh'] = "Aktualisierung";
$lang['AdminMain.settings.option_remove'] = "Entfernen";
?>