<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['FeedReaderManagePlugin.!success.feed_added'] = "

Der Feed wurde erfolgreich hinzugefügt.
";
$lang['FeedReaderManagePlugin.!success.feed_refreshed'] = "Der Feed wurde erfolgreich aktualisiert.";
$lang['FeedReaderManagePlugin.!success.feed_removed'] = "Der Feed wurde erfolgreich entfernt.";
$lang['FeedReaderManagePlugin.index.boxtitle_feedreader'] = "Feed-Reader";
$lang['FeedReaderManagePlugin.index.add_feed'] = "Feed hinzufügen";
$lang['FeedReaderManagePlugin.index.heading_url'] = "URL";
$lang['FeedReaderManagePlugin.index.heading_lastupdated'] = "Letzte Aktualisierung";
$lang['FeedReaderManagePlugin.index.heading_options'] = "Optionen";
$lang['FeedReaderManagePlugin.index.option_refresh'] = "Neuladen";
$lang['FeedReaderManagePlugin.index.option_remove'] = "Löschen";
$lang['FeedReaderManagePlugin.index.no_feeds'] = "Es gibt keine Standard Feeds";
$lang['FeedReaderManagePlugin.add.boxtitle_feed'] = "Füge einen Feed hinzu";
$lang['FeedReaderPlugin.add.field_url'] = "URL";
$lang['FeedReaderPlugin.add.submit_add'] = "Feed hinzufügen ";
$lang['FeedReaderPlugin.add.submit_cancel'] = "Stornieren";
$lang['FeedReaderManagePlugin.index.page_title'] = "Feed Reader > Verwalten";
$lang['FeedReaderManagePlugin.add.page_title'] = "Feed Reader&gt; Feed hinzufügen";
$lang['FeedReaderManagePlugin.index.text_confirm_delete'] = "

Diesen Feed wirklich löschen?
";
?>