<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['FeedReaderPlugin.!error.libxml_required'] = "Die Erweiterung libxml ist für dieses Plugin erforderlich.";
$lang['FeedReaderPlugin.!error.dom_required'] = "Die DOM Erweiterung ist für dieses Plugin erforderlich.";
$lang['FeedReaderPlugin.name'] = "Feed-Reader";
?>