<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminPlugin.getactionlocations.widget_staff_billing'] = "Widget - Rechnungsübersicht (Mitarbeiter)";
$lang['AdminPlugin.getoptionalfunctions.tooltip_upgrade'] = "Führt die Migration der Daten von \$current_version (der aktuell installierten Version) auf die angegeben Datensatz durch. Setzt bei einem Fehlschlag Eingabefehler, so dass das Modul nicht aktualisiert werden kann.";
$lang['AdminPlugin.basic.heading_authors'] = "Autoren";
$lang['AdminPlugin.basic.logo'] = "Logo
";
$lang['AdminPlugin.basic.author_name'] = "Autor Name";
$lang['AdminPlugin.basic.author_url'] = "Autor-URL";
$lang['AdminPlugin.basic.author_row_add'] = "Autor hinzufügen";
$lang['AdminPlugin.basic.placeholder_author_name'] = "z.B. Blesta";
$lang['AdminPlugin.database.heading_database'] = "Datenbank Tabellen";
$lang['AdminPlugin.database.heading_more_info'] = "Mehr Infos";
$lang['AdminPlugin.database.tooltip_table_name'] = "Der Name der Datenbank Tabelle (z.B. extention_table_name)";
$lang['AdminPlugin.database.placeholder_table_name'] = "z. B. extention_table_name";
$lang['AdminPlugin.database.column_name'] = "Spalte Name";
$lang['AdminPlugin.database.tooltip_length'] = "Legt die maximale Anzahl von Zeichen in einem Feld fest. Wenn der Spaltentyp \"enum\" ist, geben Sie die Werte bitte in diesem Format ein: 'a','b','c'...";
$lang['AdminPlugin.database.tooltip_nullable'] = "Ob ein Nullwert für diese Spalte zulässig sein soll oder nicht.";
$lang['AdminPlugin.database.text_options'] = "Optionen";
$lang['AdminPlugin.integrations.name'] = "Name";
$lang['AdminPlugin.integrations.text_options'] = "Optionen";
$lang['AdminPlugin.integrations.placeholder_controller'] = "z. B. admin_main";
$lang['AdminPlugin.integrations.placeholder_event_callback'] = "z.B. myClientAddHandlerMethod";
$lang['AdminPlugin.integrations.features'] = "Weiter - Zusätzliche Funktionen";
$lang['AdminPlugin.features.tooltip_type'] = "Die Art der Zeitsteuerung, die für die Cron-Aufgabe verwendet werden soll (Zeit oder Intervall)";
$lang['AdminPlugin.features.tooltip_time'] = "Dieser Crontask sollte ausgeführt werden";
$lang['AdminPlugin.features.placeholder_tab_label'] = "z.B. Passwort ändern";
$lang['AdminPlugin.features.text_options'] = "Optionen";
$lang['AdminPlugin.features.text_remove'] = "Entfernen";
?>