<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ExtensionGeneratorPlugin.description'] = "Dies ist ein Plugin zur automatischen Erzeugung von Dateien für neue Blesta-Erweiterungen";
$lang['ExtensionGeneratorPlugin.nav_secondary_staff.admin_main'] = "Generator für Erweiterungen";
?>