<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Config.index.header_configuration'] = "Aufbau";
$lang['Config.index.header_configure_service'] = "%1\$s konfigurieren "; // %1$s is the service name to configure
$lang['Config.index.config_notes'] = "

Wählen Sie die gewünschten Optionen aus und fahren Sie mit dem Checkout fort.
";
$lang['Config.index.header_term'] = "Laufzeit und Preis";
$lang['Config.index.header_module'] = "Konfigurierbare Optionen";
$lang['Config.index.header_addons'] = "Verfügbare Addons";
$lang['Config.index.addons_notes'] = "Alle ausgewählten Addons werden im nächsten Schritt konfiguriert.";
$lang['Config.index.continue_btn'] = "Weiter";
?>