<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Opensrs.module_row'] = "Konto";
$lang['Opensrs.module_row_plural'] = "Konten";
$lang['Opensrs.manage.module_rows.confirm_delete'] = "Sind Sie sicher, dass Sie dieses Konto löschen möchten?";
$lang['Opensrs.add_row.basic_title'] = "Grundeinstellungen";
$lang['Opensrs.package_fields.type'] = "Typ";
$lang['Opensrs.tab_settings.field_registrar_lock_yes'] = "Stellen Sie die Registrar-Sperre ein. Empfohlen, um eine unbefugte Übertragung zu verhindern.";
$lang['Opensrs.tab_settings.field_whois_privacy'] = "WHOIS-Datenschutz";
$lang['Opensrs.whois.owner.first_name'] = "Vorname";
$lang['Opensrs.whois.owner.last_name'] = "Nachname";
$lang['Opensrs.whois.owner.address2'] = "Adresse 2";
$lang['Opensrs.whois.tech.last_name'] = "Nachname";
$lang['Opensrs.whois.tech.address1'] = "Adresse 1";
$lang['Opensrs.whois.admin.org_name'] = "Firma";
$lang['Opensrs.whois.admin.state'] = "Bundesland";
$lang['Opensrs.whois.billing.first_name'] = "Vorname";
$lang['Opensrs.whois.billing.country'] = "Land";
$lang['Opensrs.domain.category'] = "Registrierstelle Typ";
$lang['Opensrs.domain.app_purpose.p2'] = "Gemeinnützig";
$lang['Opensrs.domain.owner_confirm_address'] = "Besitzer E-Mail Adresse";
$lang['Opensrs.domain.legal_type.res'] = "Kanadische_r Einwohner_in";
$lang['Opensrs.domain.legal_type.edu'] = "Bildungswesen";
$lang['Opensrs.domain.registrant_type.stra'] = "UK-Einzelkaufmann";
$lang['Opensrs.domain.registrant_type.sch'] = "Britische Schule";
$lang['Opensrs.domain.legal_entity_type.government'] = "Staatliche Einrichtungen";
$lang['Opensrs.domain.legal_entity_type.society'] = "Trusts, Nachlässe, Vereinigungen oder Gesellschaften";
$lang['Opensrs.domain.reg_code'] = "Registrierungs-Code";
$lang['Opensrs.domain.entity_type.1'] = "Person";
$lang['Opensrs.domain.qli_accreditation_id'] = "Akkreditierungs-ID";
?>