<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Cyberpanel.name'] = "CyberPanel";
$lang['Cyberpanel.module_row'] = "Server";
$lang['Cyberpanel.module_row_plural'] = "Server";
$lang['Cyberpanel.module_group'] = "Servergruppe";
$lang['Cyberpanel.tab_client_actions'] = "Aktionen";
$lang['Cyberpanel.add_module_row'] = "

Server hinzufügen
";
$lang['Cyberpanel.add_module_group'] = "

Servergruppe hinzufügen
";
$lang['Cyberpanel.manage.module_rows_title'] = "Server";
$lang['Cyberpanel.manage.module_groups_title'] = "Servergruppen";
$lang['Cyberpanel.manage.module_rows_heading.name'] = "

Server-Kennzeichnung
";
$lang['Cyberpanel.manage.module_rows_heading.hostname'] = "Hostname";
$lang['Cyberpanel.manage.module_rows_heading.options'] = "Optionen";
$lang['Cyberpanel.manage.module_groups_heading.name'] = "Gruppenname";
$lang['Cyberpanel.manage.module_groups_heading.servers'] = "Serveranzahl";
$lang['Cyberpanel.manage.module_groups_heading.options'] = "Optionen";
$lang['Cyberpanel.manage.module_rows.edit'] = "Bearbeiten";
$lang['Cyberpanel.manage.module_groups.edit'] = "Bearbeiten";
$lang['Cyberpanel.manage.module_rows.delete'] = "Löschen";
$lang['Cyberpanel.manage.module_groups.delete'] = "Löschen";
$lang['Cyberpanel.manage.module_rows.confirm_delete'] = "Möchten Sie diesen Server wirklich löschen?";
$lang['Cyberpanel.manage.module_groups.confirm_delete'] = "Möchten Sie diese Servergruppe wirklich löschen?";
$lang['Cyberpanel.manage.module_rows_no_results'] = "Es gibt keine Server.";
$lang['Cyberpanel.manage.module_groups_no_results'] = "Es gibt keine Servergruppen.";
$lang['Cyberpanel.order_options.first'] = "

Erster nicht voller Server
";
$lang['Cyberpanel.order_options.roundrobin'] = "Gleichmäßig unter den Servern verteilen";
$lang['Cyberpanel.add_row.box_title'] = "CyberPanel-Server hinzufügen";
$lang['Cyberpanel.add_row.basic_title'] = "Grundeinstellungen";
$lang['Cyberpanel.add_row.name_servers_title'] = "Name Server";
$lang['Cyberpanel.add_row.notes_title'] = "Notizen";
$lang['Cyberpanel.add_row.name_server_btn'] = "Zusätzlichen Namenserver hinzufügen";
$lang['Cyberpanel.add_row.name_server_col'] = "Nameserver";
$lang['Cyberpanel.add_row.name_server_host_col'] = "Hostname";
$lang['Cyberpanel.add_row.name_server'] = "Namenserver %1\$s"; // %1$s is the name server number (e.g. 3)
$lang['Cyberpanel.add_row.remove_name_server'] = "Löschen";
$lang['Cyberpanel.add_row.add_btn'] = "Server hinzufügen";
$lang['Cyberpanel.edit_row.box_title'] = "CyberPanel-Server bearbeiten";
$lang['Cyberpanel.edit_row.basic_title'] = "Grundeinstellungen";
$lang['Cyberpanel.edit_row.name_servers_title'] = "Namenserver";
$lang['Cyberpanel.edit_row.notes_title'] = "Anmerkungen";
$lang['Cyberpanel.edit_row.name_server_btn'] = "Zusätzlichen Namenserver hinzufügen";
$lang['Cyberpanel.edit_row.name_server_col'] = "

Nameserver
";
$lang['Cyberpanel.edit_row.name_server_host_col'] = "Hostname";
$lang['Cyberpanel.edit_row.name_server'] = "Nameserver %1\$s"; // %1$s is the name server number (e.g. 3)
$lang['Cyberpanel.edit_row.remove_name_server'] = "Löschen";
$lang['Cyberpanel.edit_row.add_btn'] = "

Server bearbeiten
";
$lang['Cyberpanel.row_meta.server_name'] = "Serverkennzeichnung";
$lang['Cyberpanel.row_meta.host_name'] = "Hostname";
$lang['Cyberpanel.row_meta.admin_username'] = "Admin Benutzername";
$lang['Cyberpanel.row_meta.admin_password'] = "Administrator-Passwort";
$lang['Cyberpanel.row_meta.use_ssl'] = "Verwenden Sie SSL, wenn Sie eine Verbindung zur API herstellen (empfohlen)";
$lang['Cyberpanel.package_fields.package'] = "Paketnamen";
$lang['Cyberpanel.service_field.domain'] = "Domain";
$lang['Cyberpanel.service_field.username'] = "Benutzername";
$lang['Cyberpanel.service_field.password'] = "Passwort";
$lang['Cyberpanel.tab_client_actions.change_password'] = "Passwort ändern";
$lang['Cyberpanel.tab_client_actions.field_cyberpanel_password'] = "Passwort";
$lang['Cyberpanel.tab_client_actions.field_cyberpanel_confirm_password'] = "Bestätige das Passwort";
$lang['Cyberpanel.tab_client_actions.field_password_submit'] = "Passwort aktualisieren";
$lang['Cyberpanel.service_info.username'] = "Benutzername";
$lang['Cyberpanel.service_info.password'] = "Passwort";
$lang['Cyberpanel.service_info.server'] = "Server";
$lang['Cyberpanel.service_info.options'] = "Optionen";
$lang['Cyberpanel.service_info.option_login'] = "Einloggen";
$lang['Cyberpanel.service_field.tooltip.username'] = "

Sie können den Benutzernamen leer lassen, um automatisch einen zu erstellen.
";
$lang['Cyberpanel.service_field.tooltip.password'] = "Sie können das Passwort leer lassen, um automatisch ein Passwort zu generieren.";
$lang['Cyberpanel.!error.server_name_valid'] = "

Sie müssen eine Server-Bezeichnung eingeben.
";
$lang['Cyberpanel.!error.host_name_valid'] = "Der Hostname scheint ungültig zu sein.";
$lang['Cyberpanel.!error.remote_admin_username_valid'] = "Der Admin-Benutzername scheint ungültig zu sein.";
$lang['Cyberpanel.!error.remote_admin_password_valid'] = "

Das Admin-Passwort scheint ungültig zu sein.
";
$lang['Cyberpanel.!error.remote_admin_password_valid_connection'] = "

Es konnte keine Verbindung zum Server hergestellt werden. Bitte überprüfen Sie, ob der Hostname und das Admin-Passwort korrekt sind.
";
$lang['Cyberpanel.!error.name_servers_valid'] = "Einer oder mehrere der eingegebenen Nameserver sind ungültig.";
$lang['Cyberpanel.!error.name_servers_count'] = "Sie müssen mindestens 2 Nameserver definieren.";
$lang['Cyberpanel.!error.meta[package].empty'] = "

Ein CyberPanel-Paket ist erforderlich.
";
$lang['Cyberpanel.!error.api.internal'] = "Ein interner Fehler ist aufgetreten oder der Server hat auf die Anfrage nicht geantwortet.";
$lang['Cyberpanel.!error.module_row.missing'] = "Ein interner Fehler ist aufgetreten. Die Modulzeile ist nicht verfügbar.";
$lang['Cyberpanel.!error.cyberpanel_domain.format'] = "

Bitte geben Sie einen gültigen Domainnamen ein, z.B. domain.com.
";
$lang['Cyberpanel.!error.cyberpanel_domain.test'] = "Der Domänenname kann nicht mit \"test\" beginnen.";
$lang['Cyberpanel.!error.cyberpanel_username.format'] = "Der Benutzername darf nur Buchstaben und Zahlen enthalten und darf nicht mit einer Zahl beginnen.";
$lang['Cyberpanel.!error.cyberpanel_username.test'] = "Der Benutzername darf nicht mit \"test\" beginnen.";
$lang['Cyberpanel.!error.cyberpanel_username.length'] = "Der Benutzername muss zwischen 1 und 16 Zeichen lang sein.";
$lang['Cyberpanel.!error.cyberpanel_password.valid'] = "

Das Passwort muss mindestens 8 Zeichen lang sein.
";
$lang['Cyberpanel.!error.cyberpanel_password.matches'] = "Passwort und Passwort bestätigen stimmen nicht überein.";
?>