<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Stripe_gateway.!error.auth'] = "Das Gateway konnte nicht authentifiziert werden.";
$lang['Stripe_gateway.!error.api_key.empty'] = "Bitte geben Sie einen API-Key ein.";
$lang['Stripe_gateway.!error.json_required'] = "Die JSON-Erweiterung ist für dieses Gateway erforderlich.";
$lang['Stripe_gateway.name'] = "Streifen";
$lang['Stripe_gateway.api_key'] = "API Geheimschlüssel";
$lang['Stripe_gateway.tooltip_api'] = "Ihr API-Schlüssel ist entweder für Produktiv oder Test gültig. Bitte achten Sie darauf, den korrekten Schlüssel zu verwenden.";
$lang['Stripe_gateway.stored'] = "Karten-Informationen außerhalb der Seite speichern";
$lang['Stripe_gateway.tooltip_stored'] = "Aktivieren Sie dieses Kontrollkästchen, um Informationen zu Zahlungskonten mit Stripe und nicht mit Blesta zu speichern.";
?>