<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['OrderTypeDomain.name'] = "Domains und Sonstiges";
$lang['OrderTypeDomain.!error.domain.invalid'] = "Dieser Domainname wird nicht unterstützt.";
$lang['OrderTypeDomain.!error.domain.empty'] = "Bitte geben Sie einen Domainnamen ein.";
$lang['OrderTypeDomain.!error.template.valid'] = "Die ausgewählte Vorlage benötigt mindestens eine Paketgruppe.";
$lang['OrderTypeDomain.settings.domain_group_title'] = "Domänenpaketgruppe";
$lang['Main.steps.step_1_description'] = "Wählen Sie eine Domain";
?>