<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminTickets.!success.ticket_created'] = "Das Ticket # %1\$s wurde erfolgreich geöffnet."; // %1$s is the ticket number
$lang['AdminTickets.!success.ticket_updated'] = "Das Ticket %1\$s wurde erfolgreich aktualisiert."; // %1$s is the ticket number
$lang['AdminTickets.!notice.no_departments_staff'] = "Es wurden noch keine Mitarbeiter und/oder Abteilungen erstellt. Klicken Sie oben auf %1\$s, um eine Abteilung zu erstellen, oder auf %2\$s, um einen Mitarbeiter zuzuweisen."; // %1$s is the language definition for the Departments navigation item, %2$s is the language definition for the Staff navigation item
$lang['AdminTickets.index.page_title'] = "Support Manager > Tickets";
$lang['AdminTickets.add.page_title'] = "

Support Manager > Ticket öffnen
";
$lang['AdminTickets.reply.page_title'] = "Support > Ticket #%1\$s"; // %1$s is the ticket number
$lang['AdminTickets.search.page_title'] = "Suchergebnisse für \"%1\$s\""; // %1$s is the search keywords
$lang['AdminTickets.text.unassigned'] = "

Nicht zugeordnet
";
$lang['AdminTickets.index.category_open'] = "Warten auf Mitarbeiterantwort";
$lang['AdminTickets.index.category_awaiting_reply'] = "Warten auf Client-Antwort";
$lang['AdminTickets.index.category_in_progress'] = "In bearbeitung";
$lang['AdminTickets.index.category_closed'] = "Geschlossen";
$lang['AdminTickets.index.categorylink_createticket'] = "Ticket erstellen";
$lang['AdminTickets.index.boxtitle_tickets'] = "Tickets";
$lang['AdminTickets.index.heading_code'] = "

Ticketnummer
";
$lang['AdminTickets.index.heading_priority'] = "Priorität";
$lang['AdminTickets.index.heading_department_name'] = "Abteilung";
$lang['AdminTickets.index.heading_summary'] = "Zusammenfassung";
$lang['AdminTickets.index.heading_last_reply_date'] = "Letzte Antwort";
$lang['AdminTickets.index.no_results'] = "Derzeit gibt es keine Tickets mit diesem Status.";
$lang['AdminTickets.add.boxtitle_add'] = "Ticket erstellen";
$lang['AdminTickets.add.heading_search_client'] = "Kunden suchen
";
$lang['AdminTickets.add.text_no_clients'] = "Keine Kunden gefunden. Versuchen Sie es erneut.";
$lang['AdminTickets.add.heading_summary'] = "Zusammenfassung";
$lang['AdminTickets.add.heading_client'] = "Kunde";
$lang['AdminTickets.add.heading_department'] = "Abteilung";
$lang['AdminTickets.add.heading_staff_id'] = "Zugewiesen an";
$lang['AdminTickets.add.heading_priority'] = "Priorität";
$lang['AdminTickets.add.heading_status'] = "Status";
$lang['AdminTickets.add.field_attachments'] = "Anhänge";
$lang['AdminTickets.add.field_details'] = "Details";
$lang['AdminTickets.add.text_add_attachment'] = "Anhang hinzufügen";
$lang['AdminTickets.add.field_addsubmit'] = "Ticket eröffnen";
$lang['AdminTickets.add.text_add_response'] = "

Fügen Sie eine vordefinierte Antwort ein
";
$lang['AdminTickets.reply.boxtitle_reply'] = "Ticket #%1\$s"; // %1$s is the ticket number
$lang['AdminTickets.reply.heading_summary'] = "Zusammenfassung";
$lang['AdminTickets.reply.heading_client'] = "Klient";
$lang['AdminTickets.reply.heading_department'] = "Abteilung";
$lang['AdminTickets.reply.heading_staff_id'] = "Zuweisen an";
$lang['AdminTickets.reply.heading_priority'] = "Priorität";
$lang['AdminTickets.reply.heading_status'] = "Status";
$lang['AdminTickets.reply.heading_date_added'] = "Eröffnet am";
$lang['AdminTickets.reply.text_add_response'] = "Fügen Sie eine vordefinierte Antwort ein";
$lang['AdminTickets.reply.heading_reply'] = "Antwort hinzufügen";
$lang['AdminTickets.reply.field_reply'] = "Antworten";
$lang['AdminTickets.reply.field_note'] = "Notiz";
$lang['AdminTickets.reply.field_attachments'] = "Anlagen";
$lang['AdminTickets.reply.text_add_attachment'] = "Anhang hinzufügen";
$lang['AdminTickets.reply.field_replysubmit'] = "

Ticket aktualisieren
";
$lang['AdminTickets.reply.reply_date'] = "

Auf %1\$s %2\$s %3\$s antwortete
"; // %1$s is the ticket reply date, %2$s is the first name of the reply author, %3$s is the last name of the reply author
$lang['AdminTickets.reply.log_date'] = "%1\$s von %2\$s %3\$s"; // %1$s is the ticket reply date, %2$s is the first name of the reply author, %3$s is the last name of the reply author
$lang['AdminTickets.reply.system'] = "System";
$lang['AdminTickets.reply.staff_title'] = "Support-Mitarbeiter";
$lang['AdminTickets.client.category_open'] = "Warten auf Mitarbeiterantwort";
$lang['AdminTickets.client.category_awaiting_reply'] = "Warten auf Client-Antwort";
$lang['AdminTickets.client.category_in_progress'] = "

In Bearbeitung
";
$lang['AdminTickets.client.category_closed'] = "Geschlossen";
$lang['AdminTickets.client.categorylink_createticket'] = "Ticket erstellen";
$lang['AdminTickets.client.boxtitle_tickets'] = "Tickets";
$lang['AdminTickets.client.heading_code'] = "Ticket Nummer";
$lang['AdminTickets.client.heading_priority'] = "Priorität";
$lang['AdminTickets.client.heading_department_name'] = "Abteilung";
$lang['AdminTickets.client.heading_summary'] = "Zusammenfassung";
$lang['AdminTickets.client.heading_last_reply_date'] = "Letzte Antwort";
$lang['AdminTickets.client.no_results'] = "

Derzeit gibt es keine Tickets mit diesem Status.
";
$lang['AdminTickets.search.boxtitle_tickets'] = "Tickets suchen für \"%1\$s\""; // %1$s is the search criteria
$lang['AdminTickets.search.heading_code'] = "Ticketnummer";
$lang['AdminTickets.search.heading_priority'] = "Priorität";
$lang['AdminTickets.search.heading_status'] = "Status";
$lang['AdminTickets.search.heading_department_name'] = "Bereich";
$lang['AdminTickets.search.heading_summary'] = "Zusammenfassung";
$lang['AdminTickets.search.heading_last_reply_date'] = "Letzte Antwort";
$lang['AdminTickets.search.no_results'] = "Es existieren keine Tickets die der Suchanfrage entsprechen.";
$lang['AdminTickets.index.last_reply_by'] = "durch";
$lang['Admintickets.add.client_placeholder'] = "Kundennummer oder Name";
$lang['AdminTickets.!success.ticket_split'] = "Das Ticket # %1\$s wurde erfolgreich in Ticket # %2\$s aufgeteilt."; // %1$s is the ticket number of the ticket being split, %2$s is the ticket number of the split ticket
$lang['AdminTickets.!success.ticket_merge'] = "Die ausgewählten Tickets wurden erfolgreich in Ticket # %1\$s zusammengeführt."; // %1$s is the ticket number
$lang['AdminTickets.!success.ticket_update_status'] = "Die ausgewählten Tickets wurden erfolgreich aktualisiert.";
$lang['AdminTickets.index.heading_assigned_staff'] = "Zugewiesen";
$lang['AdminTickets.index.unassigned'] = "Nicht zugewiesen";
$lang['AdminTickets.index.text_with_selected'] = "Mit markierten Tickets, ";
$lang['AdminTickets.index.text_into_ticket'] = "

In Ticket:
";
$lang['AdminTickets.index.text_to_status'] = "Ändern zu:";
$lang['AdminTickets.index.ticket_number_placeholder'] = "Ticketnummer";
$lang['AdminTickets.index.text_no_tickets'] = "Keine offenen Tickets gefunden. Versuchen Sie es erneut.";
$lang['AdminTickets.index.field_actionsubmit'] = "Absenden";
$lang['AdminTickets.index.ticket_name'] = "#%1\$s %2\$s %3\$s"; // %1$s is the ticket number, %2$s is the client's first name, %3$s is the client's last name
$lang['AdminTickets.index.ticket_email'] = "# %1\$s %2\$s"; // %1$s is the ticket number, %2$s is the client's email address
$lang['AdminTickets.reply.text_with_selected'] = "Führen Sie mit ausgewählten Antworten Folgendes aus:";
$lang['AdminTickets.reply.field_actionsubmit'] = "Gehen";
$lang['AdminTickets.index.heading_client'] = "Klient";
$lang['AdminTickets.!success.ticket_delete'] = "Die ausgewählten Tickets wurden erfolgreich gelöscht.";
$lang['AdminTickets.index.category_on_hold'] = "

In Wartestellung
";
$lang['AdminTickets.index.category_trash'] = "Abfall";
$lang['AdminTickets.client.category_on_hold'] = "

In Wartestellung
";
$lang['AdminTickets.client.category_trash'] = "Müll";
$lang['AdminTickets.reply.refresh'] = "Es gibt neue Antworten oder Statusänderungen.";
$lang['AdminTickets.reply.refresh_link'] = "Klicken Sie, um anzuzeigen.";
$lang['AdminTickets.index.minutes'] = "%1\$s Minuten"; // %1$s is the elapsed minutes
$lang['AdminTickets.index.hours'] = "%1\$s Stunden"; // %1$s is the elapsed hours
$lang['AdminTickets.index.field_summary'] = "Gesamt";
$lang['AdminTickets.index.field_last_reply'] = "Letzte Antwort";
$lang['AdminTickets.add.dropzone_drop_files_here'] = "Dateien zum Hochladen hier ablegen oder zum Auswählen von Dateien anklicken";
$lang['AdminTickets.reply.dropzone_remove_file'] = "Datei löschen";
?>