<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Global.time_since.day'] = "%1\$s Tage"; // %1$s is the number of days
$lang['Global.time_since.hour'] = "%1\$s Std."; // %1$s is the number of hours
$lang['Global.time_since.minute'] = "%1\$s min"; // %1$s is the number of minutes
$lang['Global.select.never'] = "-- Noch nie --";
$lang['Global.action.split'] = "Aufteilen";
$lang['Global.action.merge'] = "Verbinden";
$lang['Global.action.update_status'] = "Status aktualisieren";
$lang['Global.action.quote'] = "Zitat";
$lang['Global.action.delete'] = "Löschen";
?>