<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Knowledgebase.index.page_title'] = "Wissensdatenbank";
$lang['Knowledgebase.view.page_title'] = "%1\$s"; // %1\$s is the title of the knowledge base article
$lang['Knowledgebase.search.placeholder'] = "Haben Sie eine Frage? Suchen Sie hier in unserer Wissensdatenbank";
$lang['Knowledgebase.search.form_submit'] = "Suche";
$lang['Knowledgebase.index.heading_categories'] = "Kategorien";
$lang['Knowledgebase.index.heading_subcategories'] = "Unterkategorien";
$lang['Knowledgebase.index.category_items'] = "(%1\$s)"; // %1$s is the number of items within this category
$lang['Knowledgebase.index.categories_description'] = "Durchsuchen Sie unsere Wissensdatenbank nach Kategorie.";
$lang['Knowledgebase.index.categories_no_results'] = "Es sind keine Kategorien verfügbar.";
$lang['Knowledgebase.index.heading_popular'] = "populäre Artikel";
$lang['Knowledgebase.index.popular_description'] = "Die Leute fanden diese Artikel am nützlichsten.";
$lang['Knowledgebase.index.heading_articles'] = "Artikel";
$lang['Knowledgebase.index.articles_description'] = "Artikel in %1\$s."; // %1$s is the name of the category
$lang['Knowledgebase.search.articles_no_results'] = "Es gibt keine Artikel, die den Suchkriterien entsprechen.";
$lang['Knowledgebase.view.text_rate'] = "

Bitte bewerten Sie diesen Artikel, um unsere Knowledge Base zu verbessern.
";
$lang['Knowledgebase.view.edit'] = "Bearbeiten";
$lang['Knowledgebase.view.text_voted'] = "Sie haben schon für diesen Artikel gestimmt.";
$lang['Knowledgebase.view.text_vote_thanks'] = "Danke, dass Sie zu diesem Artikel abgestimmt haben!";
$lang['Knowledgebase.!text.root_directory'] = "Home";
$lang['Knowledgebase.!text.ellipsis'] = "…";
?>