<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PackageFeed.getOptionFields.example_code_pricing'] = "Zeigen Sie den Preis, die Verlängerung, die Einrichtungsgebühr, die Stornogebühr oder die Währung eines Paketpreises an:";
?>