<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SoftaculousPlugin.remote_error'] = "Verbindung zum remote server fehlgeschlagen.";
$lang['SoftaculousPlugin.remote_firewall_error'] = "Der Standort von Softaculous auf dem Remote-Server konnte nicht ermittelt werden. Möglicherweise verhindert eine Firewall den Zugriff.";
$lang['SoftaculousPlugin.admin_fname'] = "System";
$lang['SoftaculousPlugin.admin_lname'] = "Administrator";
$lang['SoftaculousPlugin.installation_success'] = "Skript für den Dienst mit der ID %1\$s erfolgreich installiert"; // %1$s is the script
?>