<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SoftaculousQueuedServices.errors.service_id.exists'] = "The angegebene Service existiert nicht.";
$lang['SoftaculousQueuedServices.errors.company_id.exists'] = "Das angegebene Unternehmen existiert nicht.";
?>