<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Util.Tax.europe_tax.fields.note_tax_exempt_eu_vat'] = "Setzen Sie einen Kunden automatisch als steuerbefreit, wenn seine Mehrwertsteuer-Nummer gültig ist und nicht aus Ihrem Steuerwohnsitz stammt.";
?>