<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Ispmanager.manage.module_groups_title'] = "Server-Gruppen";
$lang['Ispmanager.manage.module_rows_heading.accounts'] = "Konten";
$lang['Ispmanager.manage.module_rows.edit'] = "Bearbeiten";
$lang['Ispmanager.manage.module_groups.edit'] = "Bearbeiten";
$lang['Ispmanager.manage.module_groups.delete'] = "Löschen";
$lang['Ispmanager.manage.module_rows.confirm_delete'] = "Sind Sie sicher, dass Sie diesen Server löschen wollen?";
$lang['Ispmanager.manage.module_groups.confirm_delete'] = "Sind Sie sicher, dass Sie diese Servergruppe löschen wollen?";
$lang['Ispmanager.add_row.box_title'] = "ISPmanager-Server hinzufügen";
$lang['Ispmanager.add_row.notes_title'] = "Notizen";
$lang['Ispmanager.add_row.add_btn'] = "Server hinzufügen";
$lang['Ispmanager.edit_row.name_servers_title'] = "Nameserver";
$lang['Ispmanager.tab_client_actions.field_password_submit'] = "Passwort aktualisieren";
$lang['Ispmanager.package_fields.template'] = "Vorlage";
$lang['Ispmanager.service_info.username'] = "Benutzername";
$lang['Ispmanager.!error.host_name_valid'] = "Der Hostname scheint ungültig zu sein.";
$lang['Ispmanager.!error.name_servers_count'] = "Sie müssen mindestens 2 Nameserver definieren.";
$lang['Ispmanager.!error.api.internal'] = "Ein interner Fehler ist aufgetreten oder der Server hat nicht auf die Anfrage geantwortet.";
$lang['Ispmanager.!error.ispmanager_password.matches'] = "Kennwort und Bestätigungskennwort stimmen nicht überein.";
$lang['Ispmanager.!error.api'] = "Es ist ein interner Fehler aufgetreten, oder der Server hat nicht auf die Anfrage geantwortet.";
?>