<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Vultr.name'] = "Vultr";
$lang['Vultr.module_row'] = "Konto";
$lang['Vultr.module_row_plural'] = "Konten";
$lang['Vultr.tab_actions'] = "Aktionen";
$lang['Vultr.tab_stats'] = "Statistiken";
$lang['Vultr.tab_snapshots'] = "

Snapshots
";
$lang['Vultr.tab_backups'] = "Sicherungen";
$lang['Vultr.tab_client_actions'] = "

Aktionen
";
$lang['Vultr.tab_client_stats'] = "Statistik";
$lang['Vultr.tab_client_snapshots'] = "Snapshots";
$lang['Vultr.tab_client_backups'] = "Backups";
$lang['Vultr.add_module_row'] = "Konto hinzufügen";
$lang['Vultr.manage.module_rows_title'] = "Konten";
$lang['Vultr.manage.module_rows_heading.name'] = "Konto";
$lang['Vultr.manage.module_rows_heading.options'] = "Optionen";
$lang['Vultr.manage.module_rows.edit'] = "Bearbeiten";
$lang['Vultr.manage.module_rows.delete'] = "Löschen";
$lang['Vultr.manage.module_rows.confirm_delete'] = "Möchten Sie dieses Konto wirklich löschen?";
$lang['Vultr.manage.module_rows_no_results'] = "Es gibt keine Konten.";
$lang['Vultr.add_row.box_title'] = "Vultr Server hinzufügen";
$lang['Vultr.add_row.basic_title'] = "Grundeinstellungen";
$lang['Vultr.add_row.add_btn'] = "Server hinzufügen";
$lang['Vultr.edit_row.box_title'] = "Vultr Server bearbeiten";
$lang['Vultr.edit_row.basic_title'] = "Grundeinstellungen";
$lang['Vultr.edit_row.add_btn'] = "Server bearbeiten";
$lang['Vultr.row_meta.account_name'] = "Kontobezeichnung";
$lang['Vultr.row_meta.api_key'] = "

API-Schlüssel
";
$lang['Vultr.package_fields.server_type'] = "Server Typ";
$lang['Vultr.package_fields.server_type.baremetal'] = "Bare Metal";
$lang['Vultr.package_fields.server_type.server'] = "Virtuelle Maschine";
$lang['Vultr.package_fields.baremetal_plan'] = "

Bare-Metal-Plan
";
$lang['Vultr.package_fields.server_plan'] = "Serverplan";
$lang['Vultr.package_fields.set_template'] = "Template festlegen";
$lang['Vultr.package_fields.admin_set_template'] = "Wählen Sie ein Template aus";
$lang['Vultr.package_fields.client_set_template'] = "Kundenspezifische Vorlage zulassen";
$lang['Vultr.package_fields.template'] = "Template";
$lang['Vultr.package_fields.surcharge_templates'] = "Zuschlagsvorlagen";
$lang['Vultr.package_fields.allow_surcharge_templates'] = "Aufschlag Templates zulassen";
$lang['Vultr.package_fields.disallow_surcharge_templates'] = "Aufschlag Templates deaktivieren";
$lang['Vultr.service_field.subid'] = "Vultr SUBID";
$lang['Vultr.service_field.hostname'] = "Hostname";
$lang['Vultr.service_field.location'] = "Ort";
$lang['Vultr.service_field.template'] = "Template";
$lang['Vultr.service_field.ipv6'] = "IPv6-Netzwerk";
$lang['Vultr.service_field.enable_ipv6'] = "IPv6 aktivieren";
$lang['Vultr.service_field.disable_ipv6'] = "IPv6 deaktivieren";
$lang['Vultr.tab_actions.status_title'] = "Server Status";
$lang['Vultr.tab_actions.server_title'] = "Serveraktionen";
$lang['Vultr.tab_actions.action_restart'] = "Neustart";
$lang['Vultr.tab_actions.action_stop'] = "Stop";
$lang['Vultr.tab_actions.action_start'] = "Start";
$lang['Vultr.tab_actions.action_reinstall_template'] = "Installier das Template erneut";
$lang['Vultr.tab_actions.action_change_template'] = "Template ändern";
$lang['Vultr.tab_actions.heading_change_template'] = "Template ändern";
$lang['Vultr.tab_actions.field_template'] = "Template";
$lang['Vultr.tab_actions.field_change_template_submit'] = "Template ändern";
$lang['Vultr.tab_actions.action_kvm_console'] = "KVM-Konsole";
$lang['Vultr.tab_stats.server_information'] = "Serverinformation";
$lang['Vultr.tab_stats.info_heading.field'] = "Feld";
$lang['Vultr.tab_stats.info_heading.value'] = "Wert";
$lang['Vultr.tab_stats.info.os'] = "Betriebssystem";
$lang['Vultr.tab_stats.info.ram'] = "Server RAM";
$lang['Vultr.tab_stats.info.disk'] = "

Server-Festplatte
";
$lang['Vultr.tab_stats.info.main_ip'] = "Haupt-IP";
$lang['Vultr.tab_stats.info.vcpu_count'] = "Virtuelle CPUs";
$lang['Vultr.tab_stats.info.cpu_count'] = "CPU Kerne";
$lang['Vultr.tab_stats.info.location'] = "Ort";
$lang['Vultr.tab_stats.info.default_password'] = "Standard-Passwort";
$lang['Vultr.tab_stats.info.current_bandwidth_gb'] = "Aktuelle Bandbreite (in GB)";
$lang['Vultr.tab_stats.info.allowed_bandwidth_gb'] = "Zulässige Bandbreite (in GB)";
$lang['Vultr.tab_stats.info.netmask_v4'] = "IPv4-Netzmaske";
$lang['Vultr.tab_stats.info.gateway_v4'] = "IPv4-Gateway";
$lang['Vultr.tab_stats.app_information'] = "Anwendungsinformationen";
$lang['Vultr.tab_snapshots.snapshots'] = "Snapshots";
$lang['Vultr.tab_snapshots.heading_row_snapshot_id'] = "Snapshot ID";
$lang['Vultr.tab_snapshots.heading_row_description'] = "Beschreibung";
$lang['Vultr.tab_snapshots.heading_row_options'] = "Optionen";
$lang['Vultr.tab_snapshots.restore_snapshot'] = "Schnappschuss wiederherstellen";
$lang['Vultr.tab_snapshots.remove_snapshot'] = "Snapshot entfernen";
$lang['Vultr.tab_snapshots.no_snapshots'] = "Momentan gibt es keine Snapshots.";
$lang['Vultr.tab_snapshots.heading_create'] = "Snapshot erstellen";
$lang['Vultr.tab_snapshots.field_description'] = "Beschreibung";
$lang['Vultr.tab_snapshots.field_create_submit'] = "Erstellen";
$lang['Vultr.tab_backups.backups'] = "Backups";
$lang['Vultr.tab_backups.heading_row_backup_id'] = "Backup ID";
$lang['Vultr.tab_backups.heading_row_date_created'] = "Datum erstellt";
$lang['Vultr.tab_backups.heading_row_description'] = "

Beschreibung
";
$lang['Vultr.tab_backups.heading_row_options'] = "Optionen";
$lang['Vultr.tab_backups.restore_backup'] = "Backup wiederherstellen";
$lang['Vultr.tab_backups.no_backups'] = "Derzeit gibt es keine Backups.";
$lang['Vultr.tab_backups.backups_disabled'] = "Dieser Server hat keine automatischen Sicherungen aktiviert oder unterstützt sie nicht.";
$lang['Vultr.tab_client_actions.heading_status'] = "Server Status";
$lang['Vultr.tab_client_actions.status_online'] = "Online";
$lang['Vultr.tab_client_actions.status_offline'] = "Offline";
$lang['Vultr.tab_client_actions.heading_actions'] = "Aktionen";
$lang['Vultr.tab_client_actions.action_restart'] = "Neustart";
$lang['Vultr.tab_client_actions.action_stop'] = "Stopp";
$lang['Vultr.tab_client_actions.action_start'] = "

Start
";
$lang['Vultr.tab_client_actions.action_reinstall_template'] = "Installieren Sie das Template erneut";
$lang['Vultr.tab_client_actions.action_change_template'] = "Template ändern";
$lang['Vultr.tab_client_actions.action_kvm_console'] = "KVM-Konsole";
$lang['Vultr.tab_client_actions.heading_change_template'] = "Template ändern";
$lang['Vultr.tab_client_actions.field_template'] = "Template";
$lang['Vultr.tab_client_actions.field_change_template_submit'] = "Vorlage ändern";
$lang['Vultr.tab_client_stats.server_information'] = "Serverinformation";
$lang['Vultr.tab_client_stats.info_heading.field'] = "

Feld
";
$lang['Vultr.tab_client_stats.info_heading.value'] = "Wert";
$lang['Vultr.tab_client_stats.info.os'] = "Betriebssystem";
$lang['Vultr.tab_client_stats.info.ram'] = "Server RAM";
$lang['Vultr.tab_client_stats.info.disk'] = "Server-Festplatte";
$lang['Vultr.tab_client_stats.info.main_ip'] = "Haupt-IP";
$lang['Vultr.tab_client_stats.info.vcpu_count'] = "Virtuelle CPUs";
$lang['Vultr.tab_client_stats.info.cpu_count'] = "CPU-Kerne";
$lang['Vultr.tab_client_stats.info.location'] = "

Ort
";
$lang['Vultr.tab_client_stats.info.default_password'] = "Standard-Passwort";
$lang['Vultr.tab_client_stats.info.current_bandwidth_gb'] = "Aktuelle Bandbreite (in GB)";
$lang['Vultr.tab_client_stats.info.allowed_bandwidth_gb'] = "Zulässige Bandbreite (in GB)";
$lang['Vultr.tab_client_stats.info.netmask_v4'] = "IPv4-Netzmaske";
$lang['Vultr.tab_client_stats.info.gateway_v4'] = "IPv4-Gateway";
$lang['Vultr.tab_client_stats.app_information'] = "Anwendungsinformationen";
$lang['Vultr.tab_client_snapshots.snapshots'] = "Snapshots";
$lang['Vultr.tab_client_snapshots.snapshot_id'] = "Snapshot ID";
$lang['Vultr.tab_client_snapshots.description'] = "Beschreibung";
$lang['Vultr.tab_client_snapshots.options'] = "Optionen";
$lang['Vultr.tab_client_snapshots.heading_restore_snapshot'] = "Snapshot wiederherstellen %1\$s"; // %1$s is the snapshot id
$lang['Vultr.tab_client_snapshots.heading_remove_snapshot'] = "Snapshot entfernen %1\$s"; // %1$s is the snapshot id
$lang['Vultr.tab_client_snapshots.confirm_restore_snapshot'] = "Möchten Sie diesen Snapshot wirklich wiederherstellen?";
$lang['Vultr.tab_client_snapshots.confirm_remove_snapshot'] = "Möchten Sie diesen Snapshot wirklich dauerhaft entfernen?";
$lang['Vultr.tab_client_snapshots.cancel'] = "Abbrechen";
$lang['Vultr.tab_client_snapshots.restore_snapshot'] = "Snapshot wiederherstellen";
$lang['Vultr.tab_client_snapshots.remove_snapshot'] = "Snapshot entfernen";
$lang['Vultr.tab_client_snapshots.no_snapshots'] = "Momentan gibt es keine Snapshots.";
$lang['Vultr.tab_client_snapshots.heading_create'] = "Snapshot erstellen";
$lang['Vultr.tab_client_snapshots.field_description'] = "Beschreibung";
$lang['Vultr.tab_client_snapshots.field_create_submit'] = "Erstellen";
$lang['Vultr.tab_client_backups.backups'] = "Backups";
$lang['Vultr.tab_client_backups.backup_id'] = "Backup ID";
$lang['Vultr.tab_client_backups.date_created'] = "Datum erstellt";
$lang['Vultr.tab_client_backups.description'] = "Beschreibung";
$lang['Vultr.tab_client_backups.options'] = "Optionen";
$lang['Vultr.tab_client_backups.restore_backup'] = "Restore Backup";
$lang['Vultr.tab_client_backups.heading_restore_backup'] = "Backup wiederherstellen %1\$s"; // %1$s is the backup id
$lang['Vultr.tab_client_backups.confirm_restore_backup'] = "Möchten Sie diese Sicherung wirklich wiederherstellen?";
$lang['Vultr.tab_client_backups.cancel'] = "Abbrechen";
$lang['Vultr.tab_client_backups.no_backups'] = "Derzeit gibt es keine Backups.";
$lang['Vultr.tab_client_backups.backups_disabled'] = "Dieser Server hat keine automatischen Sicherungen aktiviert oder unterstützt sie nicht.";
$lang['Vultr.service_info.hostname'] = "Hostname";
$lang['Vultr.service_info.os'] = "

Betriebssystem
";
$lang['Vultr.service_info.location'] = "Ort";
$lang['Vultr.service_info.main_ip'] = "Haupt-IP";
$lang['Vultr.service_info.default_password'] = "

Passwort
";
$lang['Vultr.service_field.tooltip.subid'] = "Die eindeutige Kennung für dieses Abonnement.";
$lang['Vultr.!error.account_name_valid'] = "

Bitte geben Sie einen gültigen Kontonamen ein.
";
$lang['Vultr.!error.api_key_valid'] = "Der API-Schlüssel scheint ungültig zu sein.";
$lang['Vultr.!error.api_key_valid_connection'] = "Es konnte keine Verbindung zum Server hergestellt werden. Bitte überprüfen Sie, ob der API-Schlüssel korrekt ist.";
$lang['Vultr.!error.meta[server_type].valid'] = "Der Servertyp scheint ungültig zu sein.";
$lang['Vultr.!error.meta[baremetal_plan].format'] = "Bitte wählen Sie einen gültigen Bare-Metal-Plan aus.";
$lang['Vultr.!error.meta[server_plan].format'] = "Bitte wählen Sie einen gültigen Serverplan aus.";
$lang['Vultr.!error.api.internal'] = "Es ist ein interner Fehler aufgetreten oder der Server hat auf die Anforderung nicht geantwortet.";
$lang['Vultr.!error.module_row.missing'] = "Ein interner Fehler ist aufgetreten. Die Modulzeile ist nicht verfügbar.";
$lang['Vultr.!error.vultr_hostname.format'] = "Bitte geben Sie einen gültigen Hostnamen ein, z.B. domain.com.";
$lang['Vultr.!error.vultr_location.valid'] = "Bitte wählen Sie einen gültigen Standort.";
$lang['Vultr.!error.vultr_template.valid'] = "Bitte wählen Sie ein gültiges Template.";
$lang['Vultr.!error.vultr_subid.valid'] = "Bitte geben Sie eine gültige Vultr-SUBID ein.";
$lang['Vultr.tab_actions.server_locked'] = "Ein Snapshot wird gerade wiederhergestellt. Dieser Vorgang kann bis zu 60 Minuten dauern. Die meisten Serveraktionen sind nicht verfügbar, bis dies abgeschlossen ist.";
$lang['Vultr.tab_snapshots.heading_row_status'] = "Status";
$lang['Vultr.tab_client_actions.status_locked'] = "Gesperrt";
$lang['Vultr.tab_client_snapshots.status'] = "Status";
$lang['Vultr.!error.api.server_locked'] = "Aktion kann nicht abgeschlossen werden. Server ist momentan gesperrt.";
$lang['Vultr.description'] = "Das Vultr Control Panel macht die Serververwaltung einfach und intuitiv. Übliche Aufgaben wie die Bestellung von Servern, die Verwaltung von Backups und die Anpassung der Zugriffskontrolle sind nur wenige Klicks entfernt.";
?>