<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Skrill.name'] = "Skrill";
$lang['Skrill.user_email'] = "E-Mail";
$lang['Skrill.secret_word'] = "Geheimwort";
$lang['Skrill.merchant_id'] = "Händler-ID";
$lang['Skrill.mqi'] = "MQI Passwort";
$lang['Skrill.secret_word_note'] = "

Geben Sie Ihr Skrill-Konto Secret Word ein.
";
$lang['Skrill.user_email_note'] = "Geben Sie die E-Mail-Adresse Ihres Skrill-Kontos ein.";
$lang['Skrill.merchant_id_note'] = "Geben Sie die Händler-ID Ihres Skrill-Kontos ein.";
$lang['Skrill.mqi_note'] = "Geben Sie Ihr MQI-API-Passwort für Ihr Skrill-Konto ein.";
$lang['Skrill.buildprocess.submit'] = "Bezahlen mit Skrill";
$lang['Skrill.invoice.description'] = "Rechnungen";
$lang['Skrill.!error.libxml_required'] = "Die Erweiterungen libxml und simplexml sind für dieses Gateway erforderlich.";
$lang['Skrill.!error.user_email.valid'] = "Bitte geben sie eine gültige E-Mail Adresse an.";
$lang['Skrill.!error.secret_word.empty'] = "Bitte geben Sie Ihr geheimes Passwort ein.";
$lang['Skrill.!error.mqi.empty'] = "Bitte geben Sie Ihr MQI-Passwort ein.";
$lang['Skrill.!error.merchant_id.empty'] = "

Bitte geben Sie Ihre Händler-ID ein.
";
?>