<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Quantum_gateway.!error.gateway_login.empty'] = "Bitte geben Sie Ihren Gateway Login ein";
$lang['Quantum_gateway.!error.restrict_key.empty'] = "Bitte geben Sie Ihren Restrict Key ein";
$lang['Quantum_gateway.!error.maxmind.valid'] = "

Maxmind muss auf \"true\" gesetzt sein, falls angegeben.
";
$lang['Quantum_gateway.name'] = "QuantumGateway";
$lang['Quantum_gateway.gateway_login'] = "Gateway Login";
$lang['Quantum_gateway.restrict_key'] = "

Schlüssel einschränken
";
$lang['Quantum_gateway.maxmind'] = "Benutze Maxmind";
$lang['Quantum_gateway.tooltip_maxmind'] = "Markieren Sie das Kästchen, um Maxmind Frau Control zu aktivieren. Überprüfen Sie Ihr QuantumGateway Control Panel für zusätzliche Maxmind Einstellungen.";
?>