<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ImportManagerManagePlugin.!success.imported'] = "Der Importeur wurde verarbeitet.";
$lang['ImportManagerManagePlugin.index.boxtitle_importmanager'] = "

Import Manager
";
$lang['ImportManagerManagePlugin.index.page_title'] = "Importmanager&gt; Importieren";
$lang['ImportManagerManagePlugin.index.platform'] = "Plattform";
$lang['ImportManagerManagePlugin.index.versions'] = "Versionen";
$lang['ImportManagerManagePlugin.index.no_migrators'] = "Es sind keine Migratoren verfügbar.";
$lang['ImportManagerManagePlugin.import.boxtitle_importmanager'] = "Importieren aus %1\$s Version %2\$s"; // %1$s is the import type %2$s is the version
$lang['ImportManagerManagePlugin.import.page_title'] = "Importmanager&gt; Importieren";
$lang['ImportManagerManagePlugin.import.continue'] = "Weiter";
$lang['ImportManagerManagePlugin.import.submit'] = "Einführen";
$lang['ImportManagerManagePlugin.import.cancel'] = "Abbrechen, nicht importieren";
?>