<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PterodactylService.!error.server_name.empty'] = "Bitte geben Sie einen Namen für den Server an.";
$lang['PterodactylService.service_fields.server_name'] = "Server Name";
$lang['PterodactylService.service_fields.tooltip.server_name'] = "Der Name des Servers.";
$lang['PterodactylService.service_fields.server_id'] = "Server ID (Optional)";
$lang['PterodactylService.service_fields.optional'] = "%1\$s (Optional)"; // %1$s is the name of the field
?>