<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PterodactylPackage.!error.meta[memory].format'] = "Die Speichermenge muss numerisch sein.";
$lang['PterodactylPackage.!error.meta[databases].format'] = "Die Anzahl der Datenbanken muss numerisch sein.";
$lang['PterodactylPackage.package_fields.dedicated_ip'] = "Dedizierte IP (optional)";
$lang['PterodactylPackage.package_fields.tooltip.dedicated_ip'] = "Weisen Sie den erstellten Servern eine dedizierte IP zu.";
$lang['PterodactylPackage.package_fields.tooltip.pack_id'] = "ID des Paketes, mit dem der Server installiert werden soll.";
$lang['PterodactylPackage.package_fields.disk'] = "Speicherplatz (MB)";
$lang['PterodactylPackage.package_fields.tooltip.io'] = "Block IO Einstellungsnummer (10-1000).";
$lang['PterodactylPackage.package_fields.tooltip.image'] = "Benutzerdefiniertes Docker-Image, das den erstellten Servern zugewiesen wird (z. B. quay.io/pterodactyl/core:java-glibc).";
?>