<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Pterodactyl.name'] = "Pterodactyl";
$lang['Pterodactyl.module_row'] = "Server";
$lang['Pterodactyl.module_row_plural'] = "Server";
$lang['Pterodactyl.!error.server_name.empty'] = "Sie müssen einen Servernamen eingeben.";
$lang['Pterodactyl.!error.host_name.valid'] = "Der Hostname scheint ungültig zu sein.";
$lang['Pterodactyl.!error.account_api_key.valid'] = "Die Verbindung mit der angegebenen URL und dem Konto-API-Schlüssel kann nicht hergestellt werden.";
$lang['Pterodactyl.!error.module_row.missing'] = "Ein interner Fehler ist aufgetreten. Die Modulzeile ist nicht verfügbar.";
$lang['Pterodactyl.!success.stop'] = "Der Server wird jetzt heruntergefahren.";
$lang['Pterodactyl.!success.restart'] = "Der Server startet jetzt neu.";
$lang['Pterodactyl.row_meta.use_ssl'] = "Verwenden Sie SSL, wenn Sie eine Verbindung zur API herstellen (empfohlen).";
$lang['Pterodactyl.order_options.first'] = "Erster \"nicht voller\" Server";
$lang['Pterodactyl.manage.module_groups_title'] = "Server-Gruppen";
$lang['Pterodactyl.manage.module_rows_heading.host_name'] = "Hostname";
$lang['Pterodactyl.manage.module_rows_heading.options'] = "Optionen";
$lang['Pterodactyl.manage.module_groups_heading.options'] = "Optionen";
$lang['Pterodactyl.manage.module_rows.edit'] = "Bearbeiten";
$lang['Pterodactyl.service_info.password'] = "Passwort";
$lang['Pterodactyl.tab_actions.status_starting'] = "Beginn";
$lang['Pterodactyl.tab_actions.status_stopping'] = "Stoppen";
$lang['Pterodactyl.tab_client_actions.heading_actions'] = "Aktionen";
$lang['Pterodactyl.tab_client_actions.server_status'] = "Server Status";
$lang['Pterodactyl.tab_client_actions.status_stopping'] = "Anhalten";
$lang['Pterodactyl.!actions.stop'] = "Halt";
$lang['Pterodactyl.!actions.restart'] = "Neustarten";
?>