<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MulticraftModule.!error.json.unavailable'] = "Die JSON-Erweiterung wird von diesem Modul benötigt.";
$lang['MulticraftModule.!error.server_name.empty'] = "Bitte geben Sie eine Bezeichnung für diesen Server ein.";
$lang['MulticraftModule.!error.panel_url.empty'] = "Bitte geben Sie die URL zum Multicraft-Panel an.";
$lang['MulticraftModule.!error.panel_api_url.empty'] = "

Bitte geben Sie die URL Ihrer Multicraft Panel-API ein.
";
$lang['MulticraftModule.!error.username.empty'] = "Bitte geben Sie Ihren Multicraft-Benutzernamen ein";
$lang['MulticraftModule.!error.key.empty'] = "Bitte geben Sie Ihren API-Schlüssel ein";
$lang['MulticraftModule.!error.log_all.format'] = "Ob alle API-Anforderungen protokolliert werden sollen, muss auf 1 oder 0 festgelegt werden.";
$lang['MulticraftModule.!error.ips.match'] = "Bitte legen Sie eine IP-Adresse für jeden Dämonsatz fest.";
$lang['MulticraftModule.!error.daemons.match'] = "Bitte legen Sie für jede IP-Adresse eine Daemon-ID fest.";
$lang['MulticraftModule.!error.ips_in_use.match'] = "Bitte stellen Sie ein, ob die IP-Adresse aktuell auf 1 oder 0 eingestellt ist.";
?>