<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PterodactylRule.!error.required'] = "Das Feld %1\$s ist erforderlich."; // %1$s is the name of the required field
$lang['PterodactylRule.!error.numeric'] = "Das Feld %1\$s muss eine Zahl enthalten."; // %1$s is the name of the field
$lang['PterodactylRule.!error.digitsBetween'] = "Das Feld %1\$s muss einen Wert zwischen %2\$s und %3\$s haben."; // %1$s is the name of the field, %2$s is the minimum value/length, %3$s is the maximum value/length
?>