<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerStaff.!error.staff_id.exists'] = "Der hinzuzufügende Mitarbeiter existiert nicht.";
$lang['SupportManagerStaff.!error.staff_id.belongs'] = "Der Mitarbeiter gehört nicht zu der Firma, der er zugeordnet ist.";
$lang['SupportManagerStaff.!error.staff_id.duplicate'] = "

Der ausgewählte Mitarbeiter ist bereits im Support-System vorhanden.
";
$lang['SupportManagerStaff.!error.company_id.exists'] = "Die Firmen-ID ist ungültig.";
$lang['SupportManagerStaff.!error.departments.exists'] = "Mindestens eine der eingerichteten Abteilungen existiert nicht.";
$lang['SupportManagerStaff.!error.schedules.minimum'] = "Bitte legen Sie eine geplante Start- und Endzeit für mindestens einen Tag fest.";
$lang['SupportManagerStaff.!error.schedules.unique_days'] = "Jeder geplante Tag muss eindeutig sein.";
$lang['SupportManagerStaff.!error.schedules[][day].format'] = "

Ungültiger geplanter Tag
";
$lang['SupportManagerStaff.!error.schedules[][start_time].format'] = "Bitte wählen Sie eine Startzeit für jeden geplanten Tag.";
$lang['SupportManagerStaff.!error.schedules[][end_time].format'] = "Bitte wählen Sie eine Endzeit für jeden geplanten Tag.";
$lang['SupportManagerStaff.days.sun'] = "Sonntag";
$lang['SupportManagerStaff.days.mon'] = "Montag";
$lang['SupportManagerStaff.days.tue'] = "Dienstag";
$lang['SupportManagerStaff.days.wed'] = "Mittwoch";
$lang['SupportManagerStaff.days.thu'] = "Donnerstag";
$lang['SupportManagerStaff.days.fri'] = "Freitag";
$lang['SupportManagerStaff.days.sat'] = "Samstag";
?>