<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerKbCategories.!error.parent_id.exists'] = "Ungültige Eltern-ID";
$lang['SupportManagerKbCategories.!error.parent_id.valid_company'] = "Diese Kategorie darf keinem Elternteil einer separaten Firma zugeordnet werden.";
$lang['SupportManagerKbCategories.!error.parent_id.valid_parent'] = "Diese Kategorie kann kein Elternteil für sich selbst sein.";
$lang['SupportManagerKbCategories.!error.company_id.exists'] = "Ungültige Firmen-ID";
$lang['SupportManagerKbCategories.!error.name.empty'] = "Bitte geben Sie einen Kategorienamen ein.";
$lang['SupportManagerKbCategories.!error.name.length'] = "

Der Kategoriename darf nicht länger als 255 Zeichen sein.
";
$lang['SupportManagerKbCategories.!error.access.type'] = "Ungültiger Zugriffstyp.";
$lang['SupportManagerKbCategories.!error.category_id.exists'] = "Ungültige Kategorie-ID.";
$lang['SupportManagerKbCategories.access_types.public'] = "Öffentlich";
$lang['SupportManagerKbCategories.access_types.private'] = "Privatgelände";
$lang['SupportManagerKbCategories.access_types.hidden'] = "Versteckt";
$lang['SupportManagerKbCategories.!error.articles.parent'] = "Die Kategorie kann nicht gelöscht werden, es sei denn, alle Artikel in dieser Kategorie gehören einer anderen Kategorie an.";
?>