<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerResponses.!error.company_id.exists'] = "Ungültige Firmen ID";
$lang['SupportManagerResponses.!error.parent_id.exists'] = "Ungültige Elternkategorie-ID";
$lang['SupportManagerResponses.!error.parent_id.company'] = "

Diese Kategorie muss zu derselben Firma gehören wie ihre Muttergesellschaft.
";
$lang['SupportManagerResponses.!error.name.empty'] = "Bitte geben Sie einen Kategorienamen ein.";
$lang['SupportManagerResponses.!error.name.length'] = "Der Kategoriename darf nicht mehr als 64 Charaktere überschreiten.";
$lang['SupportManagerResponses.!error.category_id.exists'] = "Ungültige Kategorie-ID";
$lang['SupportManagerResponses.!error.name.response_empty'] = "

Bitte geben Sie einen Namen für diese Antwort ein.
";
$lang['SupportManagerResponses.!error.name.response_length'] = "Der Kategoriename darf 64 Zeichen nicht überschreiten.";
$lang['SupportManagerResponses.!error.details.empty'] = "

Bitte geben Sie die Antwortdetails ein.
";
$lang['SupportManagerResponses.!error.category_id.root_responses'] = "Die Kategorie kann nicht gelöscht werden, da sie vordefinierte Antworten enthält.";
?>