<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Automation.task.cancel_scheduled_services.cancel_success'] = "Der Dienst #%1\$s von Kunde #%2\$s wurde storniert."; // %1$s is the service ID, %2$s is the client ID
?>