<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Automation.task.plugin.attempt'] = "Versuch eines Plugin-Cron für %1\$s %2\$s."; // %1$s is the plugin dir, %2$s is the plugin cron task key
?>