<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Logicboxes.name'] = "LogicBoxes";
$lang['Logicboxes.module_row'] = "Konto";
$lang['Logicboxes.module_row_plural'] = "Konten";
$lang['Logicboxes.add_module_row'] = "Konto hinzufügen";
$lang['Logicboxes.manage.module_rows_title'] = "Konten";
$lang['Logicboxes.manage.module_rows_heading.registrar'] = "

Registrar Name
";
$lang['Logicboxes.manage.module_rows_heading.reseller_id'] = "Händler-ID";
$lang['Logicboxes.manage.module_rows_heading.key'] = "API-Schlüssel";
$lang['Logicboxes.manage.module_rows_heading.sandbox'] = "Sandkasten";
$lang['Logicboxes.manage.module_rows_heading.options'] = "Optionen";
$lang['Logicboxes.manage.module_rows.edit'] = "Bearbeiten";
$lang['Logicboxes.manage.module_rows.delete'] = "Löschen";
$lang['Logicboxes.manage.module_rows.confirm_delete'] = "Sind Sie sicher, dass Sie Ihr Konto löschen wollen?";
$lang['Logicboxes.manage.module_rows_no_results'] = "Es gibt keine Konten.";
$lang['Logicboxes.row_meta.registrar'] = "Registrar Name";
$lang['Logicboxes.row_meta.reseller_id'] = "Reseller ID";
$lang['Logicboxes.row_meta.key'] = "Schlüssel";
$lang['Logicboxes.row_meta.sandbox'] = "Sandbox";
$lang['Logicboxes.row_meta.sandbox_true'] = "Ja";
$lang['Logicboxes.row_meta.sandbox_false'] = "Nein";
$lang['Logicboxes.add_row.box_title'] = "LogicBoxes Account hinzufügen ";
$lang['Logicboxes.add_row.basic_title'] = "Grundeinstellungen";
$lang['Logicboxes.add_row.add_btn'] = "

Konto hinzufügen
";
$lang['Logicboxes.edit_row.box_title'] = "Bearbeite LogicBoxes Account";
$lang['Logicboxes.edit_row.basic_title'] = "Grundeinstellungen";
$lang['Logicboxes.edit_row.add_btn'] = "Account aktualisieren";
$lang['Logicboxes.package_fields.type'] = "Art";
$lang['Logicboxes.package_fields.type_domain'] = "Domain Registration";
$lang['Logicboxes.package_fields.type_ssl'] = "SSL-Zertifikate";
$lang['Logicboxes.package_fields.tld_options'] = "TLDs";
$lang['Logicboxes.package_fields.ns1'] = "Namenserver 1";
$lang['Logicboxes.package_fields.ns2'] = "NameServer 2";
$lang['Logicboxes.package_fields.ns3'] = "Name Server 3";
$lang['Logicboxes.package_fields.ns4'] = "Nameserver 4";
$lang['Logicboxes.package_fields.ns5'] = "Name Server 5";
$lang['Logicboxes.tab_whois.title'] = "Whois";
$lang['Logicboxes.tab_whois.section_registrantcontact'] = "Registrant";
$lang['Logicboxes.tab_whois.section_admincontact'] = "Administrativ";
$lang['Logicboxes.tab_whois.section_techcontact'] = "Technisch";
$lang['Logicboxes.tab_whois.section_billingcontact'] = "Abrechnung";
$lang['Logicboxes.tab_whois.field_submit'] = "Whois aktualisieren";
$lang['Logicboxes.tab_nameservers.title'] = "Name Server";
$lang['Logicboxes.tab_nameserver.field_ns'] = "Namenserver %1\$s"; // %1$s is the name server number
$lang['Logicboxes.tab_nameservers.field_submit'] = "Name Server aktualisieren";
$lang['Logicboxes.tab_settings.title'] = "Einstellungen";
$lang['Logicboxes.tab_settings.field_registrar_lock'] = "

Registrar-Sperre
";
$lang['Logicboxes.tab_settings.field_registrar_lock_yes'] = "Legen Sie die Registrarsperre fest. Empfohlen, um eine nicht autorisierte Übertragung zu verhindern.";
$lang['Logicboxes.tab_settings.field_registrar_lock_no'] = "Geben Sie die Registrierungssperre frei, damit die Domain übertragen werden kann.";
$lang['Logicboxes.tab_settings.field_request_epp'] = "Fordern Sie den EPP-Code / Übertragungsschlüssel an";
$lang['Logicboxes.tab_settings.field_submit'] = "Einstellungen aktualisieren";
$lang['Logicboxes.!error.registrar.valid'] = "Bitte geben Sie einen Registrar-Namen ein.";
$lang['Logicboxes.!error.reseller_id.valid'] = "

Bitte geben Sie eine Reseller-ID ein.
";
$lang['Logicboxes.!error.key.valid'] = "Bitte gib einen Schlüssel ein.";
$lang['Logicboxes.!error.key.valid_connection'] = "

Die Reseller-ID und die Schlüsselkombination scheinen ungültig zu sein, oder Ihr LogicBoxes-Konto ist möglicherweise nicht für den API-Zugriff konfiguriert.
";
$lang['Logicboxes.transfer.domain-name'] = "Domänenname";
$lang['Logicboxes.transfer.auth-code'] = "EPP-Code";
$lang['Logicboxes.domain.domain-name'] = "Domänenname";
$lang['Logicboxes.nameserver.ns1'] = "Name Server 1";
$lang['Logicboxes.nameserver.ns2'] = "Namenserver 2";
$lang['Logicboxes.nameserver.ns3'] = "Name Server 3";
$lang['Logicboxes.nameserver.ns4'] = "Nameserver 4";
$lang['Logicboxes.nameserver.ns5'] = "Namenserver 5";
$lang['Logicboxes.contact.customer-id'] = "Kundennummer";
$lang['Logicboxes.contact.type'] = "Art";
$lang['Logicboxes.contact.name'] = "Name";
$lang['Logicboxes.contact.company'] = "Firma";
$lang['Logicboxes.contact.email'] = "Email";
$lang['Logicboxes.contact.address-line-1'] = "Adresse ";
$lang['Logicboxes.contact.address-line-2'] = "Adresse 2";
$lang['Logicboxes.contact.city'] = "Stadt";
$lang['Logicboxes.contact.state'] = "Zustand";
$lang['Logicboxes.contact.zipcode'] = "Postleitzahl";
$lang['Logicboxes.contact.country'] = "Land";
$lang['Logicboxes.contact.phone-cc'] = "Telefon-Landesvorwahl";
$lang['Logicboxes.contact.phone'] = "Telefonnummer";
$lang['Logicboxes.contact.fax-cc'] = "

Ländervorwahl per Fax
";
$lang['Logicboxes.contact.fax'] = "Faxnummer";
$lang['Logicboxes.customer.username'] = "Nutzername";
$lang['Logicboxes.customer.passwd'] = "Passwort";
$lang['Logicboxes.customer.lang-pref'] = "Sprache";
$lang['Logicboxes.contact.legalentitytype'] = "Gesetzlicher Typ";
$lang['Logicboxes.contact.legalentitytype.corporation'] = "Unternehmen oder Firmen";
$lang['Logicboxes.contact.legalentitytype.cooperative'] = "Genossenschaften";
$lang['Logicboxes.contact.legalentitytype.partnership'] = "

Partnerschaften oder Kollektive
";
$lang['Logicboxes.contact.legalentitytype.government'] = "Regierungsstellen";
$lang['Logicboxes.contact.legalentitytype.politicalParty'] = "Politische Parteien oder Gewerkschaften";
$lang['Logicboxes.contact.legalentitytype.society'] = "Stiftungen, Stände, Verbände oder Gesellschaften";
$lang['Logicboxes.contact.legalentitytype.institution'] = "Institutionen";
$lang['Logicboxes.contact.legalentitytype.naturalPerson'] = "

Natürliche Personen
";
$lang['Logicboxes.contact.identform'] = "Form der Identität";
$lang['Logicboxes.contact.identform.certificate'] = "Gründungsurkunde";
$lang['Logicboxes.contact.identform.legislation'] = "Charter";
$lang['Logicboxes.contact.identform.societyRegistry'] = "Gesellschaften Registry";
$lang['Logicboxes.contact.identform.politicalPartyRegistry'] = "Politische Partei Registry";
$lang['Logicboxes.contact.identform.passport'] = "Pass- / Staatsbürgerschafts-ID";
$lang['Logicboxes.contact.identnumber'] = "Identifikationsnummer";
$lang['Logicboxes.contact.CPR'] = "Gesetzlicher Typ";
$lang['Logicboxes.contact.CPR.cco'] = "Konzern";
$lang['Logicboxes.contact.CPR.cct'] = "Kanadischer Staatsbürger

";
$lang['Logicboxes.contact.CPR.res'] = "Kanadischer Einwohner";
$lang['Logicboxes.contact.CPR.gov'] = "Regierungsinstanz";
$lang['Logicboxes.contact.CPR.edu'] = "Bildungsbereich";
$lang['Logicboxes.contact.CPR.ass'] = "Nicht eingetragener Verein";
$lang['Logicboxes.contact.CPR.hop'] = "Krankenhaus";
$lang['Logicboxes.contact.CPR.prt'] = "Partnerschaft";
$lang['Logicboxes.contact.CPR.tdm'] = "Warenzeichen";
$lang['Logicboxes.contact.CPR.trd'] = "Gewerkschaft";
$lang['Logicboxes.contact.CPR.plt'] = "Politische Partei";
$lang['Logicboxes.contact.CPR.lam'] = "Bibliotheken, Archive und Museen";
$lang['Logicboxes.contact.CPR.trs'] = "Vertrauen";
$lang['Logicboxes.contact.CPR.abo'] = "

Ureinwohner
";
$lang['Logicboxes.contact.CPR.inb'] = "Indische Band";
$lang['Logicboxes.contact.CPR.lgr'] = "Gesetzlicher Vertreter";
$lang['Logicboxes.contact.CPR.omk'] = "Offizielle Marke";
$lang['Logicboxes.contact.CPR.maj'] = "

Die Königin
";
$lang['Logicboxes.contact.sponsor'] = "ROID des Sponsors (Kooperationsreferenz)";
$lang['Logicboxes.contact.es_tipo_identificacion'] = "

Idenfikation Art
";
$lang['Logicboxes.contact.es_tipo_identificacion.1'] = "

Spanische Personalausweis oder Umsatzsteuer-ID (DNI oder NIF)
";
$lang['Logicboxes.contact.es_tipo_identificacion.3'] = "Ausländer mit Wohnsitz in Spanien (NIE)";
$lang['Logicboxes.contact.es_tipo_identificacion.0'] = "Passnummer, Führerscheinnummer usw.";
$lang['Logicboxes.contact.es_identificacion'] = "Identifikationsnummer";
$lang['Logicboxes.contact.legalForm'] = "

Registrant-Typ
";
$lang['Logicboxes.contact.legalForm.persoon'] = "Natürliche Person";
$lang['Logicboxes.contact.legalForm.anders'] = "Andere";
$lang['Logicboxes.contact.profession'] = "Beruf";
$lang['Logicboxes.contact.contract-type'] = "kontaktart";
$lang['Logicboxes.contact.contract-type.org'] = "Organisation";
$lang['Logicboxes.contact.contract-type.prs'] = "Einzelperson";
$lang['Logicboxes.contact.birth-date'] = "Geburtsdatum (TT.MM.JJJJ), wenn Einzelperson";
$lang['Logicboxes.contact.kpp'] = "Gebietsgebundene Steuerzahlernummer bei Organisation";
$lang['Logicboxes.contact.code'] = "

Steuerzahler-Identifikationsnummer (TIN), wenn Organisation
";
$lang['Logicboxes.contact.passport'] = "Passnummer, ausgestellt von, und ausgestelltes Datum, wenn Individual";
$lang['Logicboxes.contact.category'] = "Registrant-Typ";
$lang['Logicboxes.contact.category.c11'] = "US-Bürger";
$lang['Logicboxes.contact.category.c12'] = "Ständiger Wohnsitz in den USA";
$lang['Logicboxes.contact.category.c21'] = "US-Unternehmen oder Organisation";
$lang['Logicboxes.contact.category.c31'] = "Ausländische Organisation";
$lang['Logicboxes.contact.category.c32'] = "Ausländische Organisation mit einem Büro in den USA";
$lang['Logicboxes.contact.purpose'] = "Zweck";
$lang['Logicboxes.contact.purpose.p1'] = "Geschäft";
$lang['Logicboxes.contact.purpose.p2'] = "Nicht kommerziell";
$lang['Logicboxes.contact.purpose.p3'] = "Persönlich";
$lang['Logicboxes.contact.purpose.p4'] = "Bildungsbereich";
$lang['Logicboxes.contact.purpose.p5'] = "Regierung";
$lang['Logicboxes.domain.id-type'] = "

Berechtigungs-ID-Typ
";
$lang['Logicboxes.domain.id-type.acn'] = "Australische Firmennummer";
$lang['Logicboxes.domain.id-type.abn'] = "

Australische Geschäftsnummer
";
$lang['Logicboxes.domain.id-type.vic_bn'] = "

Victoria Geschäftsnummer
";
$lang['Logicboxes.domain.id-type.nsw_bn'] = "New South Wales Geschäftsnummer";
$lang['Logicboxes.domain.id-type.sa_bn'] = "

South Australia Geschäftsnummer
";
$lang['Logicboxes.domain.id-type.nt_bn'] = "Northern Territory Geschäftsnummer";
$lang['Logicboxes.domain.id-type.wa_bn'] = "

Western Australia Geschäftsnummer
";
$lang['Logicboxes.domain.id-type.tas_bn'] = "Tasmanien-Geschäftszahl";
$lang['Logicboxes.domain.id-type.act_bn'] = "Nummer des australischen Hauptstadtterritoriums";
$lang['Logicboxes.domain.id-type.qld_bn'] = "Queensland Geschäftsnummer";
$lang['Logicboxes.domain.id-type.tm'] = "Handelsmarkennummer";
$lang['Logicboxes.domain.id-type.arbn'] = "Australische registrierte Körpernummer";
$lang['Logicboxes.domain.id-type.other'] = "Andere";
$lang['Logicboxes.domain.id'] = "Berechtigungs-ID";
$lang['Logicboxes.domain.policyReason'] = "

Förderfähigkeitsgrund
";
$lang['Logicboxes.domain.policyReason.1'] = "Der Domainenname ist eine genaue Entsprechung, ein Akronym oder eine Abkürzung der Firma oder des Handelsnamens des Registranten, des Unternehmens- oder Verbandsnamens oder der Marke";
$lang['Logicboxes.domain.policyReason.2'] = "Der Domainname ist eng mit dem Registranten verbunden";
$lang['Logicboxes.domain.isAUWarranty'] = "Garantie";
$lang['Logicboxes.domain.isAUWarranty.true'] = "Mit der Übermittlung dieses Antrags bestätige ich, dass ich berechtigt bin, den in dieser Anwendung angegebenen Domainnamen zu führen, und dass alle in dieser Anwendung bereitgestellten Informationen wahr, vollständig und korrekt sind und in keiner Weise irreführend sind. Sollte sich später herausstellen, dass die Informationen nicht korrekt sind oder unvollständig, inkorrekt oder irreführend sind oder wenn dieser Antrag böswillig eingereicht wird, kann die Domain - Lizenz gekündigt werden und zu einem dauerhaften Verlust der Daten führen Verwendung des Domain-Namens.";
$lang['Logicboxes.domain.RegistrantNexus'] = "Anmelder-Typ";
$lang['Logicboxes.domain.RegistrantNexus.c11'] = "US-Bürger";
$lang['Logicboxes.domain.RegistrantNexus.c12'] = "Ständiger Wohnsitz in der USA";
$lang['Logicboxes.domain.RegistrantNexus.c21'] = "US-Unternehmen oder Organisation";
$lang['Logicboxes.domain.RegistrantNexus.c31'] = "

Ausländische Organisation
";
$lang['Logicboxes.domain.RegistrantNexus.c32'] = "Ausländische Organisation mit einem Büro in den USA";
$lang['Logicboxes.domain.RegistrantPurpose'] = "Grund";
$lang['Logicboxes.domain.RegistrantPurpose.p1'] = "Geschäft";
$lang['Logicboxes.domain.RegistrantPurpose.p2'] = "Gemeinnützig";
$lang['Logicboxes.domain.RegistrantPurpose.p3'] = "Persönliche";
$lang['Logicboxes.domain.RegistrantPurpose.p4'] = "Bildungsbereich";
$lang['Logicboxes.domain.RegistrantPurpose.p5'] = "Regierung";
$lang['Logicboxes.domain.EUAgreeWhoisPolicy'] = "Whois Policy";
$lang['Logicboxes.domain.EUAgreeWhoisPolicy.yes'] = "Ich stimme hiermit zu, dass die Kanzlei berechtigt ist, die in dieser Anmeldung enthaltenen Daten an Dritte weiterzugeben (i), wenn sie von einer öffentlichen Stelle dazu aufgefordert werden, ihre rechtmäßigen Aufgaben wahrzunehmen; und (ii) auf Verlangen eines ADR-Anbieters wie in Abschnitt 16 der Allgemeinen Geschäftsbedingungen beschrieben, die auf www.eurid.eu veröffentlicht sind; und (iii) wie in Abschnitt 2 (WHOIS-Nachschlageinrichtung) der .eu Domain Name WHOIS-Richtlinie, die auf www.eurid.eu veröffentlicht ist, vorgesehen ist.";
$lang['Logicboxes.domain.EUAgreeDeletePolicy.yes'] = "

Ich stimme den besonderen Verlängerungs- und Ablaufbedingungen für diesen Domainnamen, einschließlich der in der Registrierungsvereinbarung festgelegten Bedingungen, zu und stimme ihnen zu. Ich verstehe, dass, wenn ich diese Domäne nicht für die automatische Verlängerung festgelegt habe, dieser Domänenname bis zum Ablaufdatum oder bis zum 20. des Verfallsmonats explizit erneuert werden muss, je nachdem, welcher Zeitpunkt früher liegt. (Wenn beispielsweise der Name am 4. September 2008 abläuft, muss eine manuelle Erneuerung bis zum 4. September 2008 eingehen. Wenn der Name am 27. September 2008 abläuft, muss der Antrag auf Erneuerung vor dem 20. September 2008 eingehen.). Wenn der Name nicht manuell erneuert wird oder zuvor auf automatische Aktualisierung gesetzt wurde, wird eine Löschanforderung von Logicboxes ausgegeben. Wenn eine Löschanforderung ausgegeben wird, ist der Name bis zu seinem Ablauf in meinem Konto voll funktionsfähig, kann jedoch nicht mehr erneuert werden, und ich kann keine Änderungen am Namen vornehmen. Diese Bedingungen können sich ändern.
";
$lang['Logicboxes.domain.CIRALegalType'] = "Gesetzlicher Typ";
$lang['Logicboxes.domain.RegistrantPurpose.cco'] = "Konzern";
$lang['Logicboxes.domain.RegistrantPurpose.cct'] = "Kanadischer Bürger";
$lang['Logicboxes.domain.RegistrantPurpose.res'] = "Kanadischer Einwohner";
$lang['Logicboxes.domain.RegistrantPurpose.gov'] = "Regierungsinstanz";
$lang['Logicboxes.domain.RegistrantPurpose.edu'] = "Bildung";
$lang['Logicboxes.domain.RegistrantPurpose.ass'] = "Nicht eingetragener Verein";
$lang['Logicboxes.domain.RegistrantPurpose.hop'] = "Krankenhaus";
$lang['Logicboxes.domain.RegistrantPurpose.prt'] = "Partnerschaft";
$lang['Logicboxes.domain.RegistrantPurpose.tdm'] = "Warenzeichen";
$lang['Logicboxes.domain.RegistrantPurpose.trd'] = "

Gewerkschaft
";
$lang['Logicboxes.domain.RegistrantPurpose.plt'] = "Partei";
$lang['Logicboxes.domain.RegistrantPurpose.lam'] = "Bibliotheken, Archive und Museen";
$lang['Logicboxes.domain.RegistrantPurpose.trs'] = "Vertrauen";
$lang['Logicboxes.domain.RegistrantPurpose.abo'] = "Ureinwohnervölker";
$lang['Logicboxes.domain.RegistrantPurpose.inb'] = "

Indische Band
";
$lang['Logicboxes.domain.RegistrantPurpose.lgr'] = "Gesetzlicher Vertreter";
$lang['Logicboxes.domain.RegistrantPurpose.omk'] = "Offizielle Marke";
$lang['Logicboxes.domain.RegistrantPurpose.maj'] = "Die Königin";
$lang['Logicboxes.domain.CIRAWhoisDisplay'] = "Wer ist";
$lang['Logicboxes.domain.CIRAWhoisDisplay.full'] = "Veröffentlichen";
$lang['Logicboxes.domain.CIRAWhoisDisplay.private'] = "Privat halten ";
$lang['Logicboxes.domain.COUKLegalType'] = "

Gesetzlicher Typ
";
$lang['Logicboxes.domain.COUKLegalType.ind'] = "UK Einzelperson";
$lang['Logicboxes.domain.COUKLegalType.find'] = "Nicht-UK-Individuum";
$lang['Logicboxes.domain.COUKLegalType.ltd'] = "UK Limited Company";
$lang['Logicboxes.domain.COUKLegalType.plc'] = "Britische Aktiengesellschaft";
$lang['Logicboxes.domain.COUKLegalType.ptnr'] = "UK-Partnerschaft";
$lang['Logicboxes.domain.COUKLegalType.llp'] = "UK Limited Liability Partnership";
$lang['Logicboxes.domain.COUKLegalType.ip'] = "UK Industrial / Provident Eingetragene Firma";
$lang['Logicboxes.domain.COUKLegalType.stra'] = "UK Einzelunternehmer";
$lang['Logicboxes.domain.COUKLegalType.sch'] = "GB Schule";
$lang['Logicboxes.domain.COUKLegalType.rchar'] = "UK registrierte Wohltätigkeitsorganisation";
$lang['Logicboxes.domain.COUKLegalType.gov'] = "Britischen Regierung Körper";
$lang['Logicboxes.domain.COUKLegalType.other'] = "UK Entität (andere)";
$lang['Logicboxes.domain.COUKLegalType.crc'] = "UK Corporation von Royal Charter";
$lang['Logicboxes.domain.COUKLegalType.fcorp'] = "Ausländische Organisation";
$lang['Logicboxes.domain.COUKLegalType.stat'] = "UK Statutory Body FIND";
$lang['Logicboxes.domain.COUKLegalType.fother'] = "Andere ausländische Organisationen";
$lang['Logicboxes.domain.COUKCompanyID'] = "Firmen-ID-Nummer";
$lang['Logicboxes.domain.COUKRegisteredfor'] = "

Name des Registranten
";
$lang['Logicboxes.domain.MEUKLegalType'] = "Gesetzlicher Typ";
$lang['Logicboxes.domain.MEUKLegalType.ind'] = "UK Einzelperson";
$lang['Logicboxes.domain.MEUKLegalType.find'] = "Nicht-UK-Person";
$lang['Logicboxes.domain.MEUKLegalType.ltd'] = "

UK Limited Company
";
$lang['Logicboxes.domain.MEUKLegalType.plc'] = "UK Public Limited Company";
$lang['Logicboxes.domain.MEUKLegalType.ptnr'] = "

Britische Partnerschaft
";
$lang['Logicboxes.domain.MEUKLegalType.llp'] = "Partnerschaft mit beschränkter Haftung im Vereinigten Königreich";
$lang['Logicboxes.domain.MEUKLegalType.ip'] = "UK Industrial / Provident Eingetragene Firma";
$lang['Logicboxes.domain.MEUKLegalType.stra'] = "UK Einzelhändler";
$lang['Logicboxes.domain.MEUKLegalType.sch'] = "UK Schule";
$lang['Logicboxes.domain.MEUKLegalType.rchar'] = "In Großbritannien eingetragene Wohltätigkeitsorganisation";
$lang['Logicboxes.domain.MEUKLegalType.gov'] = "UK Government Body";
$lang['Logicboxes.domain.MEUKLegalType.other'] = "UK Entity (andere)";
$lang['Logicboxes.domain.MEUKLegalType.crc'] = "UK Corporation von Royal Charter";
$lang['Logicboxes.domain.MEUKLegalType.fcorp'] = "Ausländische Organisation";
$lang['Logicboxes.domain.MEUKLegalType.stat'] = "UK Gesetzliche Einrichtung FIND";
$lang['Logicboxes.domain.MEUKLegalType.fother'] = "Andere ausländische Organisationen";
$lang['Logicboxes.domain.MEUKCompanyID'] = "Firmennummer";
$lang['Logicboxes.domain.MEUKRegisteredfor'] = "

Name des Registranten
";
$lang['Logicboxes.domain.ORGUKLegalType'] = "

Gesetzlicher Typ
";
$lang['Logicboxes.domain.ORGUKLegalType.ind'] = "UK-Individuum";
$lang['Logicboxes.domain.ORGUKLegalType.find'] = "Nicht-UK-Individuum";
$lang['Logicboxes.domain.ORGUKLegalType.ltd'] = "

UK Limited Company
";
$lang['Logicboxes.domain.ORGUKLegalType.plc'] = "Britische Aktiengesellschaft";
$lang['Logicboxes.domain.ORGUKLegalType.ptnr'] = "UK-Partnerschaft";
$lang['Logicboxes.domain.ORGUKLegalType.llp'] = "UK Limited Liability Partnership";
$lang['Logicboxes.domain.ORGUKLegalType.ip'] = "UK Industrial / Provident Eingetragene Firma";
$lang['Logicboxes.domain.ORGUKLegalType.stra'] = "

Einziger Händler in Großbritannien
";
$lang['Logicboxes.domain.ORGUKLegalType.sch'] = "Britische Schule";
$lang['Logicboxes.domain.ORGUKLegalType.rchar'] = "

In Großbritannien eingetragene Wohltätigkeitsorganisation
";
$lang['Logicboxes.domain.ORGUKLegalType.gov'] = "

Britische Regierungsbehörde
";
$lang['Logicboxes.domain.ORGUKLegalType.other'] = "

UK Entität (andere)
";
$lang['Logicboxes.domain.ORGUKLegalType.crc'] = "UK Corporation von Royal Charter";
$lang['Logicboxes.domain.ORGUKLegalType.fcorp'] = "Ausländische Organisation";
$lang['Logicboxes.domain.ORGUKLegalType.stat'] = "UK Gesetzliche Einrichtung FIND";
$lang['Logicboxes.domain.ORGUKLegalType.fother'] = "Andere ausländische Organisationen";
$lang['Logicboxes.domain.ORGUKCompanyID'] = "Firmennummer";
$lang['Logicboxes.domain.ORGUKRegisteredfor'] = "Name des Registranten";
$lang['Logicboxes.domain.ASIALegalEntityType'] = "Gesetzlicher Typ";
$lang['Logicboxes.domain.ASIALegalEntityType.corporation'] = "Unternehmen oder Unternehmen";
$lang['Logicboxes.domain.ASIALegalEntityType.cooperative'] = "Genossenschaften";
$lang['Logicboxes.domain.ASIALegalEntityType.partnership'] = "Partnerschaften oder Kollektive";
$lang['Logicboxes.domain.ASIALegalEntityType.government'] = "Regierungsstellen";
$lang['Logicboxes.domain.ASIALegalEntityType.politicalParty'] = "Politische Parteien oder Gewerkschaften";
$lang['Logicboxes.domain.ASIALegalEntityType.society'] = "Trusts, Estates, Verbände oder Gesellschaften";
$lang['Logicboxes.domain.ASIALegalEntityType.institution'] = "Institutionen";
$lang['Logicboxes.domain.ASIALegalEntityType.naturalPerson'] = "Natürliche Personen";
$lang['Logicboxes.domain.ASIAIdentForm'] = "Form der Identität";
$lang['Logicboxes.domain.ASIAIdentForm.certificate'] = "Gründungsurkunde";
$lang['Logicboxes.domain.ASIAIdentForm.legislation'] = "Charta";
$lang['Logicboxes.domain.ASIAIdentForm.societyRegistry'] = "Gesellschaften Registry";
$lang['Logicboxes.domain.ASIAIdentForm.politicalPartyRegistry'] = "Parteiliches Register";
$lang['Logicboxes.domain.ASIAIdentForm.passport'] = "

Reisepass-/Staatsangehörigkeitsausweis
";
$lang['Logicboxes.domain.ASIAIdentNumber'] = "Identifikationsnummer";
$lang['Logicboxes.tab_unavailable.message'] = "Diese Informationen sind noch nicht verfügbar.";
$lang['Logicboxes.domain.EUAgreeDeletePolicy'] = "Löschregeln";
$lang['Logicboxes.!tooltip.row_meta.sandbox'] = "

Wenn Sandbox aktiviert ist, müssen Sie die Anmeldeinformationen für Test- / Demo-Konten definieren. Wenn Sie Ihre Produktionskonto-Anmeldeinformationen mit aktivierter Sandbox verwenden, werden weiterhin Live-Aktionen ausgeführt.
";
$lang['Logicboxes.managewhois.contact_transfer'] = "Es wurde ein neuer Kontakt mit den angegebenen Details erstellt, und der Vorgang zum Übertragen der Domäne an diesen Kontakt wurde gestartet. Diese Aktion muss sowohl vom aktuellen Kontakt als auch vom neuen Kontakt bestätigt werden, bevor er wirksam wird.";
$lang['Logicboxes.description'] = "LogicBoxes ist ein Domain-Registrar.";
?>