<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 7.7.7
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Automation.task.autodebit.charge_failed'] = "Die Zahlung kann nicht verarbeitet werden.";
$lang['Automation.task.autodebit.charge_success'] = "Die Zahlung wurde erfolgreich verarbeitet.";
?>