<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Automation.task.card_expiration_reminders.success'] = "Erfolgreiche Zustellung der Ablauferinnerung für den Kontakt %1\$s %2\$s von Kunde #%3\$s."; // %1$s is the contact's first name, %2$s is the contact's last name, %3$s is the client ID
?>