<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Automation.task.cleanup_logs.logs_messenger_deleted'] = "%1\$s alte Messenger-Logs wurden gelöscht."; // %1$s is the number of logs deleted
$lang['Automation.task.cleanup_logs.logs_cron_deleted'] = "%1\$s alte Cron-Logs wurden gelöscht."; // %1$s is the number of logs deleted
?>