<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Automation.task.create_invoices.recurring_invoice_success'] = "Erfolgreich eine neue Rechnung aus der wiederkehrenden Rechnung #%1\$s für den Kunden #%2\$s erstellt."; // %1$s is the recurring invoice number, %2$s is the client ID
?>