<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Automation.task.deliver_invoices.delivery_error'] = "Aufgrund eines Fehlers können %3\$s Rechnungen nicht an Kunden #%1\$s über Versandart %2\$s übermittelt werden: Fehler %4\$s"; // %1$s is the client ID, %2$s is the invoice delivery method used, %3$s is the number of invoices that failed to be delivered, %4$s is the error message
?>