<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Automation.task.process_renewing_services.completed'] = "Die Aufgabe zur Verlängerung der Dienste ist abgeschlossen.";
$lang['Automation.task.process_renewing_services.renew_success'] = "Verlängerter Dienst #%1\$s für Kunde %2\$s."; // %1$s is the service ID, %2$s is the client ID
?>