<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientMain.index.page_title'] = "Dokumente";
$lang['ClientMain.index.boxtitle_documents'] = "Dokumente";
$lang['ClientMain.index.no_results'] = "Es sind keine Dokumente zum Download verfügbar.";
$lang['ClientMain.index.heading_name'] = "Name";
$lang['ClientMain.index.heading_description'] = "Beschreibung";
$lang['ClientMain.index.heading_date_added'] = "Hinzugefügt am";
$lang['ClientMain.index.heading_options'] = "Optionen";
$lang['ClientMain.index.option_download'] = "Download";
?>