<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientDocumentsFiles.!error.client_id.exists'] = "

Der Kunde existiert nicht.
";
$lang['ClientDocumentsFiles.!error.name.valid'] = "

Ein Dokumentenname ist erforderlich.
";
$lang['ClientDocumentsFiles.!error.date_added.valid'] = "Ein gültiges Hinzugefügt-Datum ist erforderlich.";
?>