<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Checkout.index.header_checkout'] = "Auschecken";
$lang['Checkout.index.header_paymethod'] = "Wählen Sie Ihre Zahlungsmethode";
$lang['Checkout.index.field_useaccount'] = "Zahlungskonto verwenden";
$lang['Checkout.index.field_newdetails'] = "

Neue Zahlungsdetails
";
$lang['Checkout.index.heading_other_payment_options'] = "

Andere Zahlungsmöglichkeiten
";
$lang['Checkout.index.heading_payment_options'] = "Zahlungsmöglichkeiten";
$lang['Checkout.index.apply_credit'] = "Guthaben anwenden (%1\$s verfügbar)"; // %1$s is the amount of credit available
$lang['Checkout.index.pay_btn'] = "

Bestellung abschicken
";
$lang['Checkout.index.pay_credit_btn'] = "

Gutschrift beantragen und Bestellung absenden
";
$lang['Checkout.index.continue_btn'] = "Weiter";
$lang['Checkout.index.no_options'] = "

Es sind keine Zahlungsmöglichkeiten verfügbar.
";
$lang['Checkout.contact_info.heading_contact'] = "Kontaktinformation";
$lang['Checkout.contact_info.field_contact_id'] = "Kontaktinformationen kopieren von";
$lang['Checkout.contact_info.text_select_contact'] = "

Sie können einen vorhandenen Kontakt auswählen, um dieses Formular vorab auszufüllen.
";
$lang['Checkout.cc_info.heading_cc'] = "Kreditkarteninformation";
$lang['Checkout.ach_info.heading_ach'] = "Bankkonto Information";
$lang['Checkout.complete.header_complete'] = "Bestellung ausgeführt";
$lang['Checkout.complete.header_almost_complete'] = "Fast dort...";
$lang['Checkout.complete.order_more_btn'] = "Legen Sie eine andere Reihenfolge an";
?>