<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Main.steps.step_1_name'] = "Schritt 1";
$lang['Main.steps.step_1_description'] = "

Wähle deinen Plan
";
$lang['Main.steps.step_2_name'] = "

Schritt 2
";
$lang['Main.steps.step_2_description'] = "Aufbau";
$lang['Main.steps.step_3_name'] = "

Schritt 3
";
$lang['Main.steps.step_3_description'] = "

Bestellung überprüfen
";
$lang['Main.steps.step_4_name'] = "Schritt 4";
$lang['Main.steps.step_4_description'] = "Auschecken";
$lang['Main.index.select_btn'] = "in den Warenkorb legen";
$lang['Main.index.sold_out'] = "Ausverkauft";
$lang['Main.index.client_limit'] = "Limit erreicht";
$lang['Main.index.field_currency'] = "Währung:";
?>