<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Summary.index.box_heading'] = "Ihr Einkaufswagen";
$lang['Summary.index.login_customer'] = "Bestehender Kunde?";
$lang['Summary.index.login_link'] = "Anmeldung";
$lang['Summary.index.link_resetpassword'] = "Setze mein Passwort zurück";
$lang['Summary.index.field_username'] = "Nutzername";
$lang['Summary.index.field_password'] = "Passwort";
$lang['Summary.index.login_btn'] = "Anmeldung";
$lang['Summary.index.checkout_btn'] = "Auschecken";
$lang['Summary.index.have_coupon'] = "Haben Sie einen Gutschein?";
$lang['Summary.index.coupon'] = "Coupon";
$lang['Summary.index.coupon_btn'] = "Einlösen";
$lang['Summary.index.cart_empty'] = "Es befinden sich keine Artikel in Ihrem Einkaufswagen.";
?>