<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Package.!error.meta[pricing_id].format'] = "

Bitte wählen Sie eine gültige Lizenz aus.
";
$lang['BlestaLicense.module_row.name'] = "Verkäufer";
$lang['BlestaLicense.module_rows.name'] = "Wiederverkäufer";
$lang['BlestaLicense.add_module_row'] = "Reseller hinzufügen";
$lang['BlestaLicense.manage.module_rows_title'] = "Resellers";
$lang['BlestaLicense.manage.module_rows_heading.username'] = "Nutzername";
$lang['BlestaLicense.manage.module_rows_heading.options'] = "Optionen";
$lang['BlestaLicense.manage.module_rows.edit'] = "Bearbeiten";
$lang['BlestaLicense.manage.module_rows.delete'] = "Entfernen";
$lang['BlestaLicense.manage.module_rows.confirm_delete'] = "Möchten Sie diesen Reseller wirklich löschen?";
$lang['BlestaLicense.manage.module_rows_no_results'] = "Es gibt keine Reseller.";
$lang['BlestaLicense.!tooltip.username'] = "Geben Sie Ihren Benutzernamen für den Blesta-Account ein.";
$lang['BlestaLicense.!tooltip.password'] = "Geben Sie Ihr Passwort für das Blesta-Konto ein.";
$lang['BlestaLicense.row_meta.username'] = "Nutzername";
$lang['BlestaLicense.row_meta.password'] = "Passwort";
$lang['BlestaLicense.row_meta.test_mode'] = "Testmodus";
$lang['BlestaLicense.add_row.box_title'] = "Reseller hinzufügen";
$lang['BlestaLicense.add_row.basic_title'] = "Grundeinstellungen";
$lang['BlestaLicense.add_row.add_btn'] = "

Reseller hinzufügen
";
$lang['BlestaLicense.edit_row.box_title'] = "Reseller bearbeiten";
$lang['BlestaLicense.edit_row.basic_title'] = "Grundeinstellungen";
$lang['BlestaLicense.edit_row.edit_btn'] = "Reseller bearbeiten";
$lang['Package.getpricings.pricing_id'] = "%1\$s (ID %2\$s)"; // %1$s is the package name, %2$s is the package pricing ID
$lang['Package.package_fields.pricing_id'] = "Lizenz";
$lang['BlestaLicense.tab_reissue'] = "

Lizenz verlängern";
$lang['BlestaLicense.tab_reissue.heading_reissue'] = "Verlängern";
$lang['BlestaLicense.tab_reissue.description'] = "Wenn die Lizenz zurückgesetzt wird, kann sie neu installiert, oder an einem anderen Server freigeschaltet werden.";
$lang['BlestaLicense.tab_reissue.field_submit'] = "Neuausgabe";
?>