<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Option.description.option.item_qty.added.date'] = "Addition von %1\$s - %3\$sx %2\$s (%4\$s - %5\$s)"; // %1$s is the package option label, %2$s is the package option name, %3$s is the package option quantity, %4$s is the start date, %5$s is the end date
$lang['Option.description.option.item.removed.text'] = "Entfernen von %1\$s"; // %1$s is the package option label
$lang['Option.description.option.item.updated.date.text'] = "Änderung von %1\$s (%2\$s - %3\$s)"; // %1$s is the package option label, %2$s is the start date, %3$s is the end date
$lang['Option.description.option.item.added.prorated.date'] = "Anteilige Addition von %1\$s - %2\$s (%3\$s - %4\$s)"; // %1$s is the package option label, %2$s is the package option name, %3$s is the prorated start date, %4$s is the prorated end date
$lang['Option.description.option.item.removed.prorated'] = "Anteilige Entfernung von %1\$s - %2\$s"; // %1$s is the package option label, %2$s is the package option name
$lang['Option.description.option.item.removed.prorated.date.text'] = "Anteilige Entfernung von %1\$s (%2\$s - %3\$s)"; // %1$s is the package option label, %2$s is the prorated start date, %3$s is the prorated end date
$lang['Option.description.option.item_qty.removed.prorated'] = "Anteilige Entfernung von %1\$s - %3\$sx %2\$s"; // %1$s is the package option label, %2$s is the package option name, %3$s is the package option quantity
$lang['Option.description.option.item.updated.prorated'] = "Anteiliger Wechsel von %1\$s von %3\$s zu %2\$s"; // %1$s is the package option label, %2$s is the package option name, %3$s is the old package option name
$lang['Option.description.option.item.updated.prorated.text'] = "Anteilige Änderung von %1\$s"; // %1$s is the package option label
?>