<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Service.description.service.cancel'] = "%1\$s - %2\$s Stornierungsgebühr"; // %1$s is the name of the package, %2$s is the name of the service
$lang['Service.description.package.cancel'] = "%1\$s Stornierungsgebühr"; // %1$s is the name of the package
$lang['Service.description.package.item.prorate'] = "Anteilig %1\$s (%2\$s - %3\$s)"; // %1$s is the name of the package, %2$s is the prorated start date, %3$s is the prorated end date
?>