<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['TransactionsApplied.name'] = "Transaktionen angewendet";
$lang['TransactionsApplied.option.any'] = "irgendein / jeder";
$lang['TransactionsApplied.options.field_start_date'] = "Anfangsdatum";
$lang['TransactionsApplied.options.field_end_date'] = "Endtermin";
$lang['TransactionsApplied.options.field_gateway'] = "Tor";
$lang['TransactionsApplied.options.field_status'] = "Status";
$lang['TransactionsApplied.options.field_payment_type'] = "Zahlungsart";
$lang['TransactionsApplied.heading.id'] = "Transaktionen #";
$lang['TransactionsApplied.heading.transaction_id'] = "Transaktions-ID";
$lang['TransactionsApplied.heading.reference_id'] = "Referenz ID";
$lang['TransactionsApplied.heading.client_id_code'] = "Kunde #";
$lang['TransactionsApplied.heading.invoice_id_code'] = "Rechnungsnummer #";
$lang['TransactionsApplied.heading.gateway_name'] = "Zahlungs-Gateways";
$lang['TransactionsApplied.heading.type_name'] = "Zahlungsart";
$lang['TransactionsApplied.heading.applied_amount'] = "Angewendeter Betrag";
$lang['TransactionsApplied.heading.amount'] = "Zahlungsbetrag";
$lang['TransactionsApplied.heading.currency'] = "Währung";
$lang['TransactionsApplied.heading.status'] = "Status";
$lang['TransactionsApplied.heading.applied_date'] = "Antragsdatum";
$lang['TransactionsApplied.heading.income_type'] = "Art der Transaktion";
?>