<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CmsPages.!error.uri.empty'] = "Bitte geben Sie den URI-Pfad zur Seite ein.";
$lang['CmsPages.!error.company_id.exists'] = "Ungültige Unternehmens-ID.";
$lang['CmsPages.!error.title.empty'] = "Bitte geben Sie einen Seitentitel ein.";
$lang['CmsPages.!error.content.valid'] = "Fehler beim parsen des Inhalts: %1\$s"; // %1$s is the parse error
?>