<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CmsManagePlugin.!success.plugin_updated'] = "Das Portal wurde erfolgreich aktualisiert.";
$lang['CmsManagePlugin.index.page_title'] = "Portal > Verwalten";
$lang['CmsManagePlugin.index.boxtitle_portal'] = "Portal";
$lang['CmsManagePlugin.index.field_title'] = "Index Seitentitel";
$lang['CmsManagePlugin.index.field_tags'] = "Verfügbare Tags";
$lang['CmsManagePlugin.index.field_content'] = "Inhalt der Indexseite";
$lang['CmsManagePlugin.index.field_submit'] = "Seite aktualisieren";
?>