<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Domain.description.domain.item.prorate'] = "Anteilig %1\$s - %2\$s (%3\$s - %4\$s)"; // %1$s is the name of the tld, %2$s is the name of the domain, %3$s is the prorated start date, %4$s is the prorated end date
$lang['Domain.description.package.setup'] = "%1\$s Einrichtungsgebühr"; // %1$s is the name of the tld
$lang['Domain.description.package.item.updated.prorate'] = "Anteilige Änderung von %1\$s zu %2\$s (%3\$s - %4\$s)"; // %1$s is the name of the old package, %2$s is the name of the tld, %3$s is the prorated start date, %4$s is the prorated end date
?>