<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Blue_pay.!error.account_id.empty'] = "Bitte geben Sie Ihre Kontonummer ein.";
$lang['Blue_pay.!error.secret_key.empty'] = "Bitte geben Sie Ihren geheimen Schlüssel an.";
$lang['Blue_pay.!error.test_mode.valid'] = "Testmodus muss auf \"wahr\" gesetzt sein.";
$lang['Blue_pay.name'] = "BluePay";
$lang['Blue_pay.account_id'] = "Account ID";
$lang['Blue_pay.secret_key'] = "Secret Key";
$lang['Blue_pay.test_mode'] = "Testmodus";
$lang['Blue_pay.description'] = "BluePay offers fast, easy, and secure payment processing solutions to fit every merchant's needs. Operates in North America";
?>