<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Centoswebpanel.name'] = "

CentOS WebPanel
";
$lang['Centoswebpanel.module_row'] = "Server";
$lang['Centoswebpanel.module_row_plural'] = "Server";
$lang['Centoswebpanel.module_group'] = "Servergruppe";
$lang['Centoswebpanel.add_module_row'] = "

Server hinzufügen
";
$lang['Centoswebpanel.add_module_group'] = "

Servergruppe hinzufügen
";
$lang['Centoswebpanel.manage.module_rows_title'] = "Server";
$lang['Centoswebpanel.manage.module_groups_title'] = "Servergruppen";
$lang['Centoswebpanel.manage.module_rows_heading.name'] = "Serverkennzeichnung";
$lang['Centoswebpanel.manage.module_rows_heading.hostname'] = "Hostname";
$lang['Centoswebpanel.manage.module_rows_heading.accounts'] = "Konten";
$lang['Centoswebpanel.manage.module_rows_heading.options'] = "Optionen";
$lang['Centoswebpanel.manage.module_groups_heading.name'] = "Gruppenname";
$lang['Centoswebpanel.manage.module_groups_heading.servers'] = "Serveranzahl";
$lang['Centoswebpanel.manage.module_groups_heading.options'] = "Optionen";
$lang['Centoswebpanel.manage.module_rows.count'] = "%1\$s/%2\$s"; // %1$s is the current number of accounts, %2$s is the total number of accounts available
$lang['Centoswebpanel.manage.module_rows.edit'] = "Bearbeiten";
$lang['Centoswebpanel.manage.module_groups.edit'] = "Bearbeiten";
$lang['Centoswebpanel.manage.module_rows.delete'] = "

Löschen
";
$lang['Centoswebpanel.manage.module_groups.delete'] = "Löschen";
$lang['Centoswebpanel.manage.module_rows.confirm_delete'] = "Möchten Sie diesen Server wirklich löschen?";
$lang['Centoswebpanel.manage.module_groups.confirm_delete'] = "

Möchten Sie diese Servergruppe wirklich löschen?
";
$lang['Centoswebpanel.manage.module_rows_no_results'] = "

Es gibt keine Server.
";
$lang['Centoswebpanel.manage.module_groups_no_results'] = "Es gibt keine Servergruppen.";
$lang['Centoswebpanel.order_options.first'] = "Erster nicht voller Server";
$lang['Centoswebpanel.order_options.roundrobin'] = "Gleichmäßig unter Servern verteilen";
$lang['Centoswebpanel.add_row.box_title'] = "CentOS WebPanel Server hinzufügen";
$lang['Centoswebpanel.add_row.basic_title'] = "Grundeinstellungen";
$lang['Centoswebpanel.add_row.name_servers_title'] = "Name Server";
$lang['Centoswebpanel.add_row.notes_title'] = "Anmerkungen";
$lang['Centoswebpanel.add_row.name_server_btn'] = "Fügen Sie zusätzlichen Namenserver hinzu";
$lang['Centoswebpanel.add_row.name_server_col'] = "Name Server";
$lang['Centoswebpanel.add_row.name_server_host_col'] = "Hostname";
$lang['Centoswebpanel.add_row.name_server'] = "Namenserver %1\$s"; // %1$s is the name server number (e.g. 3)
$lang['Centoswebpanel.add_row.remove_name_server'] = "Löschen";
$lang['Centoswebpanel.add_row.add_btn'] = "Server hinzufügen";
$lang['Centoswebpanel.edit_row.box_title'] = "Bearbeiten Sie CentOS WebPanel Server";
$lang['Centoswebpanel.edit_row.basic_title'] = "Grundeinstellungen";
$lang['Centoswebpanel.edit_row.name_servers_title'] = "Namenserver";
$lang['Centoswebpanel.edit_row.notes_title'] = "Notizen";
$lang['Centoswebpanel.edit_row.name_server_btn'] = "Weiteren Namenserver hinzufügen";
$lang['Centoswebpanel.edit_row.name_server_col'] = "Name Server";
$lang['Centoswebpanel.edit_row.name_server_host_col'] = "Hostname";
$lang['Centoswebpanel.edit_row.name_server'] = "Namenserver %1\$s"; // %1$s is the name server number (e.g. 3)
$lang['Centoswebpanel.edit_row.remove_name_server'] = "Löschen";
$lang['Centoswebpanel.edit_row.add_btn'] = "Server bearbeiten";
$lang['Centoswebpanel.row_meta.server_name'] = "

Server-Kennzeichnung
";
$lang['Centoswebpanel.row_meta.host_name'] = "Hostname";
$lang['Centoswebpanel.row_meta.api_key'] = "

API-Schlüssel
";
$lang['Centoswebpanel.row_meta.use_ssl'] = "Verwenden Sie SSL, wenn Sie eine Verbindung zur API herstellen (empfohlen)";
$lang['Centoswebpanel.row_meta.account_limit'] = "Kontolimit";
$lang['Centoswebpanel.package_fields.package'] = "

Paket-ID
";
$lang['Centoswebpanel.package_fields.inode'] = "

Maximale Anzahl von Inodes
";
$lang['Centoswebpanel.package_fields.nofile'] = "

Maximale Dateien
";
$lang['Centoswebpanel.package_fields.nproc'] = "Maximaler Prozess";
$lang['Centoswebpanel.service_field.domain'] = "Domain";
$lang['Centoswebpanel.service_field.username'] = "Nutzername";
$lang['Centoswebpanel.service_field.password'] = "Passwort";
$lang['Centoswebpanel.service_info.username'] = "Nutzername";
$lang['Centoswebpanel.service_info.password'] = "Passwort";
$lang['Centoswebpanel.service_info.server'] = "Server";
$lang['Centoswebpanel.service_info.options'] = "Optionen";
$lang['Centoswebpanel.service_info.option_login'] = "Einloggen";
$lang['Centoswebpanel.service_field.tooltip.username'] = "

Sie können den Benutzernamen leer lassen, um automatisch einen zu erstellen.
";
$lang['Centoswebpanel.service_field.tooltip.password'] = "

Sie können das Passwort leer lassen, um es automatisch zu generieren.
";
$lang['Centoswebpanel.!error.server_name_valid'] = "

Sie müssen eine Server-Bezeichnung eingeben.
";
$lang['Centoswebpanel.!error.host_name_valid'] = "Der Hostname scheint ungültig zu sein.";
$lang['Centoswebpanel.!error.user_name_valid'] = "Der Benutzername scheint ungültig zu sein.";
$lang['Centoswebpanel.!error.remote_api_key_valid'] = "

Der API-Schlüssel scheint ungültig zu sein.
";
$lang['Centoswebpanel.!error.remote_api_key_valid_connection'] = "Eine Verbindung zum Server konnte nicht hergestellt werden. Überprüfen Sie, ob der Hostname und der API-Schlüssel korrekt sind.";
$lang['Centoswebpanel.!error.account_limit_valid'] = "

Das Kontolimit muss leer sein (für unbegrenzte Konten) oder auf einen ganzzahligen Wert gesetzt werden.
";
$lang['Centoswebpanel.!error.name_servers_valid'] = "Einer oder mehrere der eingegebenen Nameserver sind ungültig.";
$lang['Centoswebpanel.!error.name_servers_count'] = "

Sie müssen mindestens 2 Namenserver definieren.
";
$lang['Centoswebpanel.!error.meta[package].empty'] = "Ein CentOS WebPanel-Paket ist erforderlich.";
$lang['Centoswebpanel.!error.meta[inode].valid'] = "

Die maximalen Inodes müssen ein numerischer Wert sein.
";
$lang['Centoswebpanel.!error.meta[nofile].valid'] = "Die maximale Anzahl an Dateien muss ein numerischer Wert sein.";
$lang['Centoswebpanel.!error.meta[nproc].valid'] = "

Die Maximalanzahl für Prozess muss eine Zahl sein.
";
$lang['Centoswebpanel.!error.api.internal'] = "Es ist ein interner Fehler aufgetreten oder der Server hat auf die Anforderung nicht geantwortet.";
$lang['Centoswebpanel.!error.module_row.missing'] = "Ein interner Fehler ist aufgetreten. Die Modulzeile ist nicht verfügbar.";
$lang['Centoswebpanel.!error.centoswebpanel_domain.format'] = "Bitte geben Sie einen gültigen Domainnamen ein, z.B. domain.com.";
$lang['Centoswebpanel.!error.centoswebpanel_domain.test'] = "Der Domänenname kann nicht mit \"test\" beginnen.";
$lang['Centoswebpanel.!error.centoswebpanel_username.format'] = "Der Benutzername darf nur Buchstaben und Zahlen enthalten und darf nicht mit einer Zahl beginnen.";
$lang['Centoswebpanel.!error.centoswebpanel_username.test'] = "

Der Benutzername darf nicht mit \"test\" beginnen.
";
$lang['Centoswebpanel.!error.centoswebpanel_username.length'] = "Der Benutzername muss zwischen 1 und 16 Zeichen lang sein.";
$lang['Centoswebpanel.!error.centoswebpanel_password.valid'] = "Das Passwort muss mindestens 8 Zeichen lang sein.";
$lang['Centoswebpanel.!error.centoswebpanel_password.matches'] = "Passwort und Passwortbestätigung stimmen nicht überein.";
?>