<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyEmails.templates.Phpids.email_alert_name'] = "PHPIDS Einbruchalarm";
$lang['AdminCompanyEmails.templates.Phpids.email_alert_desc'] = "PHPIDS Intrusion-Dection-Alarm-E-Mail, gesendet an Adressen, die unter dem PHPIDS-Plugin konfiguriert wurden.";
?>