<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AgingInvoices.name'] = "Aging-Rechnungen";
$lang['AgingInvoices.options.field_status'] = "Status";
$lang['AgingInvoices.option.any'] = "Irgendein";
$lang['AgingInvoices.heading.id_code'] = "Rechnungs-Nummer:";
$lang['AgingInvoices.heading.client_id_code'] = "

Kunde #
";
$lang['AgingInvoices.heading.subtotal'] = "Zwischensumme";
$lang['AgingInvoices.heading.total'] = "Summe";
$lang['AgingInvoices.heading.paid'] = "Bezahlt";
$lang['AgingInvoices.heading.currency'] = "Stand";
$lang['AgingInvoices.heading.status'] = "Status";
$lang['AgingInvoices.heading.date_billed'] = "Abrechnungsdatum";
$lang['AgingInvoices.heading.date_due'] = "Fälligkeitsdatum";
$lang['AgingInvoices.heading.past30'] = "30";
$lang['AgingInvoices.heading.past60'] = "60";
$lang['AgingInvoices.heading.past90'] = "

90+
";
$lang['AgingInvoices.heading.client_first_name'] = "Vorname des Kunden";
$lang['AgingInvoices.heading.client_last_name'] = "Name des Kunden";
$lang['AgingInvoices.heading.client_email'] = "E-Mail des Kunden";
$lang['AgingInvoices.heading.client_numbers'] = "Kunden Telefonnummern";
?>