<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['TransactionsReceived.name'] = "

Erhaltene Transaktionen
";
$lang['TransactionsReceived.option.any'] = "Andere";
$lang['TransactionsReceived.options.field_start_date'] = "Startdatum";
$lang['TransactionsReceived.options.field_end_date'] = "Enddatum";
$lang['TransactionsReceived.options.field_gateway'] = "Gateway";
$lang['TransactionsReceived.options.field_status'] = "Status";
$lang['TransactionsReceived.options.field_payment_type'] = "Zahlungsart";
$lang['TransactionsReceived.heading.id'] = "Transaktion #";
$lang['TransactionsReceived.heading.transaction_id'] = "

Transaktions-ID
";
$lang['TransactionsReceived.heading.reference_id'] = "

Referenz ID
";
$lang['TransactionsReceived.heading.client_id_code'] = "Klient #";
$lang['TransactionsReceived.heading.gateway_name'] = "Zahlungs-Gateway";
$lang['TransactionsReceived.heading.type_name'] = "Zahlungsart";
$lang['TransactionsReceived.heading.amount'] = "Zahlungsbetrag";
$lang['TransactionsReceived.heading.currency'] = "Währung";
$lang['TransactionsReceived.heading.status'] = "Status";
$lang['TransactionsReceived.heading.date_added'] = "Datum hinzugefügt ";
$lang['TransactionsReceived.heading.income_type'] = "Art der Transaktion";
?>