<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminDomains.!success.tld_added'] = "Die TLD wurde erfolgreich hinzugefügt!";
$lang['AdminDomains.browse.heading_registration'] = "Datum der Registrierung";
$lang['AdminDomains.browse.confirm_delete'] = "Sind Sie sicher, dass Sie diesen Domain Dienst löschen wollen?";
$lang['AdminDomains.browse.category_suspended'] = "Ausgesetzt";
$lang['AdminDomains.browse.tooltip_renew'] = "Automatische Erneuerung für Blesta bedeutet, dass dem Nutzer automatisch eine Rechnung gestellt wird und die Domain erneuert wird, sobald die Rechnung bezahlt ist.";
$lang['AdminDomains.configuration.tab_notifications'] = "Benachrichtigungen";
$lang['AdminDomains.configuration.field_second_reminder_days_before'] = "2nd Erneuerungs Benachrichtigung tage zuvor";
$lang['AdminDomains.configuration.tooltip_dns_management_option_group'] = "Die konfigurierbare Optionsgruppe, mit der gesteuert wird, ob eine Domain über DNS-Verwaltungsdienste verfügen soll.";
$lang['AdminDomains.configuration.tooltip_first_reminder_days_before'] = "Wähle die Anzahl an Tagen bevor eine Domain ausläuft um die erste Erneuerungsmail zu senden (26-35 per ICANN Standart). Nutze den E-Mail Template link um die Datei zu bearbeiten/deactivieren zu können.";
$lang['AdminDomains.importpackages.tooltip_migrate_services'] = "Wenn diese Option aktiviert ist, werden alle Leistungen, die den geklonten Paketen zugeordnet sind, auf die neu erstellten Pakete übertragen. Dies gilt nur für Leistungen mit einer jährlichen Preisperiode.";
$lang['AdminDomains.importpackages.field_overwrite_packages'] = "TLD-Pakete überschreiben";
$lang['AdminDomains.importpackages.field_submit'] = "Pakete importieren";
$lang['AdminDomains.tlds.heading_email_forwarding'] = "E-Mail-Weiterleitung";
$lang['AdminDomains.tlds.heading_module'] = "Modul";
$lang['AdminDomains.tlds.tooltip_id_protection'] = "Die Verfügbarkeit des ID-Schutzes hängt davon ab, ob das Registrierstellen-Modul diese Funktion implementiert, und ist möglicherweise nicht für alle TLDs oder Registrierstellen verfügbar.";
$lang['AdminDomains.tlds.tooltip_epp_code'] = "Die Verfügbarkeit des EPP-Codes hängt davon ab, ob das Registrierstellen-Modul diese Funktion implementiert und ist möglicherweise nicht für alle TLDs oder Registrierstellen verfügbar.";
$lang['AdminDomains.pricing.tab_nameservers'] = "Nameserver";
$lang['AdminDomains.pricing.heading_term'] = "Bezeichnung";
$lang['AdminDomains.pricing.text_advanced_options'] = "Bearbeiten Sie das Kernpaket, um Kundenlimits, konfigurierbare Optionen, verfügbare Mengen, Plugin-Integrationen, Beschreibungen und mehr zu definieren.";
$lang['AdminDomains.pricing.field_modulegroup_any'] = "Irgendeins";
$lang['AdminDomains.meta.field_continue'] = "Weiter";
$lang['AdminDomains.getDays.text_day'] = "%1\$s Tag"; // %1$s is the number of days
$lang['AdminDomains.getDays.text_days'] = "%1\$s Tage"; // %1$s is the number of days
$lang['AdminDomains.getOperators.earlier'] = "Früher";
$lang['AdminDomains.!warning.automatic_currency_conversion'] = "Sie haben einen Wechselkurs für diese Währung festgelegt, daher ist es nicht notwendig, hier Preise zu definieren. Wenn keine Preise für diese Währung definiert sind, wird die Währung automatisch aus %1\$s umgerechnet. Wenn Sie hier einen Preis definieren, wird dieser stattdessen verwendet."; // %1$s is the default currency
$lang['AdminDomains.browse.page_title'] = "Domains > Durchsuchen";
$lang['AdminDomains.configuration.tab_configurableoptions'] = "Konfigurierbare Optionen";
$lang['AdminDomains.configurableoptions.heading_configurable_option'] = "Konfigurierbare Optionen";
$lang['AdminDomains.configurableoptions_pricing.boxtitle_edit_configurable_option'] = "Bearbeiten von %1\$s";
$lang['AdminDomains.!success.change_status'] = "TLD-Zustände wurden erfolgreich aktualisiert!";
$lang['AdminDomains.getTldActions.option_tld_sync'] = "Registrar Price Sync";
$lang['AdminDomains.!success.tlds_imported'] = "Die TLDs sind erfolgreich importiert worden!";
$lang['AdminDomains.browse.heading_renewal'] = "Verlängerungsdatum";
$lang['AdminDomains.configuration.tooltip_renewal_days_before_expiration'] = "Wenn Domains in Rechnung gestellt werden, wird die Rechnung diese Anzahl von Tagen vor dem Ablaufdatum der Domain fällig.";
$lang['AdminDomains.import.title_terms'] = "Bedingungen";
$lang['AdminDomains.import.title_tlds'] = "TLDs";
$lang['AdminDomains.import.text_years'] = "%1\$s Jahre"; // %1$s is the number of years
?>