<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyEmails.templates.Domains.domain_renewal_1_desc'] = "Erste Mitteilung an einen Kunden, wenn seine Domain demnächst ausläuft.";
$lang['AdminCompanyEmails.templates.Domains.domain_expiration_desc'] = "Mitteilung an einen Kunden, kurz nachdem seine Domain abgelaufen ist.";
?>