<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientMain.index.category_active'] = "Aktiv";
$lang['ClientMain.index.heading_suspension_date'] = "Datum der Aussetzung";
$lang['ClientMain.index.heading_deletion_date'] = "Datum der Löschung";
$lang['ClientMain.index.heading_domain'] = "Domain";
$lang['ClientMain.serviceinfo.no_results'] = "Diese Domain hat keine Details.";
?>