<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DomainsFeed.getOptionFields.example_code_table'] = "Zeigt eine Tabelle mit den Preisen für alle TLDs in einer bestimmten Währung:";
$lang['DomainsFeed.getOptionFields.header_name'] = "Name";
$lang['DomainsFeed.getOptionFields.param_currency'] = "Währung";
$lang['DomainsFeed.getOptionFields.param_currency_description'] = "Der dreistellige Währungscode, für den die Preise abgerufen werden sollen.";
$lang['DomainsFeed.table.heading_year'] = "%1\$s Jahr"; // %1$s is the number of years
?>