<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Coingate.name'] = "CoinGate.com";
$lang['Coingate.app_id'] = "APP-ID";
$lang['Coingate.api_key'] = "API-Schlüssel";
$lang['Coingate.api_secret'] = "

API-Secret
";
$lang['Coingate.coingate_environment'] = "CoinGate-Umgebung";
$lang['Coingate.environment.sandbox'] = "Sandkasten";
$lang['Coingate.environment.live'] = "Leben";
$lang['Coingate.receive_currency'] = "Auszahlungswährung";
$lang['Coingate.receive_currency_note'] = "

Währung, die Sie beim Abheben bei CoinGate erhalten möchten. Bitte beachten Sie, dass Sie bei der Auswahl von EUR oder USD zur Bestätigung aufgefordert werden bevor Sie eine Auszahlung bei CoinGate vornehmen.
";
$lang['Coingate.environment_note'] = "Aktivieren Sie \"Sandbox\", um auf sandbox.coingate.com zu testen. Bitte beachten Sie, dass Sie für den Sandbox-Modus separate API-Anmeldeinformationen für sandbox.coingate.com erstellen müssen. Auf coingate.com generierte API-Anmeldeinformationen funktionieren nicht für den Sandbox-Modus.";
$lang['Coingate.buildprocess.submit'] = "CoinGate.com";
$lang['Coingate.receive_currency.usd'] = "US-Dollar \$";
$lang['Coingate.receive_currency.btc'] = "Bitcoin ?";
$lang['Coingate.receive_currency.eur'] = "Euro €";
$lang['Coingate.!error.app_id.empty'] = "Die APP-ID darf nicht leer sein.";
$lang['Coingate.!error.api_key.empty'] = "Der API-Schlüssel darf nicht leer sein";
$lang['Coingate.!error.api_secret.empty'] = "API Secret darf nicht leer sein";
$lang['Coingate.!error.payment.invalid'] = "Die Transaktion ist ungültig und konnte nicht verarbeitet werden.";
$lang['Coingate.!error.payment.canceled'] = "

Die Transaktion wird abgebrochen und konnte nicht verarbeitet werden.
";
$lang['Coingate.!error.payment.expired'] = "Die Transaktion ist abgelaufen und konnte nicht verarbeitet werden.";
$lang['Coingate.!error.failed.response'] = "Die Transaktion konnte nicht verarbeitet werden.";
?>