<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MulticraftService.!error.internal'] = "Ein interner Fehler ist aufgetreten oder der Server hat auf die Anfrage nicht geantwortet.";
$lang['MulticraftService.!error.client'] = "Es wurde kein Client gefunden, aus dem ein Multicraft-Benutzer erstellt werden könnte.";
$lang['MulticraftService.!error.server_id.format'] = "Die Server-ID muss eine ganze Zahl sein oder leer gelassen werden.";
$lang['MulticraftService.!error.user_id.format'] = "Die Benutzer-ID muss eine Ganzzahl oder leer sein.";
$lang['MulticraftService.!error.daemon_id.format'] = "Die Daemon-ID muss eine ganze Zahl sein oder leer gelassen werden.";
$lang['MulticraftService.!error.ip.format'] = "Bitte geben Sie eine gültige IP-Adresse ein oder lassen Sie sie leer.";
$lang['MulticraftService.!error.port.format'] = "Bitte geben Sie einen Gültigen Port an oder lassen Sie das Feld leer.";
$lang['MulticraftService.service_fields.server_id'] = "Server ID";
$lang['MulticraftService.service_fields.tooltip.server_id'] = "Legen Sie die eindeutige ID des Multicraft-Servers fest, dem dieser Service zugewiesen werden soll. Lassen Sie es ansonsten leer.";
$lang['MulticraftService.service_fields.user_id'] = "Benutzeridentifikation";
$lang['MulticraftService.service_fields.tooltip.user_id'] = "Legen Sie die eindeutige ID des Multicraft-Benutzers fest, dem dieser Service zugewiesen werden soll. Lassen Sie es ansonsten leer.";
$lang['MulticraftService.service_fields.daemon_id'] = "Daemon-ID";
$lang['MulticraftService.service_fields.tooltip.daemon_id'] = "Legen Sie die ID des Multicraft-Daemons fest, dem dieser Dienst zugewiesen werden soll. Lassen Sie es ansonsten leer.";
$lang['MulticraftService.service_fields.ip'] = "IP Adresse";
$lang['MulticraftService.service_fields.tooltip.ip'] = "Stellen Sie die IP-Adresse des Multicraft-Servers ein, dem dieser Service zugewiesen werden soll. Lassen Sie es ansonsten leer.";
$lang['MulticraftService.service_fields.port'] = "Port";
$lang['MulticraftService.service_fields.tooltip.port'] = "

Legen Sie den Port des Multicraft-Servers fest, dem dieser Dienst zugewiesen werden soll. Lassen Sie es ansonsten leer.
";
$lang['MulticraftService.service_fields.yes'] = "Ja";
$lang['MulticraftService.service_fields.no'] = "Nein";
$lang['MulticraftService.!error.configoptions[user_players].format'] = "Ob der Server-Besitzer die Anzahl der Spieler einstellen kann, muss auf 1 oder 0 eingestellt werden.";
$lang['MulticraftService.!error.configoptions[players].format'] = "

Bitte legen Sie die Anzahl der Spieler fest.
";
$lang['MulticraftService.!error.configoptions[memory].format'] = "

Bitte legen Sie eine gültige Speichermenge fest.
";
$lang['MulticraftService.!error.configoptions[daemon_id].format'] = "Bitte setze einen gültigen Daemon.";
$lang['MulticraftService.!error.configoptions[dedicated_ip].format'] = "Ob eine dedizierte IP verwendet werden soll, muss auf 1 oder 0 gesetzt sein.";
?>