<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Util.filters.client_filters.field_contact_company'] = "Firma";
$lang['Util.filters.client_filters.field_client_group_id'] = "Kundengruppe";
$lang['Util.filters.client_filters.field_last_seen_start_date'] = "Anfangsdatum";
?>