<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['IpUnblockerPlugin.!error.remote_curl'] = "Es konnte keine Verbindung zum Remote-Server hergestellt werden. cURL-Fehler: %1\$s"; // %1$s is the curl error
?>