<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyEmails.templates.Thesslstore.expiration_reminder_name'] = "SSL-Zertifikat Ablauf Erinnerung";
$lang['AdminCompanyEmails.templates.Thesslstore.expiration_reminder_desc'] = "Mitteilung, die vor Ablauf des Ablaufdatums von 30 Tagen gesendet wurde.";
?>