<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['InvoiceDelivery.!error.libxml_required'] = "Die Erweiterungen libxml und simplexml sind für die Rechnungszustellung erforderlich.";
$lang['InvoiceDelivery.deliverinvoices.interfax_subject'] = "Rechnung %1\$s"; // %1$s is the invoice number (or the first invoice number in a group of several)
$lang['InvoiceDelivery.deliverinvoices.postalmethods_description'] = "Rechnungsnummer %1\$s"; // %1$s is the invoice number (or the first invoice number in a group of several);
?>