<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientFeed.getOptionFields.example_code_inactive'] = "Zeigt die Anzahl der inaktiven Kunden an:";
$lang['ClientFeed.!error.invalid_endpoint'] = "Der angeforderte Endpunkt ist nicht gültig oder existiert nicht.";
?>