<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Perfectmoney.name'] = "Perfect Money";
$lang['Perfectmoney.payee_account'] = "Zahlungskonto";
$lang['Perfectmoney.passphrase'] = "Alternative Passphrase";
$lang['Perfectmoney.passphrase_note'] = "Die alternative Passphrase wird für die Berechnung des MD5-Hash zur Validierung von Zahlungen verwendet.";
$lang['Perfectmoney.buildprocess.submit'] = "Mit Perfect Money bezahlen";
$lang['Perfectmoney.!error.payee_account.valid'] = "Sie müssen ein gültiges Konto eingeben.";
$lang['Perfectmoney.!error.passphrase.valid'] = "Sie müssen eine gültige Passphrase eingeben.";
?>