<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Whmcs8_0.!error.host.invalid'] = "Datenbank-Host ist erforderlich.";
$lang['Whmcs8_0.!error.database.invalid'] = "Datenbankname ist erforderlich.";
$lang['Whmcs8_0.!error.pass.invalid'] = "Datenbank Passwort wird benötigt!";
$lang['Whmcs8_0.!notice.gmp'] = "Die Erweiterung 'gmp' wurde nicht gefunden. Diese Erweiterung wird empfohlen, um die Leistung zu erhöhen und den Importprozess zu verbessern. Sie können auch ohne diese Erweiterung fortfahren, aber der Importvorgang kann sehr viel langsamer sein.";
$lang['Whmcs8_0.settings.host'] = "Datenbankhost";
$lang['Whmcs8_0.settings.key'] = "CC-Verschlüsselung Hash";
$lang['Whmcs8_0.configuration.remote_package'] = "Remote-Paket";
?>