<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DownloadManagerCategories.!error.parent_id.exists'] = "Die ausgewählte Kategorie existiert nicht.";
$lang['DownloadManagerCategories.!error.parent_id.loop'] = "Die ausgewählte übergeordnete Kategorie ist möglicherweise nicht die Kategorie selbst.";
$lang['DownloadManagerCategories.!error.company_id.exists'] = "

Ungültige Firmen-ID
";
$lang['DownloadManagerCategories.!error.name.empty'] = "Bitte einen Kategorienamen angeben.";
$lang['DownloadManagerCategories.!error.description.empty'] = "Bitte geben Sie eine Kategorie Beschreibung ein.";
$lang['DownloadManagerCategories.!error.category_id.exists'] = "

Die zu aktualisierende Kategorie ist nicht vorhanden.
";
?>