<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DownloadManagerLogs.!error.file_id.exists'] = "

Die Datei existiert nicht.
";
$lang['DownloadManagerLogs.!error.client_id.exists'] = "Der Kunde existiert nicht.";
$lang['DownloadManagerLogs.!error.contact_id.exists'] = "

Der Kontakt existiert nicht.
";
?>