<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyGroups.!success.add_created'] = "%1\$s wurde erfolgreich erstellt!"; // %1$s is the name of the client group
$lang['AdminCompanyGroups.!success.edit_updated'] = "%1\$s wurde erfolgreich bearbeitet!"; // %1$s is the name of the client group
$lang['AdminCompanyGroups.!success.delete_deleted'] = "%1\$s wurde erfolgreich gelöscht!"; // %1$s is the name of the client group
$lang['AdminCompanyGroups.!error.delete_failed'] = "%1\$s ist die Standardgruppe und kann nicht gelöscht werden."; // %1$s is the name of the client group
$lang['AdminCompanyGroups.index.boxtitle_groups'] = "Kundengruppen";
$lang['AdminCompanyGroups.index.categorylink_addgroup'] = "Gruppe Erstellen";
$lang['AdminCompanyGroups.index.text_name'] = "Name";
$lang['AdminCompanyGroups.index.text_description'] = "Beschreibung";
$lang['AdminCompanyGroups.index.text_clients'] = "Anzahl der Kunden";
$lang['AdminCompanyGroups.index.text_options'] = "Optionen";
$lang['AdminCompanyGroups.index.option_edit'] = "Bearbeiten";
$lang['AdminCompanyGroups.index.option_delete'] = "Löschen";
$lang['AdminCompanyGroups.index.no_results'] = "Es gibt keine Kundengruppen.";
$lang['AdminCompanyGroups.index.confirm_delete'] = "Möchten Sie diese Kundengruppe wirklich löschen? Alle Clients in dieser Gruppe werden in die Standardgruppe verschoben.";
$lang['AdminCompanyGroups.add.boxtitle_addgroup'] = "Gruppe erstellen";
$lang['AdminCompanyGroups.add.heading_basic'] = "Grundeinstellungen";
$lang['AdminCompanyGroups.add.heading_invoice'] = "Rechnungs- und Gebührenoptionen";
$lang['AdminCompanyGroups.add.heading_delivery'] = "Zustellung der Rechnung";
$lang['AdminCompanyGroups.add.field_name'] = "Name";
$lang['AdminCompanyGroups.add.field_color'] = "Farbe";
$lang['AdminCompanyGroups.add.field_description'] = "Beschreibung";
$lang['AdminCompanyGroups.add.field_delivery_methods'] = "Rechnungszustellungsmethoden";
$lang['AdminCompanyGroups.add.field_company_settings'] = "Nutze die Einstellungen des Unternehmens (nicht markieren für spezielle Einstellungen)";
$lang['AdminCompanyGroups.add.text_addsubmit'] = "

Gruppe erstellen
";
$lang['AdminCompanyGroups.edit.boxtitle_editgroup'] = "Gruppe bearbeiten";
$lang['AdminCompanyGroups.edit.heading_basic'] = "Grundlegende Optionen";
$lang['AdminCompanyGroups.edit.heading_invoice'] = "Rechnungs- und Gebührenoptionen";
$lang['AdminCompanyGroups.edit.heading_delivery'] = "Rechnungszustellung";
$lang['AdminCompanyGroups.edit.field_name'] = "Name";
$lang['AdminCompanyGroups.edit.field_color'] = "Frabe";
$lang['AdminCompanyGroups.edit.field_description'] = "Beschreibung";
$lang['AdminCompanyGroups.edit.field_delivery_methods'] = "Rechnungsbereitstellungsmethoden";
$lang['AdminCompanyGroups.edit.field_company_settings'] = "Verwenden Sie Unternehmenseinstellungen (deaktivieren Sie, um unten anzugeben)";
$lang['AdminCompanyGroups.edit.text_editsubmit'] = "Gruppe bearbeiten";
$lang['AdminCompanyGroups.index.page_title'] = "Einstellungen > Unternehmen > Kundengruppen";
$lang['AdminCompanyGroups.add.page_title'] = "Einstellungen > Unternehmen > Kundengruppen > Gruppe erstellen";
$lang['AdminCompanyGroups.edit.page_title'] = "Einstellungen&gt; Unternehmen&gt; Kundengruppen&gt; Gruppe bearbeiten";
$lang['AdminCompanyGroups.add.heading_client_fields'] = "Erforderliche Kundenfelder";
$lang['AdminCompanyGroups.edit.heading_client_fields'] = "Erforderliche Client-Felder";
$lang['AdminCompanyGroups.add.heading_payment'] = "Hinweise";
?>