<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminReports.index.page_title'] = "Rechnungsberichte";
$lang['AdminReports.index.box_title'] = "Berichte";
$lang['AdminReports.index.field_format'] = "Format";
$lang['AdminReports.index.field_report_type'] = "Berichtstyp";
$lang['AdminReports.index.field_submit'] = "Export";
$lang['AdminReports.index.reports'] = "Generieren";
$lang['AdminReports.index.customize'] = "Anpassen";
?>