<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemCompanies.!success.company_added'] = "Das Unternehmen %1\$s wurde erfolgreich erstellt."; // %1$s is the name of the company
$lang['AdminSystemCompanies.!success.company_edited'] = "Die Firma %1\$s wurde erfolgreich bearbeitet."; // %1$s is the name of the company
$lang['AdminSystemCompanies.index.boxtitle_companies'] = "Firmen";
$lang['AdminSystemCompanies.index.categorylink_addcompany'] = "

Firma hinzufügen
";
$lang['AdminSystemCompanies.index.no_results'] = "Es gibt keine Unternehmen.";
$lang['AdminSystemCompanies.index.text_name'] = "Name";
$lang['AdminSystemCompanies.index.text_address'] = "Adresse";
$lang['AdminSystemCompanies.index.text_phone'] = "Telefon";
$lang['AdminSystemCompanies.index.text_options'] = "Optionen";
$lang['AdminSystemCompanies.index.option_edit'] = "Bearbeiten";
$lang['AdminSystemCompanies.add.boxtitle_addcompany'] = "Firma hinzufügen";
$lang['AdminSystemCompanies.add.field_company'] = "

Unternehmenseinstellungen importieren aus
";
$lang['AdminSystemCompanies.add.field_name'] = "Name";
$lang['AdminSystemCompanies.add.field_hostname'] = "Hostname";
$lang['AdminSystemCompanies.add.field_address'] = "Adresse";
$lang['AdminSystemCompanies.add.field_phone'] = "Telefon";
$lang['AdminSystemCompanies.add.field_fax'] = "Fax";
$lang['AddSystemCompanies.add.field_companysubmit'] = "Neues Unternehmen";
$lang['AdminSystemCompanies.edit.boxtitle_editcompany'] = "Firma bearbeiten";
$lang['AdminSystemCompanies.edit.field_name'] = "Name";
$lang['AdminSystemCompanies.edit.field_hostname'] = "Hostname";
$lang['AdminSystemCompanies.edit.field_address'] = "Adresse";
$lang['AdminSystemCompanies.edit.field_phone'] = "Telefon";
$lang['AdminSystemCompanies.edit.field_fax'] = "Fax";
$lang['AddSystemCompanies.edit.field_companysubmit'] = "Unternehmen bearbeiten";
$lang['AdminSystemCompanies.index.page_title'] = "Einstellungen > System > Firmen";
$lang['AdminSystemCompanies.index.text_hostname'] = "Hostname";
$lang['AdminSystemCompanies.add.page_title'] = "Einstellungen > System > Firmen > Firma hinzufügen";
$lang['AdminSystemCompanies.edit.page_title'] = "Einstellungen&gt; System&gt; Firmen&gt; Firma bearbeiten";
$lang['AdminSystemCompanies.!success.company_deleted'] = "

Die Firma %1\$s wurde erfolgreich entfernt!
"; // %1$s is the name of the company
$lang['AdminSystemCompanies.index.option_delete'] = "Löschen";
$lang['AdminSystemCompanies.index.confirm_delete'] = "Diese Firma wirklich löschen? Alles, was zu diesem Unternehmen gehört, wird verschwinden.";
$lang['AdminSystemCompanies.!tooltip.hostname'] = "Der Hostname sollte nur den Domainnamen, die TLD und die optionale Portnummer enthalten. Zum Beispiel \"domain.com\" oder \"subdomain.domain.com:8080\".";
?>