<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminTools.getlognames.text_module'] = "Module";
$lang['AdminTools.getlognames.text_gateway'] = "Tor";
$lang['AdminTools.getlognames.text_email'] = "Email";
$lang['AdminTools.getlognames.text_users'] = "Benutzeranmeldungen";
$lang['AdminTools.getlognames.text_contacts'] = "Kontakte";
$lang['AdminTools.getlognames.text_accountaccess'] = "Account Zugriff";
$lang['AdminTools.getlognames.text_cron'] = "Cron";
$lang['AdminTools.convertcurrency.boxtitle_currency'] = "Währung ändern";
$lang['AdminTools.convertcurrency.field_amount'] = "Menge";
$lang['AdminTools.convertcurrency.field_from'] = "Von";
$lang['AdminTools.convertcurrency.field_to'] = "An";
$lang['AdminTools.convertcurrency.field_currencysubmit'] = "Währung umrechnen.";
$lang['AdminTools.logs.boxtitle_logs'] = "Logs";
$lang['AdminTools.logmodule.text_name'] = "Name";
$lang['AdminTools.logmodule.text_staffname'] = "Mitarbeiter";
$lang['AdminTools.logmodule.text_date'] = "Datum";
$lang['AdminTools.logmodule.no_results'] = "Es gibt keine Modulprotokolle.";
$lang['AdminTools.moduleloglist.text_direction'] = "Ausrichtung";
$lang['AdminTools.moduleloglist.text_data'] = "Daten";
$lang['AdminTools.moduleloglist.text_date'] = "Datum";
$lang['AdminTools.moduleloglist.text_status'] = "Status";
$lang['AdminTools.moduleloglist.text_input'] = "Eingabe";
$lang['AdminTools.moduleloglist.text_output'] = "Ausgabe";
$lang['AdminTools.moduleloglist.text_error'] = "Error";
$lang['AdminTools.moduleloglist.text_success'] = "Erfolg";
$lang['AdminTools.moduleloglist.no_results'] = "Es gibt keine Daten für dieses Modulprotokoll.";
$lang['AdminTools.loggateway.text_name'] = "Name";
$lang['AdminTools.loggateway.text_staffname'] = "Mitarbeiter";
$lang['AdminTools.loggateway.text_date'] = "Datum";
$lang['AdminTools.loggateway.no_results'] = "

Es gibt keine Gateway-Protokolle.
";
$lang['AdminTools.gatewayloglist.text_direction'] = "Richtung";
$lang['AdminTools.gatewayloglist.text_data'] = "Daten";
$lang['AdminTools.gatewayloglist.text_date'] = "Datum";
$lang['AdminTools.gatewayloglist.text_status'] = "Status";
$lang['AdminTools.gatewayloglist.text_input'] = "Eingabe";
$lang['AdminTools.gatewayloglist.text_output'] = "Ausgabe";
$lang['AdminTools.gatewayloglist.text_error'] = "Fehler";
$lang['AdminTools.gatewayloglist.text_success'] = "Erfolgreich";
$lang['AdminTools.gatewayloglist.no_results'] = "Es gibt für diesen Gateway kein Logfile.";
$lang['AdminTools.logemail.text_date'] = "Datum";
$lang['AdminTools.logemail.text_subject'] = "Betreff";
$lang['AdminTools.logemail.text_summary'] = "Zusammenfassung";
$lang['AdminTools.logemail.text_status'] = "Status";
$lang['AdminTools.logemail.text_to'] = "An";
$lang['AdminTools.logemail.text_cc'] = "CC";
$lang['AdminTools.logemail.text_from'] = "Von";
$lang['AdminTools.logemail.text_resend'] = "Erneut senden";
$lang['AdminTools.logemail.text_sent'] = "Geschickt";
$lang['AdminTools.logemail.text_unsent'] = "Nicht gesendet";
$lang['AdminTools.logemail.no_results'] = "

Es gibt keine E-Mail-Logs.
";
$lang['AdminTools.logusers.text_name'] = "Name";
$lang['AdminTools.logusers.text_username'] = "Benutzername
";
$lang['AdminTools.logusers.text_type'] = "Art";
$lang['AdminTools.logusers.text_ipaddress'] = "IP Adresse";
$lang['AdminTools.logusers.text_date'] = "Datum";
$lang['AdminTools.logusers.text_staff'] = "Mitarbeiter";
$lang['AdminTools.logusers.text_client'] = "Klient";
$lang['AdminTools.logusers.no_results'] = "Es gibt keine Anmeldeprotokolle für Benutzer.";
$lang['AdminTools.logaccountaccess.name'] = "Mitarbeiter";
$lang['AdminTools.logaccountaccess.type'] = "Art";
$lang['AdminTools.logaccountaccess.date'] = "Datum";
$lang['AdminTools.logaccountaccess.text_cc'] = "Kreditkarte";
$lang['AdminTools.logaccountaccess.text_ach'] = "ACH";
$lang['AdminTools.logaccountaccess.no_results'] = "

Es gibt keine Kontozugriffsprotokolle.
";
$lang['AdminTools.accountaccess.name'] = "Name";
$lang['AdminTools.accountaccess.type'] = "Art";
$lang['AdminTools.accountaccess.last4'] = "Letzten 4";
$lang['AdminTools.accountaccess.type_cc'] = "%1\$s - %2\$s"; // %1$s is the account type (Credit Card) and %2$s is the type of account (MasterCard, Visa, etc.)
$lang['AdminTools.accountaccess.type_ach'] = "%1\$s - %2\$s"; // %1$s is the account type (ACH) and %2$s is the type of account (Checking or Savings)
$lang['AdminTools.accountaccess.no_results'] = "Für diesen Datensatz sind keine Kontodetails vorhanden.";
$lang['AdminTools.logcron.task'] = "Aufgabe";
$lang['AdminTools.logcron.start_date'] = "Anfangsdatum";
$lang['AdminTools.logcron.end_date'] = "Enddatum";
$lang['AdminTools.logcron.output'] = "Ausgabe";
$lang['AdminTools.logcron.no_output'] = "Für diesen Log gibt es keinen Output.";
$lang['AdminTools.logcron.no_results'] = "Keine cron-Protokolle vorhanden.";
$lang['AdminTools.!success.currency_converted'] = "%1\$s = %2\$s"; // %1$s is the from currency code and amount, %2$s is the to currency code and amount
$lang['AdminTools.getlognames.text_transactions'] = "Transaktionen";
$lang['AdminTools.convertcurrency.page_title'] = "

Tools Währung umrechnen
";
$lang['AdminTools.logs.page_title'] = "Logfiles";
$lang['AdminTools.logmodule.page_title'] = "Werkzeuge Protokolle";
$lang['AdminTools.loggateway.page_title'] = "Werkzeuge Protokolle";
$lang['AdminTools.logemail.page_title'] = "Tools Logfiles";
$lang['AdminTools.logusers.page_title'] = "Tools-Logs";
$lang['AdminTools.logcontacts.page_title'] = "Tools-Protokolle";
$lang['AdminTools.logcontacts.text_name'] = "Name";
$lang['AdminTools.logcontacts.text_date'] = "Datum";
$lang['AdminTools.logcontacts.text_field'] = "Feld";
$lang['AdminTools.logcontacts.text_previous'] = "Vorheriger Wert";
$lang['AdminTools.logcontacts.text_new'] = "Neuer Wert";
$lang['AdminTools.logcontacts.no_results'] = "

Es gibt keine Kontaktprotokolle.
";
$lang['AdminTools.logtransactions.page_title'] = "Tools Logs";
$lang['AdminTools.logtransactions.text_client_name'] = "Kunde";
$lang['AdminTools.logtransactions.text_staff_name'] = "Mitarbeiter";
$lang['AdminTools.logtransactions.text_date'] = "Datum";
$lang['AdminTools.logtransactions.text_field'] = "Feld";
$lang['AdminTools.logtransactions.text_previous'] = "Vorheriger Wert";
$lang['AdminTools.logtransactions.text_new'] = "Neuer Wert";
$lang['AdminTools.logtransactions.no_results'] = "Es gibt keine Transaktions Logs.";
$lang['AdminTools.logaccountaccess.page_title'] = "Tools Logs";
$lang['AdminTools.logcron.page_title'] = "Tools-Protokolle";
$lang['AdminTools.getlognames.text_invoice_delivery'] = "Rechnungszustellung";
$lang['AdminTools.loginvoicedelivery.page_title'] = "

Tools-Protokolle
";
$lang['AdminTools.loginvoicedelivery.invoice_id_code'] = "Rechnung #";
$lang['AdminTools.loginvoicedelivery.first_name'] = "Kunde";
$lang['AdminTools.loginvoicedelivery.method'] = "Lieferungsmethode";
$lang['AdminTools.loginvoicedelivery.date_sent'] = "Sende Datum";
$lang['AdminTools.loginvoicedelivery.no_results'] = "Es gibt keine Rechnung Lieferprotokolle.";
$lang['AdminTools.logusers.text_location'] = "Ort";
$lang['AdminTools.logusers.text_result'] = "Ergebnis";
$lang['AdminTools.logusers.text_success'] = "Erfolg";
$lang['AdminTools.logusers.text_failure'] = "Fehler";
$lang['AdminTools.logusers.text_contact'] = "Kontakt";
$lang['AdminTools.getlognames.text_client_settings'] = "Kunden-Einstellungen";
$lang['AdminTools.logclientsettings.text_ip_address'] = "IP Adresse";
$lang['AdminTools.logclientsettings.text_field'] = "Feld";
$lang['AdminTools.logclientsettings.no_results'] = "Es gibt keine Client-Einstellungsprotokolle.";
$lang['AdminTools.logmessenger.page_title'] = "Ereignis Log";
$lang['AdminTools.logmessenger.text_date'] = "Datum";
$lang['AdminTools.messengerloglist.text_error'] = "Fehler";
$lang['AdminTools.!success.collation_updated'] = "Die Sortierung der Datenbank wurde erfolgreich aktualisiert.";
$lang['AdminTools.utilities.heading_description'] = "Beschreibung";
$lang['AdminTools.utilities.heading_options'] = "Optionen";
$lang['AdminTools.utilities.text_update_to_utf8mb4'] = "Aktualisieren Sie den Zeichensatz und die Sortierung Ihrer Datenbank, Tabellen und Spalten auf utf8mb4 und um 4-Byte-Zeichen wie Emojis zu unterstützen. Dies kann einige Minuten dauern.";
?>