<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemStaff.!success.staff_added'] = "Dieser Mitarbeiter wurde erfolgreich hinzugefügt!";
$lang['AdminSystemStaff.!success.staff_updated'] = "Dieser Mitarbeiter wurde erfolgreich aktualisiert!";
$lang['AdminSystemStaff.!success.group_added'] = "Die Mitarbeitergruppe \"%1\$s\" wurde erfolgreich erstellt!"; // %1$s is the name of the staff group
$lang['AdminSystemStaff.!success.group_updated'] = "Die Mitarbeitergruppe \"%1\$s\" wurde erfolgreich aktualisiert!"; // %1$s is the name of the staff group
$lang['AdminSystemStaff.!success.group_deleted'] = "Die Mitarbeiter-Gruppe, \"%1\$s\" wurde erfolgreich gelöscht!"; // %1$s is the name of the staff group
$lang['AdminSystemStaff.manage.boxtitle_manage'] = "Verwalte Personal";
$lang['AdminSystemStaff.manage.category_active'] = "Aktiv";
$lang['AdminSystemStaff.manage.category_inactive'] = "Inaktiv";
$lang['AdminSystemStaff.manage.categorylink_addstaff'] = "Mitarbeiter hinzufügen";
$lang['AdminSystemStaff.manage.heading_name'] = "Name";
$lang['AdminSystemStaff.manage.heading_email'] = "Email";
$lang['AdminSystemStaff.manage.heading_options'] = "Optionen";
$lang['AdminSystemStaff.manage.no_results'] = "Es gibt keine Mitarbeiter mit diesem Status.";
$lang['AdminSystemStaff.manage.confirm_deactivate'] = "Möchten Sie diesen Mitarbeiter wirklich deaktivieren?";
$lang['AdminSystemStaff.manage.confirm_reactivate'] = "Reaktivieren Sie diesen Mitarbeiter wirklich?";
$lang['AdminSystemStaff.manage.option_edit'] = "Bearbeiten";
$lang['AdminSystemStaff.manage.option_deactivate'] = "Deaktivieren";
$lang['AdminSystemStaff.manage.option_reactivate'] = "Reaktivieren";
$lang['AdminSystemStaff.groups.option_delete'] = "Löschen";
$lang['AdminSystemStaff.add.boxtitle_addstaff'] = "Mitarbeiter hinzufügen";
$lang['AdminSystemStaff.add.heading_contact'] = "Kontakt Informationen";
$lang['AdminSystemStaff.add.heading_authentication'] = "Authentifizierung";
$lang['AdminSystemStaff.add.heading_groups'] = "Gruppen";
$lang['AdminSystemStaff.add.field_firstname'] = "Vorname";
$lang['AdminSystemStaff.add.field_lastname'] = "Nachname";
$lang['AdminSystemStaff.add.field_email'] = "

E-Mail
";
$lang['AdminSystemStaff.add.field_username'] = "Benutzername";
$lang['AdminSystemStaff.add.field_username_username'] = "Geben Sie einen Benutzernamen ein";
$lang['AdminSystemStaff.add.field_username_email'] = "Nutze die E-Mail Adresse als Benutzername";
$lang['AdminSystemStaff.add.field_password'] = "Passwort";
$lang['AdminSystemStaff.add.field_confirmpass'] = "Passwort Bestätigen";
$lang['AdminSystemStaff.add.field_twofactormode'] = "Zwei-Faktor Authentifizierung ";
$lang['AdminSystemStaff.add.field_twofactorkey'] = "Zwei Faktor Schlüssel";
$lang['AdminSystemStaff.add.field_twofactorpin'] = "Zwei-Faktoren Pin";
$lang['AdminSystemStaff.add.text_membergroups'] = "Mitglieder Gruppen";
$lang['AdminSystemStaff.add.text_availablegroups'] = "Verfügbare Gruppen";
$lang['AdminSystemStaff.edit.boxtitle_editstaff'] = "Bearbeite Verwaltung";
$lang['AdminSystemStaff.edit.heading_contact'] = "Kontakt";
$lang['AdminSystemStaff.edit.heading_authentication'] = "Authentifizierung";
$lang['AdminSystemStaff.edit.heading_groups'] = "Gruppen";
$lang['AdminSystemStaff.edit.field_firstname'] = "Vorname";
$lang['AdminSystemStaff.edit.field_lastname'] = "Nachname";
$lang['AdminSystemStaff.edit.field_username'] = "Benutzername";
$lang['AdminSystemStaff.edit.field_email'] = "E-Mail";
$lang['AdminSystemStaff.edit.field_password'] = "Neues Passwort";
$lang['AdminSystemStaff.edit.field_confirmpass'] = "Passwort bestätigen";
$lang['AdminSystemStaff.edit.field_twofactormode'] = "Zwei-Faktor-Authentifizierung";
$lang['AdminSystemStaff.edit.field_twofactorkey'] = "Zwei-Faktor-Schlüssel";
$lang['AdminSystemStaff.edit.field_twofactorpin'] = "Zwei Faktor Pin";
$lang['AdminSystemStaff.edit.text_membergroups'] = "Mitgliedergruppen";
$lang['AdminSystemStaff.edit.text_availablegroups'] = "Verfügbare Gruppen";
$lang['AdminSystemStaff.groups.boxtitle_groups'] = "Mitarbeitergruppen";
$lang['AdminSystemStaff.groups.categorylink_addgroup'] = "Gruppe erstellen";
$lang['AdminSystemStaff.groups.heading_name'] = "Name";
$lang['AdminSystemStaff.groups.heading_company_name'] = "Name Ihrer Firma";
$lang['AdminSystemStaff.groups.heading_staff'] = "

Mitarbeiteranzahl
";
$lang['AdminSystemStaff.groups.heading_options'] = "Optionen";
$lang['AdminSystemStaff.groups.no_results'] = "Es existieren keine Mitarbeiter Gruppen.";
$lang['AdminSystemStaff.groups.option_edit'] = "Bearbeiten";
$lang['AdminSystemStaff.groups.modal_delete'] = "Möchten Sie diese Mitarbeitergruppe wirklich löschen?";
$lang['AdminSystemStaff.addgroup.boxtitle_addgroup'] = "Gruppe erstellen";
$lang['AdminSystemStaff.addgroup.field_name'] = "Name";
$lang['AdminSystemStaff.addgroup.field_company'] = "Unternehmen";
$lang['AdminSystemStaff.addgroup.field_groupsubmit'] = "Gruppe erstellen";
$lang['AdminSystemStaff.addgroup.heading_general'] = "Allgemein";
$lang['AdminSystemStaff.addgroup.heading_permissions'] = "Zugriffskontrollliste";
$lang['AdminSystemStaff.editgroup.boxtitle_editgroup'] = "Gruppe bearbeiten";
$lang['AdminSystemStaff.editgroup.field_name'] = "Name";
$lang['AdminSystemStaff.editgroup.field_company'] = "Unternehmen";
$lang['AdminSystemStaff.editgroup.field_groupsubmit'] = "Gruppe bearbeiten";
$lang['AdminSystemStaff.editgroup.heading_general'] = "Allgemein";
$lang['AdminSystemStaff.editgroup.heading_permissions'] = "Zugriffskontrollliste (ACL)";
$lang['AdminSystemStaff.editgroup.dialog_confirm_edit_assigned'] = "Sie sind derzeit dieser Mitarbeitergruppe zugeordnet. Alle Änderungen werden sofort wirksam und Sie können möglicherweise nicht mehr auf diesen Bereich zugreifen. Möchten Sie diese Änderungen wirklich vornehmen?";
$lang['AdminSystemStaff.manage.page_title'] = "Einstellungen -> System -> Mitarbeiter -> Mitarbeiter verwalten";
$lang['AdminSystemStaff.add.page_title'] = "Einstellungen > System > Mitarbeiter > Mitarbeiter hinzufügen";
$lang['AdminSystemStaff.edit.page_title'] = "Einstellungen > System > Mitarbeiter > Mitarbeiter bearbeiten";
$lang['AdminSystemStaff.groups.page_title'] = "Einstellungen > System > Mitarbeiter > Mitarbeitergruppen";
$lang['AdminSystemStaff.!groups.text_separator'] = "/";
$lang['AdminSystemStaff.!groups.text_group_start'] = "(";
$lang['AdminSystemStaff.!groups.text_group_end'] = ")";
$lang['AdminSystemStaff.addgroup.page_title'] = "Einstellungen -> System -> Mitarbeiter -> Gruppe erstellen";
$lang['AdminSystemStaff.addgroup.heading_email_notices'] = "

E-Mail-BCC-Benachrichtigungen
";
$lang['AdminSystemStaff.addgroup.text_check_all'] = "Alle überprüfen";
$lang['AdminSystemStaff.addgroup.text_uncheck_all'] = "

Alle deaktivieren
";
$lang['AdminSystemStaff.editgroup.page_title'] = "Einstellungen > System > Mitarbeiter > Gruppe bearbeiten";
$lang['AdminSystemStaff.editgroup.heading_email_notices'] = "E-Mail BCC Notizen";
$lang['AdminSystemStaff.add.field_addsubmit'] = "Mitarbeiter erstellen";
$lang['AdminSystemStaff.edit.field_editsubmit'] = "Mitarbeiter bearbeiten";
$lang['AdminSystemStaff.addgroup.heading_subscription_email_notices'] = "

E-Mail-Abonnementbenachrichtigungen
";
$lang['AdminSystemStaff.editgroup.heading_subscription_email_notices'] = "E-Mail-Abonnement-Benachrichtigungen";
$lang['AdminSystemStaff.addgroup.field_session_lock'] = "Bei Änderung der IP-Adresse abmelden";
$lang['AdminSystemStaff.editgroup.field_session_lock'] = "Bei Änderung der IP-Adresse abmelden";
?>