<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemHelp.index.heading_user_manual'] = "Benutzerhandbuch";
$lang['AdminSystemHelp.index.text_user_manual'] = "Sie fragen sich, wie Sie Blesta konfigurieren oder einige der erweiterten Funktionen nutzen können? Schauen Sie sich die Bedienungsanleitung an.";
$lang['AdminSystemHelp.index.heading_dev_manual'] = "Entwicklerhandbuch";
$lang['AdminSystemHelp.index.text_dev_manual'] = "Auf die Bedürfnisse von Entwicklern zugeschnitten, enthält das Entwicklerhandbuch alles Wissenswerte über die Entwicklung für die Blesta-Plattform.";
$lang['AdminSystemHelp.index.heading_forums'] = "Community Foren";
$lang['AdminSystemHelp.index.text_forums'] = "Die Blesta Foren werden durch die Community unterstützt und sind zentrale Anlaufstelle für alle Art von Fragen und Problemen.";
$lang['AdminSystemHelp.index.page_title'] = "Einstellungen -> System -> Hilfe -> Resourcen";
$lang['AdminSystemHelp.boxtitle_help'] = "Ressourcen";
$lang['AdminSystemHelp.index.heading_discord'] = "Discord-Chat";
?>