<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemMarketplace.index.boxtitle_marketplace'] = "Marktplatz";
$lang['AdminSystemMarketplace.index.text_unavailable'] = "Der Marktplatz ist derzeit nicht Verfügbar.";
$lang['AdminSystemMarketplace.index.page_title'] = "Einstellungen > System > Marktplatz";
$lang['AdminSystem.marketplace.category_all'] = "Alles";
$lang['AdminSystemMarketplace.listing.boxtitle_listing'] = "Erweiterung %1\$s"; // %1$s is the name of the extension
?>