<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyGateways.!success.manage_updated'] = "Die Schnittstelle wurde erfolgreich geupdated";
$lang['AdminCompanyGateways.!success.upgraded'] = "Das Gateway wurde erfolgreich aktualisiert.";
$lang['AdminCompanyGateways.!success.uninstalled'] = "Das Gateway wurde erfolgreich deinstalliert.";
$lang['AdminCompanyGateways.!success.installed'] = "Das Gateway wurde erfolgreich installiert.";
$lang['AdminCompanyGateways.available.heading_merchant'] = "Händler";
$lang['AdminCompanyGateways.available.heading_nonmerchant'] = "Non-Merchant";
$lang['AdminCompanyGateways.available.text_author'] = "Autor:";
$lang['AdminCompanyGateways.available.text_author_url'] = "Autor-URL";
$lang['AdminCompanyGateways.available.text_supports'] = "Unterstützt:";
$lang['AdminCompanyGateways.available.text_merchantach'] = "ACH";
$lang['AdminCompanyGateways.available.text_merchantachoffsite'] = "ACH außer Haus";
$lang['AdminCompanyGateways.available.text_merchantcc'] = "Kreditkarte";
$lang['AdminCompanyGateways.available.text_merchantccoffsite'] = "Kreditkarten Offsite";
$lang['AdminCompanyGateways.available.text_merchant_none'] = "Es sind keine Händler-Gateways verfügbar.";
$lang['AdminCompanyGateways.available.text_nonmerchant_none'] = "Es gibt keine verfügbaren Nicht-Händler-Gateways.";
$lang['AdminCompanyGateways.available.btn_install'] = "Installieren";
$lang['AdminCompanyGateways.installed.heading_merchant'] = "Händler";
$lang['AdminCompanyGateways.installed.heading_nonmerchant'] = "Nicht-Händler";
$lang['AdminCompanyGateways.installed.text_author'] = "Autor:";
$lang['AdminCompanyGateways.installed.text_author_url'] = "Autor-URL";
$lang['AdminCompanyGateways.installed.text_supports'] = "Unterstützt:";
$lang['AdminCompanyGateways.installed.text_merchantach'] = "ACH";
$lang['AdminCompanyGateways.installed.text_merchantachoffsite'] = "Lastschrift";
$lang['AdminCompanyGateways.installed.text_merchantcc'] = "Kreditkarte";
$lang['AdminCompanyGateways.installed.text_merchantccoffsite'] = "Kreditkarte außerhalb";
$lang['AdminCompanyGateways.installed.text_merchant_none'] = "Es sind keine Händler-Gateways installiert.";
$lang['AdminCompanyGateways.installed.text_nonmerchant_none'] = "Es gibt keine installierten Nicht-Händler-Gateways.";
$lang['AdminCompanyGateways.installed.btn_uninstall'] = "Deinstallieren";
$lang['AdminCompanyGateways.installed.btn_manage'] = "Verwalten";
$lang['AdminCompanyGateways.installed.btn_upgrade'] = "Upgrade";
$lang['AdminCompanyGateways.installed.confirm_uninstall'] = "Möchten Sie dieses Gateway wirklich deinstallieren?";
$lang['AdminCompanyGateways.manage.boxtitle_manage'] = "Verwalten Sie %1\$s"; // %1$s is the name of the gateway
$lang['AdminCompanyGateways.manage.heading_gateway'] = "Zahlungsoptionen";
$lang['AdminCompanyGateways.manage.heading_currencies'] = "Akzeptierte Währungen";
$lang['AdminCompanyGateways.manage.text_addcurrency'] = "Währung hinzufügen";
$lang['AdminCompanyGateways.manage.update_settings'] = "Einstellungen aktualisieren";
$lang['AdminCompanyGateways.available.page_title'] = "Einstellungen> Unternehmen> Gateways> Verfügbar";
$lang['AdminCompanyGateways.available.signup_url'] = "Anmelden";
$lang['AdminCompanyGateways.installed.page_title'] = "Einstellungen > Firma > Gateways > Installiert";
$lang['AdminCompanyGateways.installed.signup_url'] = "Anmelden";
$lang['AdminCompanyGateways.manage.page_title'] = "Einstellungen> Unternehmen> Gateways> Verwalten Sie %1\$s"; // %1$s is the name of the gateway
$lang['AdminCompanyGateways.available.text_version'] = "(ver %1\$s)"; // %1$s is the version number of this gateway
$lang['AdminCompanyGateways.installed.text_version'] = "(ver %1\$s)"; // %1$s is the version number of this gateway
$lang['AdminCompanyGateways.manage.text_in_use_by'] = "im Einsatz von";
$lang['AdminCompanyGateways.!tab.installed'] = "Eingerichtet";
$lang['AdminCompanyGateways.!tab.available'] = "Verfügbar";
$lang['AdminCompanyGateways.available.boxtitle_gateway'] = "Gateways";
$lang['AdminCompanyGateways.installed.boxtitle_gateway'] = "Gateways";
$lang['AdminCompanyGateways.available.text_merchantachform'] = "Benutzerdefiniertes ACH-Formular";
$lang['AdminCompanyGateways.installed.text_merchantachform'] = "Benutzerdefiniertes ACH-Formular";
?>