<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyClientOptions.!success.field_updated'] = "Das benutzerdefinierte Benutzerfeld wurde erfolgreich aktualisiert.";
$lang['AdminCompanyClientOptions.!success.field_created'] = "Das benutzerdefinierte Benutzerfeld wurde erfolgreich erstellt.";
$lang['AdminCompanyClientOptions.!success.field_deleted'] = "Das benutzerdefinierte Benutzerfeld wurde erfolgreich gelöscht.";
$lang['AdminCompanyClientOptions.!success.requiredfields_updated'] = "Die erforderlichen Felder wurden erfolgreich aktualisiert.";
$lang['AdminCompanyClientoptions.customfields.page_title'] = "Settings > Company > Client Options > Client Custom Fields > Browse";
$lang['AdminCompanyClientOptions.customfields.boxtitle_browse'] = "Durchsuchen Sie benutzerdefinierte Clientfelder";
$lang['AdminCompanyClientOptions.customfields.categorylink_addfield'] = "Feld erstellen";
$lang['AdminCompanyClientOptions.customfields.text_name'] = "Name";
$lang['AdminCompanyClientOptions.customfields.text_type'] = "Art";
$lang['AdminCompanyClientOptions.customfields.text_required'] = "Erforderlich";
$lang['AdminCompanyClientOptions.customfields.text_visible'] = "Sichtbar für Kunden";
$lang['AdminCompanyClientOptions.customfields.text_read_only'] = "Nur für Kunden";
$lang['AdminCompanyClientOptions.customfields.text_options'] = "Optionen";
$lang['AdminCompanyClientOptions.customfields.option_edit'] = "bearbeiten";
$lang['AdminCompanyClientOptions.customfields.option_delete'] = "löschen";
$lang['AdminCompanyClientOptions.customfields.confirm_delete'] = "Durch das Löschen dieses benutzerdefinierten Felds werden alle Daten gelöscht, die für jeden Client in dieser Gruppe gespeichert sind. Möchten Sie dieses benutzerdefinierte Feld wirklich löschen?";
$lang['AdminCompanyClientOptions.customfields.no_results'] = "Es gibt keine benutzerdefinierten Felder.";
$lang['AdminCompanyClientoptions.addcustomfield.page_title'] = "Einstellungen> Firma> Client-Optionen> Benutzerdefinierte Client-Felder> Benutzerdefiniertes Feld hinzufügen";
$lang['AdminCompanyClientOptions.addcustomfield.boxtitle_add'] = "Benutzerdefiniertes Feld hinzufügen";
$lang['AdminCompanyClientOptions.addcustomfield.categorylink_select'] = "Zusätzliche Option hinzufügen";
$lang['AdminCompanyClientOptions.addcustomfield.heading_select_value'] = "Wert";
$lang['AdminCompanyClientOptions.addcustomfield.heading_select_option'] = "Optionsname";
$lang['AdminCompanyClientOptions.addcustomfield.text_remove'] = "löschen";
$lang['AdminCompanyClientoptions.editcustomfield.page_title'] = "Einstellungen> Firma> Client-Optionen> Benutzerdefinierte Client-Felder> Benutzerdefiniertes Feld bearbeiten";
$lang['AdminCompanyClientOptions.editcustomfield.boxtitle_edit'] = "Benutzerdefiniertes Feld bearbeiten";
$lang['AdminCompanyClientOptions.editcustomfield.categorylink_select'] = "Zusätzliche Option hinzufügen";
$lang['AdminCompanyClientOptions.editcustomfield.heading_select_value'] = "Wert";
$lang['AdminCompanyClientOptions.editcustomfield.heading_select_option'] = "Optionsname";
$lang['AdminCompanyClientOptions.editcustomfield.text_remove'] = "löschen";
$lang['AdminCompanyClientOptions.getRequired.no'] = "Nein";
$lang['AdminCompanyClientOptions.getRequired.yes'] = "Ja";
$lang['AdminCompanyClientOptions.getRequired.regex'] = "Benutzerdefinierte Regex";
$lang['AdminCompanyClientoptions.requiredfields.page_title'] = "Einstellungen> Firma> Client-Optionen> Benutzerdefinierte Client-Felder> Erforderliche Client-Felder";
$lang['AdminCompanyClientOptions.requiredfields.boxtitle'] = "Erforderliche Kundenfelder";
$lang['AdminCompanyClientOptions.requiredfields.description'] = "Überprüfen Sie die Felder, die beim Erstellen oder Aktualisieren eines Kunden oder Kontakts benötigt werden.";
$lang['AdminCompanyClientOptions.requiredfields.field_company'] = "Firma oder Organisation";
$lang['AdminCompanyClientOptions.requiredfields.field_title'] = "Titel";
$lang['AdminCompanyClientOptions.requiredfields.field_address1'] = "Adresse 1";
$lang['AdminCompanyClientOptions.requiredfields.field_address2'] = "Adresse 2";
$lang['AdminCompanyClientOptions.requiredfields.field_city'] = "Stadt";
$lang['AdminCompanyClientOptions.requiredfields.field_country'] = "Land";
$lang['AdminCompanyClientOptions.requiredfields.field_state'] = "Bundesland";
$lang['AdminCompanyClientOptions.requiredfields.field_zip'] = "Postleitzahl";
$lang['AdminCompanyClientOptions.requiredfields.field_email'] = "Email Adresse";
$lang['AdminCompanyClientOptions.requiredfields.text_submit'] = "Update Einstellungen";
$lang['AdminCompanyClientOptions.requiredfields.field_first_name'] = "Vorname";
$lang['AdminCompanyClientOptions.requiredfields.field_last_name'] = "Nachname";
$lang['AdminCompanyClientOptions.!notice.group_settings'] = "HINWEIS: Diese Einstellungen gelten nur für Clientgruppen, die ihre Einstellungen vom Unternehmen übernehmen.";
$lang['AdminCompanyClientOptions.!tooltip.state'] = "Für zusätzliche Schriften entpacken Sie Ihre benutzerdefinierten TCPDF-Schriften in das Verzeichnis /vendors/tecnickcom/tcpdf/fonts/fonts/ innerhalb Ihrer Installation.";
$lang['AdminCompanyClientOptions.general.field_unique_contact_emails_primary'] = "Primäre Kontakte";
$lang['AdminCompanyClientOptions.!tooltip.name'] = "Dies ist der Anzeigename für dieses Feld. Es kann sich um eine Sprachdefinition handeln.";
$lang['AdminCompanyClientOptions.!tooltip.checkbox_value'] = "Der gesendete Wert, wenn das Kontrollkästchen aktiviert ist.";
$lang['AdminCompanyClientOptions.addcustomfield.field.client_group_id'] = "Kunden Gruppe";
$lang['AdminCompanyClientOptions.addcustomfield.field.required'] = "Erforderlich";
$lang['AdminCompanyClientOptions.addcustomfield.field.regex'] = "Benutzerdefinierte Regex";
$lang['AdminCompanyClientOptions.addcustomfield.field.encrypted'] = "Werte verschlüsseln";
$lang['AdminCompanyClientOptions.addcustomfield.field.addsubmit'] = "Benutzerdefiniertes Feld hinzufügen";
$lang['AdminCompanyClientOptions.addcustomfield.field.default_checkbox'] = "Standardwert ausgewählt";
$lang['AdminCompanyClientOptions.editcustomfield.field.show_client'] = "Für Kunden Sichtbar";
$lang['AdminCompanyClientOptions.editcustomfield.heading_select_default'] = "Standard";
$lang['AdminCompanyClientOptions.general.field_email_verification'] = "E-Mail-Bestätigung aktivieren";
$lang['AdminCompanyClientOptions.general.prevent_unverified_payments'] = "Verhindern Sie Zahlungen von nicht verifizierten Kunden";
$lang['AdminCompanyClientOptions.!tooltip.clients_start'] = "Kunden ID Start ist der Startwert für Kunden-ID's. Neue Kunden haben diesen Wert, es sei denn, er ist kleiner als der Wert des zuletzt erstellten Kunden.";
?>