<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ApiKeys.!error.key.generate'] = "Der Schlüssel konnte nicht generiert werden.";
$lang['ApiKeys.!error.company_id.exists'] = "Die angegebene Firma existiert nicht.";
$lang['ApiKeys.!error.user.valid'] = "Der API-Benutzer oder -Schlüssel scheint ungültig zu sein.";
$lang['ApiKeys.!error.user.unique'] = "Der API Benutzer existiert bereits für die Firma.";
$lang['ApiKeys.!error.user.format'] = "Bitte geben Sie einen API-Benutzer mit einer Länge von 3 bis 64 Zeichen ein.";
?>