<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CalendarEvents.!error.company_id.exists'] = "Ungültige Firmen-ID";
$lang['CalendarEvents.!error.staff_id.exists'] = "Ungültige Mitarbeiter-ID.";
$lang['CalendarEvents.!error.staff_id.valid'] = "Nur der Ersteller des Ereignisses darf dieses Ereignis aktualisieren.";
$lang['CalendarEvents.!error.shared.format'] = "Ob das Ereignis geteilt wird oder nicht, muss eine Zahl sein.";
$lang['CalendarEvents.!error.shared.length'] = "Die gemeinsame Länge darf 1 Ziffer nicht überschreiten.";
$lang['CalendarEvents.!error.title.empty'] = "Bitte einen Titel eingeben.";
$lang['CalendarEvents.!error.start_date.format'] = "

Das Startdatum hat ein ungültiges Datumsformat.
";
$lang['CalendarEvents.!error.start_date.order'] = "Das Startdatum muss vor dem Enddatum liegen.";
$lang['CalendarEvents.!error.end_date.format'] = "Das Format des Enddatums ist ungültig.";
$lang['CalendarEvents.!error.all_day.format'] = "Ob das Ereignis den ganzen Tag dauert oder nicht, muss eine Zahl sein.";
$lang['CalendarEvents.!error.all_day.length'] = "Die Länge all_day darf 1 Ziffer nicht überschreiten.";
?>