<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientLogin.!error.unknown_user'] = "Dieser Benutzername wird nicht erkannt oder das Passwort kann nicht zurückgesetzt werden.";
$lang['ClientLogin.!success.reset_sent'] = "Eine Bestätigungs-E-Mail wurde an die angegebene Adresse gesendet.";
$lang['ClientLogin.index.field_username'] = "Nutzername";
$lang['ClientLogin.index.field_password'] = "Passwort";
$lang['ClientLogin.index.field_rememberme'] = "Erinnere mich an diesem Computer";
$lang['ClientLogin.index.link_resetpassword'] = "Passwort zurücksetzen";
$lang['ClientLogin.reset.page_title'] = "Passwort zurücksetzen ";
$lang['ClientLogin.reset.reset_heading'] = "Passwort zurücksetzen";
$lang['ClientLogin.reset.field_username'] = "Benutzername";
$lang['ClientLogin.reset.field_resetsubmit'] = "Passwort zurücksetzen";
$lang['ClientLogin.reset.link_login'] = "Abbrechen, Anmelden";
$lang['ClientLogin.confirmreset.page_title'] = "Zurücksetzen des Passworts bestätigen";
$lang['ClientLogin.confirmreset.reset_heading'] = "Bestätigen Sie das Passwort zurücksetzen";
$lang['ClientLogin.confirmreset.field_new_password'] = "Neues Passwort";
$lang['ClientLogin.confirmreset.field_confirm_password'] = "Bestätige neues Passwort";
$lang['ClientLogin.confirmreset.field_resetsubmit'] = "Passwort setzen";
$lang['ClientLogin.confirmreset.link_login'] = "Abbrechen, Login";
$lang['ClientLogin.index.description'] = "Bitte melden Sie sich an, um auf den Kundenbereich zuzugreifen.";
$lang['ClientLogin.reset.description'] = "Geben Sie Ihren Benutzernamen ein, um einen Link zum Zurücksetzen des Passworts anzufordern.";
$lang['ClientLogin.confirmreset.description'] = "Bitte geben Sie Ihr neues Passwort ein.";
$lang['ClientLogin.index.page_title'] = "Einloggen";
$lang['ClientLogin.index.login_heading'] = "Einloggen";
$lang['ClientLogin.index.field_loginsubmit'] = "Einloggen";
$lang['ClientLogin.otp.page_title'] = "Einloggen";
$lang['ClientLogin.otp.description'] = "

Bitte geben Sie Ihr Einmalpasswort ein.
";
$lang['ClientLogin.otp.login_heading'] = "Einloggen";
$lang['ClientLogin.otp.field_otp'] = "Einmaliges Passwort";
$lang['ClientLogin.otp.field_submit'] = "Einloggen";
$lang['ClientLogin.forgot.field_forgotsubmit'] = "Nutzernamen Vergessen";
?>