<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientGroups.!error.name.empty'] = "Bitte geben Sie einen Gruppennamen ein.";
$lang['ClientGroups.!error.company_id.exists'] = "Ungültige Firmen-ID";
$lang['ClientGroups.!error.color.length'] = "

Die Länge der Farbe darf 16 Zeichen nicht überschreiten.
";
$lang['ClientGroups.!error.group_id.exists'] = "

Ungültige Kundengruppen-ID
";
?>