<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientInvoices.index.page_title'] = "Kunde #%1\$s Rechnungen"; // %1$s is the client ID number
$lang['ClientInvoices.index.category_open'] = "Öffnen";
$lang['ClientInvoices.index.category_closed'] = "Geschlossen";
$lang['ClientInvoices.index.categorylink_make_payment'] = "Zahlung tätigen";
$lang['ClientInvoices.index.boxtitle_invoices'] = "Rechnungen";
$lang['ClientInvoices.index.heading_invoice'] = "Rechnung #";
$lang['ClientInvoices.index.heading_amount'] = "Menge";
$lang['ClientInvoices.index.heading_paid'] = "Bezahlt";
$lang['ClientInvoices.index.heading_due'] = "Fällig";
$lang['ClientInvoices.index.heading_dateclosed'] = "Datum geschlossen";
$lang['ClientInvoices.index.heading_datebilled'] = "Rechnungsdatum";
$lang['ClientInvoices.index.heading_datedue'] = "Fälligkeitsdatum";
$lang['ClientInvoices.index.heading_options'] = "Optionen";
$lang['ClientInvoices.index.option_view'] = "Ansicht";
$lang['ClientInvoices.index.option_pay'] = "Bezahlen";
$lang['ClientInvoices.index.no_results'] = "Sie haben keine %1\$s Rechnung(en)."; // %1$s is the language for the invoice category type (e.g. Open, Closed)
$lang['ClientInvoices.applied.heading_paymenttype'] = "Zahlungsart";
$lang['ClientInvoices.applied.heading_amount'] = "Betrag";
$lang['ClientInvoices.applied.heading_applied'] = "Angewendet";
$lang['ClientInvoices.applied.heading_appliedon'] = "Aufgetragen auf";
$lang['ClientInvoices.applied.no_results'] = "Die Rechnung hat keine Transaktionen zugewiesen.";
?>