<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientEmails.index.boxtitle_emails'] = "E-Mail-Verlauf";
$lang['ClientEmails.index.heading_date'] = "Datum";
$lang['ClientEmails.index.text_from'] = "Von";
?>