<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Countries.!error.alpha2.format'] = "

Der Alpha2-Ländercode muss aus 2 Buchstaben bestehen.
";
$lang['Countries.!error.alpha2.in_use'] = "Alpha2 Ländercode %1\$s ist bereits in Benutzung."; // %1$s is the alpha2 country code
$lang['Countries.!error.alpha2.exists'] = "Ungültiger Alpha2 Code";
$lang['Countries.!error.alpha3.format'] = "

Der Alpha3-Ländercode muss aus 3 Buchstaben bestehen.
";
$lang['Countries.!error.alpha3.in_use'] = "Der Alpha3-Ländercode %1\$s ist bereits vergeben."; // %1$s is the alpha3 country code
$lang['Countries.!error.name.format'] = "Bitte geben Sie einen Namen ein.";
?>