<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CouponTerms.!error.coupon_id.exists'] = "Der angegebene Gutschein existiert nicht.";
$lang['CouponTerms.!error.term.format'] = "Bitte geben Sie für jeden Zeitraum einen gültigen Begriff ein.";
$lang['CouponTerms.!error.period.valid'] = "Bitte geben Sie einen gültigen Zeitraum ein.";
$lang['CouponTerms.!error.term_id.exists'] = "

Die angegebene Kuponlaufzeit existiert nicht.
";
$lang['CouponTerms.getperiods.day'] = "Tag";
$lang['CouponTerms.getperiods.week'] = "Woche";
$lang['CouponTerms.getperiods.month'] = "Monat";
$lang['CouponTerms.getperiods.year'] = "Jahr";
$lang['CouponTerms.getperiods.onetime'] = "Einmal";
?>