<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Encryption.!error.current_passphrase.empty'] = "Bitte geben Sie die aktuelle Passphrase des privaten Schlüssels an.";
$lang['Encryption.!error.current_passphrase.matches'] = "Der aktuelle private Key ist ungültig.";
$lang['Encryption.!error.private_key_passphrase.empty'] = "Bitte geben Sie eine neue Passphrase für den privaten Schlüssel ein.";
$lang['Encryption.!error.confirm_new_passphrase.matches'] = "Der neue Passphrase stimmt nicht überein.";
$lang['Encryption.!error.agree.empty'] = "Bitte bestätigen Sie, das dieses Passwort an einem sicheren Ort aufbewahrt wird.";
?>