<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['GatewayPayments.!error.gateway.exists'] = "Die Schnittstelle existiert nicht oder ist nicht aktiviert.";
$lang['GatewayPayments.!error.transaction_id.exists'] = "Die Transaktion konnte für diesen Kunden nicht gefunden werden.";
$lang['GatewayPayments.!error.account_id.exists'] = "Das Zahlungskonto konnte für diesen Kunden nicht gefunden werden.";
$lang['GatewayPayments.!error.contact_id.exists'] = "Der Kontakt wurde für diesen Kunden nicht gefunden.";
$lang['GatewayPayments.!error.type.valid'] = "Die Zahlungsart wird für dieses Gateway nicht unterstützt.";
$lang['GatewayPayments.!error.type.instance'] = "Das Gateway unterstützt Zahlungen auf diese Weise nicht.";
$lang['GatewayPayments.!error.reference_id.store'] = "

Das Zahlungsgateway konnte das Zahlungskonto nicht speichern.
";
$lang['GatewayPayments.!error.reference_id.update'] = "Die Zahlungsschnittstelle konnte den Account nicht bearbeiten.";
$lang['GatewayPayments.!error.reference_id.remove'] = "Das Payment-Gateway konnte nicht das Zahlungskonto entfernen.";
$lang['GatewayPayments.!error.response_status'] = "Das Zahlungsgateway hat eine unerwartete Antwort zurückgegeben.";
$lang['GatewayPayments.!error.gateway.declined'] = "Die Zahlung wurde abgelehnt.";
$lang['GatewayPayments.!error.gateway.error'] = "Das Zahlungs-Gateway hat bei der Verarbeitung der Anfrage einen Fehler zurückgegeben.";
?>