<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Languages.!error.code.valid'] = "Die Standartsprache 'en_us' wurde gelöscht.";
$lang['Languages.!error.code.format'] = "Der Sprachcode ist nicht korrekt formatiert.";
$lang['Languages.!error.code.unique'] = "Dieser Sprachcode existiert bereits für diese Firma.";
$lang['Languages.!error.company_id.format'] = "Die Unternehmens-ID scheint nicht zu stimmen.";
$lang['Languages.!error.name.format'] = "Der Name der Sprache darf nicht leer sein.";
?>