<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['NonmerchantGateway.!error.invalid'] = "

Es wurde eine ungültige oder nicht erkannte Zahlungsantwort empfangen.
";
$lang['NonmerchantGateway.!error.transaction_not_found'] = "Die Transaktion ist für die Verarbeitung dieser Aktion ungültig oder nicht mehr verfügbar.";
$lang['NonmerchantGateway.!error.unsupported'] = "Das Gateway unterstützt diese Aktion nicht.";
$lang['NonmerchantGateway.!error.general'] = "Es trat ein Fehler auf, bei dem Versuch den Request über das Gateway zu verarbeiten.";
?>