<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PackageOptionGroups.!error.company_id.exists'] = "Bitte geben Sie eine gültige Firmen ID ein.";
$lang['PackageOptionGroups.!error.name.empty'] = "Geben Sie einen Gruppennamen an!";
$lang['PackageOptionGroups.!error.name.length'] = "Der Gruppenname darf nicht länger als 128 Zeichen sein.";
$lang['PackageOptionGroups.!error.group_id.exists'] = "Ungültige Paketoptionsgruppen-ID";
?>