<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['States.!error.code.format'] = "Der Statuscode muss alphanumerisch sein, wie in ISO 3166-2 definiert.";
$lang['States.!error.country_alpha2.format'] = "Country Alpha2 muss 2 Alpha-Zeichen sein.";
$lang['States.!error.country_alpha2.in_use'] = "Der Alpha2-Ländercode %1\$s und der Unterteilungscode %2\$s sind bereits vergeben."; // %1$s is the alpha2 country code, %2$s is the state code
$lang['States.!error.name.format'] = "Bitte gib das Bundesland ein.";
?>