<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Users.!error.username.empty'] = "Bitte Benutzernamen eingeben.";
$lang['Users.!error.username.unique'] = "Dieser Benutzername wurde bereits vergeben.";
$lang['Users.!error.current_password.matches'] = "Ungültiges Passwort";
$lang['Users.!error.new_password.format'] = "Bitte geben Sie ein Passwort ein das mindestens 6 Zeichen lang ist.";
$lang['Users.!error.new_password.matches'] = "Die Passwörter stimmen nicht überein.";
$lang['Users.!error.two_factor_mode.format'] = "Ungültiger Zwei-Faktor-Modus.";
$lang['Users.!error.username.auth'] = "Keine Einträge für diese Benutzer/Passwort Kombination vorhanden.";
$lang['Users.!error.user_id.exists'] = "Ungültige Benutzer-ID";
$lang['Users.!error.username.attempts'] = "Zu viele fehlgeschlagene Anmeldeversuche wurden erkannt.";
$lang['Users.!error.clients.exist'] = "Der Benutzer kann nicht gelöscht werden, da dem Benutzer mindestens ein Kunde zugewiesen ist.";
$lang['Users.!error.two_factor_key.format'] = "Ungültiger Zwei-Faktor-Schlüssel";
$lang['Users.!error.username.company'] = "Sie sind nicht berechtigt, sich an diesem Ort anzumelden.";
?>