<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Cart.index.header_cart'] = "Bestellübersicht";
$lang['Cart.index.header_note'] = "Alle anfallenden Steuern werden nach Ihrer Registrierung oder Anmeldung berechnet.";
$lang['Cart.index.table_description'] = "Beschreibung";
$lang['Cart.index.table_term'] = "Begriff";
$lang['Cart.index.table_qty'] = "Menge";
$lang['Cart.index.table_price'] = "Preis";
$lang['Cart.index.edit_item'] = "Bearbeiten";
$lang['Cart.index.remove_item'] = "Löschen";
$lang['Cart.index.have_coupon'] = "Gutscheincode verwenden";
$lang['Cart.index.coupon'] = "Coupon";
$lang['Cart.index.order_more_btn'] = "Klicken Sie, um weitere Artikel zu bestellen";
$lang['Cart.index.order_more_note'] = "

Oder registrieren/melden Sie sich an und fahren mit der Zahlung fort.
";
?>