<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Hubtel.name'] = "Hubert";
$lang['Hubtel.client_id'] = "Kunden ID";
$lang['Hubtel.client_secret'] = "Client Secret";
$lang['Hubtel.buildprocess.submit'] = "Mit Hubtel bezahlen";
$lang['Hubtel.!error.client_id.valid'] = "Sie müssen eine gültige Client-ID eingeben.";
$lang['Hubtel.!error.client_secret.valid'] = "Sie müssen ein gültiges Client Secret eingeben.";
?>