<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PackageRevenue.description'] = "Berechnet die Einnahmen aus einer Währung für jedes Paket, indem die bezahlten Rechnungspositionen, die mit dem Paket verbunden sind, summiert werden.";
$lang['PackageRevenue.options.currency'] = "Währung";
$lang['PackageRevenue.heading.package_name'] = "Paket";
$lang['PackageRevenue.heading.module_name'] = "Modul";
?>