<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Kassacompleet.!error.api_key.empty'] = "Bitte geben Sie einen API-Schlüssel ein";
$lang['Kassacompleet.!error.api_key.valid'] = "API-Schlüssel ist ungültig";
$lang['Kassacompleet.name'] = "Kredit- / Debitkarte (Kassa Compleet)";
$lang['Kassacompleet.api_key'] = "API-Schlüssel";
$lang['Kassacompleet.tooltip.api_key'] = "Um den Testmodus zu verwenden, geben Sie einfach einen API-Schlüssel eines Testkontos ein";
$lang['Kassacompleet.buildprocess.submit'] = "Mit Kassa Compleet zahlen";
$lang['Kassacompleet.description'] = "Kassa Compleet Integration für die Zahlungsart Kreditkarte.";
?>