<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.!error.export_found'] = "Der Export wurde im Dateisystem nicht gefunden.";
$lang['AdminMain.index.page_title'] = "Massenmailer";
$lang['AdminMain.index.boxtitle'] = "Massenmailer-Jobs";
$lang['AdminMain.index.categorylink_compose'] = "Erstellen Sie neues Mailing";
$lang['AdminMain.index.job_task_total'] = "%1\$s / %2\$s"; // %1$s is the number of mailing tasks completed, %2$s is the total number of mailing tasks
$lang['AdminMain.index.heading_date'] = "Datum hinzugefügt";
$lang['AdminMain.index.heading_type'] = "Art";
$lang['AdminMain.index.heading_status'] = "Status";
$lang['AdminMain.index.heading_complete'] = "Abgeschlossen";
$lang['AdminMain.index.heading_options'] = "Optionen";
$lang['AdminMain.index.option_export'] = "Exportieren";
$lang['AdminMain.index.type.email'] = "E-Mail";
$lang['AdminMain.index.type.export'] = "Export";
$lang['AdminMain.index.email_to'] = "An";
$lang['AdminMain.index.email_from'] = "Von";
$lang['AdminMain.index.email_subject'] = "Thema";
$lang['AdminMain.index.email_to_recipients'] = "%1\$s Empfänger"; // %1$s is the number of email recipients
$lang['AdminMain.index.no_export_details'] = "Es sind keine Angaben zum Export vorhanden.";
$lang['AdminMain.index.no_results'] = "Derzeit gibt es keine Mailing-Jobs.";
?>