<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MassMailerController.!success.mail_job_added'] = "Der Mailing-Job wurde erfolgreich in die Warteschlange gestellt. Emails werden per cron verschickt.";
$lang['MassMailerController.!success.export_job_added'] = "Der Export wurde erfolgreich in die Warteschlange gestellt. Es wird auf der Listungsseite verfügbar gemacht, sobald es über cron verarbeitet wurde.";
?>