<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MassMailerJobs.!error.company_id.valid'] = "Bitte geben Sie eine Firmen ID an.";
$lang['MassMailerJobs.!error.status.format'] = "

Bitte wählen Sie einen gültigen Status aus.
";
$lang['MassMailerJobs.!error.task_count.format'] = "Die Anzahl der Aufgaben muss eine positive Ganzzahl sein.";
$lang['MassMailerJobs.!error.data.empty'] = "Bitte fügen Sie zusätzliche Jobinformationen hinzu.";
$lang['MassMailerJobs.!error.date_added.format'] = "Bitte geben Sie ein Datum ein.";
$lang['MassMailerJobs.!error.job_id.exists'] = "Ungültige Job-ID";
$lang['MassMailerJobs.status.pending'] = "Ausstehend";
$lang['MassMailerJobs.status.in_progress'] = "In Bearbeitung";
$lang['MassMailerJobs.status.complete'] = "Komplett";
?>