<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MassMailerPlugin.name'] = "Massen-Mailer";
$lang['MassMailerPlugin.nav_secondary_staff.admin_main'] = "Massenmailer";
$lang['MassMailerPlugin.permission.admin_main'] = "Massenmailing-Angebote";
$lang['MassMailerPlugin.permission.admin_filter'] = "Mass Mailer Filter";
$lang['MassMailerPlugin.permission.admin_compose'] = "

Massenversender E-Mail verfassen
";
$lang['MassMailerPlugin.cron.export_name'] = "

Mailing-Export erstellen
";
$lang['MassMailerPlugin.cron.export_desc'] = "Erstellt eine CSV-Datei für jeden ausstehenden Export von Massenmailings.";
$lang['MassMailerPlugin.cron.mass_mail_name'] = "Senden Sie Massen-E-Mail";
$lang['MassMailerPlugin.cron.mass_mail_desc'] = "Sendet eine Massen-E-Mail für einen ausstehenden Mailing-Job.";
?>