<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Cart.index.header_cart'] = "Bestellung überprüfen";
$lang['Cart.index.table_description'] = "Beschreibung";
$lang['Cart.index.table_term'] = "Begriff";
$lang['Cart.index.table_qty'] = "Anzahl";
$lang['Cart.index.checkout_btn'] = "Auschecken";
$lang['Cart.index.order_more_btn'] = "Bestellen Sie mehr Artikel";
$lang['Cart.index.edit_item'] = "Bearbeiten";
$lang['Cart.index.remove_item'] = "Löschen";
$lang['Cart.index.empty_cart'] = "Ihr Warenkorb ist leer. Beginnen Sie mit der <a href=\"%1\$s\"> Auswahl eines Plans »</a>"; // %1$s is the URI to the order home page
?>