<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Signup.index.header_login_or_signup'] = "

Registrieren oder Anmelden
";
$lang['Signup.index.link_resetpassword'] = "
Mein Passwort zurücksetzen
";
$lang['Signup.index.header_login'] = "

Einloggen
";
$lang['Signup.index.heading_contact'] = "Kontaktinformation";
$lang['Signup.index.heading_billing'] = "Abrechnungsdaten";
$lang['Signup.index.heading_authentication'] = "Authentifizierung";
$lang['Signup.index.heading_settings'] = "Zusätzliche Einstellungen";
?>