<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Kassacompleetideal.!error.api_key.empty'] = "Bitte geben Sie einen API-Schlüssel ein";
$lang['Kassacompleetideal.!error.api_key.valid'] = "API-Schlüssel ist ungültig";
$lang['Kassacompleetideal.name'] = "iDeal (Kassa Compleet)";
$lang['Kassacompleetideal.api_key'] = "API-Schlüssel";
$lang['Kassacompleetideal.tooltip.api_key'] = "Um den Testmodus zu verwenden, geben Sie einfach einen API-Schlüssel eines Testkontos ein";
$lang['Kassacompleetideal.buildprocess.issuer_id'] = "iDeal Issuer";
$lang['Kassacompleetideal.buildprocess.submit'] = "Mit iDeal über Kassa Compleet bezahlen";
?>