<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientMain.index.page_title'] = "Downloads";
$lang['ClientMain.index.boxtitle_downloads'] = "Downloads";
$lang['ClientMain.index.no_downloads'] = "In diesem Bereich sind keine Downloads verfügbar.";
$lang['ClientMain.!text.root_directory'] = "Start";
$lang['ClientMain.index.login'] = "Sie müssen sich anmelden, um Downloads in diesem Abschnitt anzeigen zu können.";
?>