<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DownloadManagerFiles.!error.category_id.exists'] = "Bitte wählen Sie eine gültige Kategorie aus";
$lang['DownloadManagerFiles.!error.company_id.exists'] = "

Ungültige Firmen-ID
";
$lang['DownloadManagerFiles.!error.name.empty'] = "Bitte geben Sie einen Namen für diese Datei ein.";
$lang['DownloadManagerFiles.!error.file_name.format'] = "Bitte laden Sie eine Datei hoch oder geben Sie einen gültigen Pfad zur Datei an.";
$lang['DownloadManagerFiles.!error.public.format'] = "Die öffentliche Verfügbarkeitsoption hat ein ungültiges Format.";
$lang['DownloadManagerFiles.!error.public.assignment'] = "Die Datei muss entweder für die Öffentlichkeit, für Kundengruppen oder für Pakete verfügbar sein.";
$lang['DownloadManagerFiles.!error.permit_client_groups.format'] = "Die Verfügbarkeitsoption für die Clientgruppe hat ein ungültiges Format.";
$lang['DownloadManagerFiles.!error.file_groups.format'] = "

Mindestens eine ausgewählte Kundengruppe kann nicht hinzugefügt werden, da sie nicht vorhanden ist.
";
$lang['DownloadManagerFiles.!error.permit_packages.format'] = "

Die Paketverfügbarkeitsoption hat ein ungültiges Format.
";
$lang['DownloadManagerFiles.!error.file_packages.format'] = "Mindestens ein ausgewähltes Paket kann nicht hinzugefügt werden, da es nicht vorhanden ist.";
$lang['DownloadManagerFiles.!error.file_id.exists'] = "

Die zu aktualisierende Datei ist nicht vorhanden.
";
?>