<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2023, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Paystack.name'] = "Paystack Standard";
$lang['Paystack.secret_key'] = "Paystack Secret Key";
$lang['Paystack.buildprocess.submit'] = "Mit Paystack zahlen";
$lang['Paystack.!error.secret_key.valid'] = "Der geheime Schlüssel muss mindestens 40 Zeichen lang sein.";
?>